### PR TITLE
ol3-cesium update

### PR DESCRIPTION
**Pull request by oterral**
ol3 v3.16.0
ol3-cesium v1.16
cesium 1.21

[Test](https://mf-geoadmin3.dev.bgdi.ch/teo_up/?lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&X=190000.00&Y=660000.00&zoom=1&dev3d=true&debug&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,)

### CODE REVIEW

**Comment by gjn** [comment]
@mariavkourouni @pfanguin @rfrancel We need a test session for this PR that validates the whole application on most browsers.

Please have a close look at the [open layers release notes for 3.15 and 3.16](https://github.com/openlayers/ol3/releases)

Testing should include:
- Most browsers, especially IE9, IE10, FF and mobile browsers
- Test all drawing features on IE, chrome and FF
- Test all types of layers: wmts, wms internal and external, geojson (hydroweb), treasurehunt, external kmls and their interaction (tooltip)

@pfanguin Could you coordinate the testing effort?

**Comment by loicgasser** [comment]
I think we have a fix for https://github.com/geoadmin/mf-geoadmin3/issues/3118
thanks to https://github.com/openlayers/ol3/pull/5364

**Comment by loicgasser** [comment]
FYI dead link I redeploy the branch

**Comment by gjn** [comment]
Can't reproduce #3118 on prod...

**Comment by loicgasser** [comment]
Try https://map.geo.admin.ch/?lang=en&topic=luftbilder&bgLayer=ch.swisstopo.pixelkarte-grau&X=181000.00&Y=630500.00&zoom=1&layers=ch.swisstopo.lubis-luftbilder_schwarzweiss,ch.swisstopo.lubis-luftbilder_farbe&layers_timestamp=19321231,&catalogNodes=1179,1180,1186&time=1932

**Comment by gjn** [comment]
yes!. hardly visible on chrome here, better visible in IE9. Depends on performance of javascript engine, I think.

**Comment by gjn** [comment]
Why did you merge this? It needs alot of testing...(see my comments higher up)

**Comment by loicgasser** [comment]
I pushed force after rebase and nothing..., branch was old no make user and seems that the deploybranch failed as a result. I am preparing a new PR.

**Comment by loicgasser** [comment]
FYI it is not merged. It closed automatically.

**Comment by gjn** [comment]
image

This had me confused...

**Comment by loicgasser** [comment]
I know it has been used trillions of times. Github is confused.

**Comment by gjn** [comment]
uff. that's bad.

**Pull request closed without merging**
