### PR TITLE
Teo fix deploy

### PR DESCRIPTION
**Pull request by oterral**
Fix regression (explanations [here](https://github.com/geoadmin/mf-geoadmin3/blame/master/src/components/map/WmsService.js#L80)) introduced by https://github.com/geoadmin/mf-geoadmin3/pull/3318

### CODE REVIEW

**Comment by gjn** [comment]
My fix broke the wms id in permalink?

**Comment by oterral** [comment]
Yes we already have this problem if the id in the permalink is changed before the re-ordering of layers (this re-ordering happens after all kmls are loaded), the re-ordering does a infinite loop and block the UI..

**Comment by gjn** [comment]
Thanks for the info.

Didn't test all use cases. My bad.

**Comment by gjn** [comment]
Might be worth a selenium test.

**Pull request merged**
