### PR TITLE
BGDIINF_SB-2395: + topic bav, - topic emapis

### PR DESCRIPTION
**Pull request by rebert**

### CODE REVIEW

**Comment by rebert** [comment]
todo: waiting for translation topic_bav_tooltip

**Review by ltclm — APPROVED** [review]
thank you

**Comment by rebert** [comment]
https://sys-s.dev.bgdi.ch/9868a1fd23

**Review by pakb — APPROVED** [review]
As a good introductory exercice, could you also add this new sprite and related CSS to https://github.com/geoadmin/web-mapviewer ? 😜

**Pull request merged**
