### PR TITLE
[Stand-by] Add swisssurface3d for the shop

### PR DESCRIPTION
**Pull request by Sgachet**
<jenkins>A test link will be added here if the deploy on int succeeded.</jenkins>

<jenkins>[Test link](https://mf-geoadmin3.int.bgdi.ch/gas_shop_swisssurface3d/1905071129/index.html)</jenkins>

### CODE REVIEW

**Comment by Sgachet** [comment]
Not needing for the moment. Standby

**Comment by pakb** [comment]
@Sgachet Do we need this before today's deploy?

**Comment by Sgachet** [comment]
@pakb nope, this PR is in standby for the moment

**Comment by pakb** [comment]
@pauloamado do we still need this?

**Pull request closed without merging**
