### PR TITLE
Mapfish print v3

### PR DESCRIPTION
**Pull request by Jenselme**
Allow to print with mapfish print v3 with the mf-geoadmin3 interface. This component fits our needs. Let me know if I must change things so this PR can be merged.

- mapfish-print war used: https://github.com/Geoportail-Luxembourg/geoportailv3/blob/master/print/print-servlet.war
- mapfish-print configuration used: http://jenselme.perso.centrale-marseille.fr/visible/geojb.zip As of this moment, only the configuration for a4_portrait is complete (with northmap and legend page only if legend is asked). Based on: https://github.com/Geoportail-Luxembourg/geoportailv3/tree/master/print/print-apps/geoportailv3
- Based on components from [ngeo](https://github.com/camptocamp/ngeo):
  - https://github.com/camptocamp/ngeo/blob/master/src/services/print.js
  - https://github.com/camptocamp/ngeo/blob/master/src/services/printutils.js
- Pending PR at ngeo (applied on this version):
  - [Support map rotation for printing](https://github.com/camptocamp/ngeo/pull/231)
  - [Allow tiles from a TileWMS to be printed](https://github.com/camptocamp/ngeo/pull/226)

Side note: to make the war work correctly with java8, I had to delete `<deploy_print_root>/WEB-INF/lib/jdtcore-3.1.0.jar` and replace it by the 3.1.1 version of jdtcore: http://mvnrepository.com/artifact/org.eclipse.jdt/core/3.1.1

### CODE REVIEW

**Comment by procrastinatio** [comment]
OK, I have a look.

**Comment by Jenselme** [comment]
I corrected goog.require for ngeo

**Comment by procrastinatio** [comment]
The print configuration for _map.geo.admin.ch_ is pretty complex:

* Classic print with a map, legend, disclaimer, localized text, etc.
* Every year of layer `ch.swisstopo.zeitreiehen`may be printed, each year on a different page (up to 50 pages!). For this kind of request, we do a polling to check when the PDF is ready.
* Some legends are already PDF and have to be added after the generated PDF.

To support our special WMTS configs, I had to use the latest MapFish Print code from respository (after this PR https://github.com/mapfish/mapfish-print/pull/211)
https://github.com/geoadmin/mf-chsdi3/pull/1033

The `ngeo` looks pretty good, but from our past experience of the previous release of _map.ge.admin.ch_ based on `GeoExt`, we did almost entirely reimplemented the print function to fit our needs.

For now, I did focus on the server part, as this will decide the next steps.

All in all, we will migrate to MapFish Print v3, but no deadline is fixed now. But as we use more and more vectors in _map.geo.admin.ch_ and the support for them is far better in V3 (halo, svg, etc.), I think we will move sooner as expected.

**Comment by Jenselme** [comment]
Your needs are more advanced than ours.

We only need: map, legend and all our legends are generated on the fly. In my opinion, the code from ngeo is a good start. Maybe you will just need to extend it. Whatever you decide, keep me posted!

**Comment by gjn** [comment]
I hope it's ok if we close this as v3 printing is not top priority for us.

**Comment by Jenselme** [comment]
> I hope it's ok if we close this as v3 printing is not top priority for us.

No problem. Feel free to look at this PR when you will work on the switch.

**Pull request closed without merging**
