### PR TITLE
Update ImportController.js

### PR DESCRIPTION
**Pull request by siramon**
Added WMS Canton Schaffhausen

(Edit: <del>Adding</del><ins>Added</ins>)

### CODE REVIEW

**Comment by siramon** [comment]
@davidoesch, you asked "Still in progress?"

No, finished. Do I have to do something different? It's my first PR.

**Comment by davidoesch** [comment]
Lgtm

**Comment by davidoesch** [comment]
@siramon : all ok— 16.9 online . Fingers crossed

**Comment by pakb** [comment]
Could it be possible to implement HTTP HEAD handling on your WMS server? What goeadmin does is that it requires the getCapabilities with a HTTP HEAD request (only headers, no content) to see if it can be used as is or if it needs to be passed through our `service-proxy`. But your WMS doesn't handle HEAD requests and rejects it.

**Comment by davidoesch** [comment]
@siramon see feedback above

**Comment by siramon** [comment]
I have forwarded your feedback to the responsible person. The feedback will follow sometime in September.

**Comment by romefi** [comment]
The HEAD request should work now. Could you test it? If it doesn't work or a specific header is missing, please let me know. Thanks.

**Comment by pakb** [comment]
I still get a HTTP 405 in return, here's my request
```
HEAD /wms?SERVICE=WMS&SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.3.0 HTTP/1.1
Host: wms.geo.sh.ch
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Accept: application/json, text/plain, */*
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
DNT: 1
Origin: https://mf-geoadmin3.int.bgdi.ch
Sec-Fetch-Site: cross-site
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: https://mf-geoadmin3.int.bgdi.ch/ltbtp_test_pr_5021/2008140934/index.html?topic=ech&lang=en&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege&layers_opacity=1,1,1,0.8&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,fr;q=0.8
```
and here's the response
```
HTTP/1.1 405 Method Not Allowed
Date: Tue, 01 Sep 2020 13:19:18 GMT
Server: Secure Entry Server
Allow: GET
Content-Length: 73
Content-Type: application/json; charset=utf-8
Access-Control-Allow-Origin: https://mf-geoadmin3.int.bgdi.ch
Access-Control-Allow-Credentials: true
X-Powered-By: ASP.NET
Keep-Alive: timeout=10, max=300
Connection: Keep-Alive
```

**Comment by romefi** [comment]
Sorry for the delay, we had to adjust our proxy to make HEAD-Requests available. Anyway, should work now. Could you test? If anything is missing in the HEAD, let me know.

Thanks

**Comment by pakb** [comment]
Perfect, thanks for the addition of this new rules in your proxy. It now works without any network error.

**Comment by pakb** [comment]
this has been deployed on prod

**Comment by siramon** [comment]
Thank you!

**Pull request merged**
