### PR TITLE
Update olcesium and ol

### PR DESCRIPTION
**Pull request by oterral**
Cesium and ol are now loaded via npm modules in olcesium. So we use `npm link` to link ol cesium with our custom version of ol and cesium

[test](//mf-geoadmin3.int.bgdi.ch/teo_up/index.html)

### CODE REVIEW

**Comment by oterral** [comment]
Ready to review

**Comment by oterral** [comment]
This time I think it's good to review.

I sent you a big kml to test @loicgasser

**Comment by loicgasser** [comment]
Works well, on Explorer I get unsufficient memory and the browser refuses to load the KML, but this is the same in prod.

**Comment by oterral** [comment]
Labels bug is fixed through a patch. I will remove it in the future version if needed.

**Comment by loicgasser** [comment]
labels ok, chrome, firefox and edge have similar perfs. Good to go for me.

**Pull request merged**
