### PR TITLE
Update ImportController.js with swissdatacube WMTS

### PR DESCRIPTION
**Pull request by davidoesch**
added swissdatacube WMTS

<jenkins>[Test link](https://mf-geoadmin3.int.bgdi.ch/ltoed_WMTS_swissdatacube/index.html)</jenkins>

### CODE REVIEW

**Comment by davidoesch** [comment]
You will love that link https://s.geo.admin.ch/7d17d2b0ce , marc

**Comment by procrastinatio** [comment]
@gjn Less snow is kind of sad

**Comment by procrastinatio** [comment]
Would it not be better to have meaningfull WMS descriptions instead of url?

**Comment by davidoesch** [comment]
Fully agree Marc- part of RE4 There is even a spec for it. The idea would be to have them description directly fed from geocat

**Pull request merged**
