### PR TITLE
Use the new proxy

### PR DESCRIPTION
**Pull request by procrastinatio**
Dropbox uses redirect, we had to adapt the proxy.

[Demo](https://mf-geoadmin3.dev.bgdi.ch/fix_5227_GPX_CORS/2103051805/index.html)

Try using this GPX: https://www.dropbox.com/s/i4qtmflv7vdpfhp/2021-03-04_325666018_TransalpMelsnachScuol.gpx?dl=1

and you should see a thin red line in the Graubünden

See also: https://github.com/geoadmin/service-proxy/pull/53

Looks like `geoadmin`is stilll using the old `ranjer`proxy on `dev`

### CODE REVIEW

**Comment by davidoesch** [comment]
thanks ---

**Comment by procrastinatio** [comment]
Merging and deploying next week...

**Review by hansmannj — APPROVED** [review]
:+1:

**Review by pakb — COMMENTED** [review]
Are we only modifying `rc_dev`? I don't really get what we are doing here

**Comment by boecklic** [comment]
> Are we only modifying `rc_dev`? I don't really get what we are doing here

Yeah, `service-proxy.int|prod.bgdi.ch` are already pointing to the new runtime location of service-proxy, `service-proxy.dev.bgdi.ch` is pointing to the old one. So only dev needs to be changed

**Pull request merged**
