### PR TITLE
Set the pitch to -50 deg when flying to a location

### LINKED ISSUE #2713: location search: zoom to : tilt in 45°
When choosing a result in swisssearch, eg creux du van

the camera position is looking into nadir
https://mf-geoadmin3.dev.bgdi.ch/?dev3d=true&topic=geol&lang=fr&bgLayer=ch.swisstopo.pixelkarte-farbe&lon=6.73053&lat=46.93696&elevation=2509&heading=360.000&pitch=-90.000&catalogNodes=1786,1787

expecting result when in 3D: pitch 45° to north
https://mf-geoadmin3.dev.bgdi.ch/?dev3d=true&topic=geol&lang=fr&bgLayer=ch.swisstopo.pixelkarte-farbe&lon=6.73067&lat=46.92857&elevation=2151&heading=359.347&pitch=-45.000&catalogNodes=1786,1787

### PR DESCRIPTION
**Pull request by fredj**
Fixes #2713

### CODE REVIEW

**Comment by fredj** [comment]
demo: https://mf-geoadmin3.dev.bgdi.ch/flyTo_pitch/?dev3d=true

**Comment by cedricmoullet** [comment]
It makes a kind of jump when it arrives at destination. Any way to make that smoother ?

**Comment by cedricmoullet** [comment]
I tested with Bern and Zürich

**Comment by fredj** [comment]
We have this jump between the animations because cesium is not able to `flyTo` a location with a specific pitch.

To do so we need to know the altitude at the destination and compensate (move the camera south)

**Comment by fredj** [comment]
See #2908 for a better alternative

**Pull request closed without merging**
