### PR TITLE
Fix select box with dnd on Firefox

### LINKED ISSUE #3197: FF: select box does not work
FF: select box does not work
Windows 10 mit Firefox 44 od. 45 => funktioniert nicht
Windows 7 mit Firefox 42 => funktioniert ebenfalls nicht

unbenannt

### PR DESCRIPTION
**Pull request by Jenselme**
An alternate solutions that avoids the patch in slipjs. From what I understood, the bug is related to how Firefox handles click on pseudo elements. I don't know why it worked before thought.

Fix #3197

### CODE REVIEW

**Comment by gjn** [comment]
I've deployed this [for testing here](https://mf-geoadmin3.dev.bgdi.ch/ioda-net/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,)

It works fine on FF42, IE11 and chrome latest.

@davidoesch @cedricmoullet Could you test on Safari/Mac envoriments and on Android. I'll test on some mobile devices as well.

This is for #3197 FF bug.

**Comment by davidoesch** [comment]
Tested Android 6

**Comment by cedricmoullet** [comment]
Work on Chrome 48/Windows 7, IE11/Windows 7, FF 42/Mac 10.11, Chrome 50/Mac
10.11, Safari 9/Mac 10.11,FF 45/Mac 10.11, Safari/IOS 9.2.1
I spent a lot of time to understand that I had to click, wait and then
move.
1. Shouldn't we change the cursor when "move mode" is activated ?
2. Is the waiting time too long ?
3. When you click on the year of the "Zeitreise" layer, drag and drop will
work, but it opens then the year selection dialog when you end the move ->
it shouldn't be open.

2016-03-13 21:43 GMT+01:00 David Oesch <notifications@github.com>:

> Tested Android 6
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/pull/3202#issuecomment-196049264>
> .
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>

**Comment by davidoesch** [comment]
1)Change coursor when move : +1 (as in gmail)
2) waiting time to long ---imho it is ok
3) click zeitreise, year opens: could not reproduce on chrome48/win7 and ff/win7 and

**Comment by cedricmoullet** [comment]
3) -> on FF/mac

2016-03-14 8:14 GMT+01:00 David Oesch <notifications@github.com>:

> 1)Change coursor when move : +1 (as in gmail)
> 2) waiting time to long ---imho it is ok
> 3) click zeitreise, year opens: could not reproduce on chrome48/win7 and
> ff/win7 and
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/pull/3202#issuecomment-196175799>
> .
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>

**Comment by gjn** [comment]
1) +1
2) I thinks it's good as well. But it's a compromise because of touch events (to be able to differntiate between click and click/hold on mobile devices
3) can reproduce on FF42, windows. 

4) The same as in 3 is happening for the remove button and the setting button. It only happens when you start _and_ end the drag/drop on the given icon. This behaviour is already like this in production in FF. I think best way is to really fully patch slipjs for FF/-moz detections.

@Jenselme Can I ask you to have a look once again?

**Comment by Jenselme** [comment]
1) +1. I can make a PR for this once #3197 is fixed
2) I think it's a good compromise
3 + 4) I have that with the -moz- patch on slipjs. I'll see what I can do.

**Comment by Jenselme** [comment]
@gjn Just updated the PR with one possible solution: disabling dnd on buttons. Let me know if that's OK.

**Comment by gjn** [comment]
Linter fails (make lint)

**Comment by gjn** [comment]
@cedricmoullet @davidoesch I've updated [testlink](https://mf-geoadmin3.dev.bgdi.ch/ioda-net/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,)

Not being able to move elements on 'remove' button and 'settings' buttong is acceptable.

Thoughts?

**Comment by oterral** [comment]
I'm -1 for this PR, the Font awesome  checkbox mechanism is sensitive. If the problem is caused by Slipjs, the fix MUST be in slipjs.

**Comment by gjn** [comment]
In general we agree - but we need something for tomorrow.

#3201 lacks the button exception, I think.

**Comment by oterral** [comment]
We could disable DnD for all input, span and button. We already do that for input[type=range]

**Comment by gjn** [comment]
I would be ok with this. Could you prepare a PR?

**Comment by oterral** [comment]
I'm just against this commit https://github.com/ioda-net/mf-geoadmin3/commit/8c3d74a3e9249e308b4241cd979711d3cedb8f41,  the other looks good

**Comment by davidoesch** [comment]
+1 for "Not being able to move elements on 'remove' button and 'settings' buttong is acceptable."

**Comment by Jenselme** [comment]
@oterral I don't know if the problem comes from SlipJS or Firefox. The problem I have with the other fix is that we need to make a patch for SlipJS that is unlikely to be accepted upstream. See https://github.com/pornel/slip/issues/66.

But I am OK to update the other PR with my last patch if you want.

**Comment by gjn** [comment]
@Jenselme I'll close this one as we'll take #3209 
Thanks alot for your efforts!

**Pull request closed without merging**
