### PR TITLE
Assure right order of execution on topic change

### PR DESCRIPTION
**Pull request by gjn**
Fix for https://github.com/geoadmin/mf-geoadmin3/issues/3153

Will be part of this afternoon's deploy for sonnendach.

### CODE REVIEW

**Comment by gjn** [comment]
This is maybe not the correct fix, but it's working.

Probably more correct would be to not remove the new topic layers in the layer manager, but that would mean first refactoring [this code](https://github.com/geoadmin/mf-geoadmin3/blob/master/src/components/map/MapService.js#L2076) to be usable in more than one location.

**Comment by loicgasser** [comment]
issue with some prio?

**Comment by gjn** [comment]
The refactoring? I'll take care of it.

**Comment by oterral** [comment]
I think there is general problem. We should keep in mind this should work with only the map and the gaTopic component (without poermlink stuff).

And yes the LayerManager shouldn't  listen for the gaTopicChange event.

**Comment by gjn** [comment]
Fully agree. It's architectural problem.

`gaTopicChange` should never be listened to by independant components that have nothing to do with topic changes. Only application controllers should listen to this event and dispatch them to more component specific messages/events. Application logic (if in A) happens this, then B) should react as follows and C) in this way) should be outside of components.

So in this case, the application controller should listen to `gaTopicchange` and dispatch a (new) `removeAllLayers` message to the layermanager component.

We have other such violations in our code. We should try to address them.

Also, mapservice file is too big now. Should be split up into components proper and application specific controllers/code.

**Comment by oterral** [comment]
Yes we should split the MapService.

> So in this case, the application controller should listen to gaTopicchange and dispatch a (new) removeAllLayers message to the layermanager component.
No need to dispatch, at least to the layermanager because it is automatically updated when a layer is added or removed from the map, it doesn't care if the topic change or not.

**Comment by gjn** [comment]
It's because of this requirement: https://github.com/geoadmin/mf-geoadmin3/issues/3122 . Application state needs to be initialized. But I agree, this shouldn't be done in the layer manager, but in a application controller.

**Pull request merged**
