### PR TITLE
Space between copyright sign

### PR DESCRIPTION
**Pull request by procrastinatio**
...hard to tell what this PR is doing. Maybe adding a single space...

See https://github.com/geoadmin/mf-geoadmin3/issues/4103

and test [with](https://mf-geoadmin3.int.bgdi.ch/mom_copyright_print/index.html)

### CODE REVIEW

**Comment by oterral** [comment]
jenkins test

**Comment by oterral** [comment]
jenkins test

**Comment by oterral** [comment]
jenkins test

**Comment by oterral** [comment]
jenkins test

**Comment by oterral** [comment]
jenkins test

**Comment by oterral** [comment]
jenkins test

**Comment by oterral** [comment]
jenkins test

**Comment by oterral** [comment]
jenkins test

**Comment by oterral** [comment]
jenkins test

**Comment by loicgasser** [comment]
jenkins test

**Comment by loicgasser** [comment]
jenkins test

**Comment by loicgasser** [comment]
jenkins test

**Comment by loicgasser** [comment]
jenkins test

**Comment by oterral** [comment]
jenkins test

**Comment by oterral** [comment]
jenkins test

**Pull request merged**
