### PR TITLE
Update ol to 3.6.0

### PR DESCRIPTION
**Pull request by oterral**
[Test link](https://mf-geoadmin3.dev.bgdi.ch/teo_update_ol_3.6/?lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&X=190000.00&Y=660000.00&zoom=1&layers=ch.bafu.hydroweb-messstationen_gefahren)

### CODE REVIEW

**Comment by cedricmoullet** [comment]
Tested on iPhone 6 works fine

Envoyé de mon iPhone

**Comment by loicgasser** [comment]
good on chrome android as well.

**Comment by gjn** [comment]
Drawing does not seem to work properly (no kml file is stored). In addition, on IE11, the drawing layer is not displayed all the time (start drawing with polylines, which disappear)

**Comment by oterral** [comment]
Draw fixed

**Comment by cedricmoullet** [comment]
@kandre @daguer @alcapat Could you test the test link with Squash TM today ?

**Comment by cedricmoullet** [comment]
@kandre @daguer @alcapat what is the status of your tests ?

**Comment by kandre** [comment]
Procedure on squash TM is only ready on integration at the moment. Will be tested on int with squash TM

**Pull request merged**
