### PR TITLE
Use data-uri for logos

### PR DESCRIPTION
**Pull request by oterral**
This PR changes a little bit the display on embed page otherwise all is the same a before.

[Test](https://mf-geoadmin3.dev.bgdi.ch/teo_logo/index.html?lang=fr&topic=luftbilder&bgLayer=ch.swisstopo.pixelkarte-grau&X=190000.00&Y=660000.00&zoom=1&mobile=false&layers=ch.swisstopo.lubis-luftbilder_schwarzweiss,ch.swisstopo.lubis-luftbilder_farbe&layers_timestamp=20101231,20101231&catalogNodes=1179,1180,1186&time=2010)

### CODE REVIEW

**Comment by oterral** [comment]
jenkins test

**Comment by oterral** [comment]
ok I've put back the css of embed because I was not sure it was CDBund compliant.

Can we merge this one @gjn ?

**Comment by oterral** [comment]
Wait there is seleniume tests to fix

**Comment by gjn** [comment]
Test fails: https://jenkins.ci.bgdi.ch/job/PR_geoadmin3/804/console

**Comment by oterral** [comment]
@gjn  tests succeed !!!

**Comment by oterral** [comment]
Thx!!!

**Pull request merged**
