### PR TITLE
[WIP] New proxy integration

### PR DESCRIPTION
**Pull request by loicgasser**
We need a final addresses.

[Test Link](https://mf-chsdi3.int.bgdi.ch/shorten/71dfa6b45c)

I'll document more tomorrow.
Happy testing :)

Works with https://github.com/geoadmin/mf-geoadmin3/pull/3731

### CODE REVIEW

**Comment by loicgasser** [comment]
Test Links for KMLs (No CORS):
https://mf-chsdi3.int.bgdi.ch/shorten/71e31582ec


WMS layers;
https://mf-chsdi3.int.bgdi.ch/shorten/71e3432f16


8.5Mb KML

https://i87vv9meee.execute-api.eu-west-1.amazonaws.com/int/http/www.nabodat.ch%2Fimages%2Fdocs%2Fkml%2FBOKA_1_5000.kml

**Comment by procrastinatio** [comment]
11 MB KML

https://i87vv9meee.execute-api.eu-west-1.amazonaws.com/int/https/www.procrastinatio.org/kml/simple_000005.kml

**Comment by loicgasser** [comment]
magic

**Comment by gjn** [comment]
1. Add proxy.geo.admin.ch as official adress (technical service-proxy) (mom)
2. Big three need to validate it and give ok (jeg)
3. Adapt help (jeg)
4. Inform api list of size change (jep)
5. Rename github project to service-proxy (gal)
6. Create dedicated VPC for aws Lambda with aws-admin account (mom)
7. Test all WMS with testlink (gal, gar, gas)

Go-live once the points are done and the big 3 have given their ok.

**Comment by loicgasser** [comment]
5. done in https://github.com/geoadmin/service-proxy/pull/11

**Comment by loicgasser** [comment]
Ok we now have the right addresses and we can test.

**Comment by gjn** [comment]
+1. thanks alot. Will try to get them to test this. My first tests look good.

**Comment by gjn** [comment]
Is this passing via cloudfront?

`x-cache:Miss from cloudfront` in response header of the proxy request.

**Comment by loicgasser** [comment]
Yes we have cloudfront per default.

**Comment by procrastinatio** [comment]
Yes, custom domain names implies Cf. But a hidden one, no config possible

**Comment by procrastinatio** [comment]
- [ ] Restriction/throtling ?

**Comment by procrastinatio** [comment]
! Custom headers and *$http.get* makes a *pre-flight* *OPTIONS* request...

**Comment by procrastinatio** [comment]
See https://jira.swisstopo.ch/browse/BGDIINF_SB-423

**Pull request merged**
