### PR TITLE
Fix getPrice requests

### PR DESCRIPTION
**Pull request by loicgasser**
Is indended to work with https://github.com/geoadmin/mf-chsdi3/pull/2326

[Test Link](https://mf-geoadmin3.int.bgdi.ch/gal_shop_fix/index.html?api_url=%2F%2Fmf-chsdi3.dev.bgdi.ch%2Fltgal&lang=fr&topic=swisstopo&bgLayer=ch.swisstopo.pixelkarte-farbe&X=172129.82&Y=648484.14&zoom=2&layers=ch.swisstopo.geologie-geocover,ch.swisstopo.geologie-geocover.metadata&layers_opacity=0.75,0.3&catalogNodes=1430)

### CODE REVIEW

**Comment by loicgasser** [comment]
@oterral quick review please? It's needed by @pfanguin

**Comment by oterral** [comment]
can you add a test for these exceptions pls?

**Comment by loicgasser** [comment]
sure.

**Comment by pfanguin** [comment]
I tested all shop layers and it's look, thanks a lot.

**Comment by loicgasser** [comment]
done

**Comment by oterral** [comment]
perfect thanks!!!

**Pull request merged**
