### PR TITLE
Changing backend for service feedback

### PR DESCRIPTION
**Pull request by procrastinatio**
See https://jira.swisstopo.ch/browse/BGDIINF_SB-2043

Test link: https://mf-geoadmin3.dev.bgdi.ch/BGDIINF_SB-2043_service_feedback/2111121108/index.html

:bomb: Do not merge until service-feedback is migrated and on production

### CODE REVIEW

**Review by hansmannj — APPROVED** [review]
Nice, thanks :+1:

**Review by IsabelleBzr — APPROVED** [review]
:+1:  Thanks

**Comment by hansmannj** [comment]
@procrastinatio: `service-feedback` is now deployed on DEV, INT and PROD.
If the changes from this PR still work as expected for all stagings, you could merge this PR :slightly_smiling_face:

**Comment by procrastinatio** [comment]
Test it with the prod `service-feedback`:
https://mf-geoadmin3.dev.bgdi.ch/BGDIINF_SB-2043_service_feedback/2111121108/index.html?feedback_url=//sys-map.prod.bgdi.ch

**Comment by hansmannj** [comment]
> @hansmannj Test it with the prod `service-feedback`: https://mf-geoadmin3.dev.bgdi.ch/BGDIINF_SB-2043_service_feedback/2111121108/index.html?feedback_url=//sys-map.prod.bgdi.ch

@procrastinatio Just tested all three stagings. Everything seems to work fine, thanks very much!
So ready to merge, I'd say :tada:

**Pull request merged**
