### PR TITLE
Search suggestions design

### PR DESCRIPTION
**Pull request by kandre**
[Test link](https://mf-geoadmin3.dev.bgdi.ch/kan_search_suggestions_design)

### CODE REVIEW

**Comment by kandre** [comment]
jenkins test

**Comment by loicgasser** [comment]
test libk doesn t work for me but i like the idea.

**Comment by oterral** [comment]
I've a question probably not related to this PR. Why when I type 'Bern' not all the 'bern' value in results are highlighted?

**Comment by gjn** [comment]
That's a regression and should not happen. I'll open an issue.

**Comment by kandre** [comment]
jenkins test

**Comment by kandre** [comment]
New commits, as discussed during the meeting:

- for categories labels: no uppercase, bigger font, keep left alignement
- make placeholder loop more visible

**Comment by kandre** [comment]
As discussed during the meeting:

- for categories labels: no uppercase, bigger font, keep left alignement
- make placeholder loop more visible

**Comment by cedricmoullet** [comment]
Ok for me. @davidoesch ?

**Comment by davidoesch** [comment]
ok

**Comment by kandre** [comment]
jenkins test

**Comment by kandre** [comment]
squashed

**Comment by kandre** [comment]
jenkins test

**Comment by kandre** [comment]
jenkins test

**Pull request merged**
