### PR TITLE
Update librairies

### LINKED ISSUE #3773: import: scrolling in wms pulldown
import interface : try to scroll in wms pulldown (mouse or keyboard)
-> it always goes automatically to the end of the list

### PR DESCRIPTION
**Pull request by oterral**
Fix #3773

[Test](https://mf-geoadmin3.int.bgdi.ch/teo_up_libs/index.html?lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,&X=199964.47&Y=650035.53&zoom=1)

### CODE REVIEW

**Comment by gjn** [comment]
Thanks alot for this. I will test on my side. Together with the ol3 update, I think this merits a concerted effort.

**Comment by oterral** [comment]
Rebase on master woth ol update

**Comment by loicgasser** [comment]
For angular updates:
https://github.com/angular/angular.js/blob/master/CHANGELOG.md

**Comment by oterral** [comment]
can we merge this ?

**Pull request merged**
