### PR TITLE
Use marker as default crosshair

### PR DESCRIPTION
**Pull request by cedricmoullet**

### CODE REVIEW

**Comment by cedricmoullet** [comment]
@davidoesch do you agree ?
@pauloamado could you adapt the help ? http://help.geo.admin.ch/?id=54&lang=de marker is also one option of the crosshair parameter

**Comment by davidoesch** [comment]
Do u Mean by marker: the one used for the search result preview on map? If yes ok.

In this case we have to adapt the help screenshot

**Comment by cedricmoullet** [comment]
@davidoesch yes !
@pauloamado sorry, but the screenshot has also to be adapted.

**Comment by pauloamado** [comment]
http://help.geo.admin.ch/?id=54&lang=de is now adapted. Currently no screenshots are concerned in help.geo.admin.ch. Should we add something in http://help.geo.admin.ch/?id=12&lang=de (link with "marker" crosshair)?

**Pull request merged**
