### PR TITLE
[WIP] Add mobile tests to browserstack testing

### PR DESCRIPTION
**Pull request by ponceta**
See #2115 for details

WIP do not merge

### CODE REVIEW

**Comment by ponceta** [comment]
Still not stable, especially for iPad... Search fails often.

**Comment by ponceta** [comment]
@gjn what do you think of this?

This actually works, takes a bit of time, but it could be great to assess a bit it's stability running with jenkins for example during a week and see then if we go into more complexity or if we avoid e2e emulated mobile testing.

**Comment by gjn** [comment]
I like to have them separated, but maybe we can still keep the general framework? But the tests and caps in desktop/mobile collections and run each once?

**Comment by ponceta** [comment]
Yes, that's exactly what I was meaning with "running with jenkins"

**Comment by gjn** [comment]
The code is separated here and contains thus duplicated definitions (mobile_browsers.js/browser.js and mobilel_tests.js/tests.js share alot of same code) I'm not a fan of that.

We could separate the mobile tests from desktop tests by having
a) mobile and desktop capabilities
b) mobile and desktop tests.
in a simple collection.

That's what I meant by collections. Something like
'''
var capabilities = {
   mobile: [...],
   desktop: [...]
}

var testsToRun = {
   mobile: [....],
   desktop: [....]
}
'''

The rest of the framework won't need much adaption and we would avoid duplication of code. It would also allow to run same tests on mobile and desktop in future (can be a possibility).

**Comment by ponceta** [comment]
Like a "-m" for mobile tests, I'm pretty fan of this. I'm convinced this is a good idea. 

But if mobile tests are not stable enough this will only be code corruption.

Shouldn't we test it for a week and see if it is stable enough and adapt it as "definitive code" afterwards? As it is for know, it has no influence at all on the existing code and can be removed easily.

**Comment by gjn** [comment]
For testing a week, you can setup a new jenkins projects, make it dependant on existing geoadmin3 project, checkout this branch and run the mobile tests

**Comment by ponceta** [comment]
This is tested on jenkins for a week or two to assess its stability

**Comment by ponceta** [comment]
jenkins test

**Comment by ponceta** [comment]
I merged both mobile and desktop together.

Mobile tests are quite stable at night which is great for our night runs but are less stable on day (when there's more trafic)

I'll adapt the jenkins temp test for this new version.

IMO it could be great to select with a -m if we want mobile testing and ommiting it if we don't!

@gjn what do you think?

**Comment by ponceta** [comment]
jenkins test

**Comment by ponceta** [comment]
jenkins test

**Comment by ponceta** [comment]
jenkins test

**Pull request closed without merging**
