### PR TITLE
[WIP] Add a zoom minimun distance

### PR DESCRIPTION
**Pull request by oterral**
[Test](https://mf-geoadmin3.dev.bgdi.ch/teo_dist/?lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&dev3d=true&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege,ch.swisstopo.swissimage-product&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,&lon=7.81240&lat=46.19732&elevation=1799&heading=190.484&pitch=-40.918)

### CODE REVIEW

**Comment by cedricmoullet** [comment]
+1 It makes the navigation more easy ! @davidoesch

**Comment by davidoesch** [comment]
looks good, but might be not close enough if we have buildings for urabn areas eg https://mf-geoadmin3.dev.bgdi.ch/teo_dist/?lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&dev3d=true&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege,ch.swisstopo.swissimage-product&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,&lon=7.44260&lat=46.94510&elevation=1057&heading=57.227&pitch=-44.318

but for now: it is ok

**Comment by davidoesch** [comment]
actually the high precision of the data is hereby not clear to the user - you don't see the fitting of the roads /hiking etc anymore...

**Comment by cedricmoullet** [comment]
Maybe a smaller value ?

2015-10-09 17:17 GMT+02:00 davidoesch <notifications@github.com>:

> actually the high precision of the data is hereby not clear to the user -
> you don't see the fitting of the roads /hiking etc anymore...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/pull/2756#issuecomment-146900726>
> .
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>

**Comment by davidoesch** [comment]
IMHo it is already the same as in veloland. What google does: on urban areas you have different zoom distance than in the mountains.
maybe : if 3d Data is availble a closer zooming is possible:

but with KISS: @oterral have you a version with half of the zoom distance?

**Pull request merged**
