### PR TITLE
Fix link to obejct functionality

### PR DESCRIPTION
**Pull request by gjn**
This fixes the link-to-object permalink functionality. Introduced by the mapservice refactoring.

@oterral Do you remember why you switched from loadConfig() promise to the gaLayersChange event?

### CODE REVIEW

**Comment by gjn** [comment]
[Testlink](https://mf-geoadmin3.dev.bgdi.ch/gjn_linktoobject?ch.bfs.gebaeude_wohnungs_register=286047_0&lang=de&topic=ech) pint @cedricmoullet @davidoesch

**Comment by oterral** [comment]
Not wanted. Probably a rebase of the "Split map service" branch failure. 
But I'm worried now, it seems it's an old version of the service. See #https://github.com/geoadmin/mf-geoadmin3/pull/3179/files . I hope it's not the case for all the service I've split.

**Comment by cedricmoullet** [comment]
Seems to work. But when I open another building, then the link points not
on the branch but on the main env.

2016-03-16 14:16 GMT+01:00 oterral <notifications@github.com>:

> Not wanted. Probably a rebase of the "Split map service" branch failure.
> But I'm worried now, it seems it's an old version of the service. See #
> https://github.com/geoadmin/mf-geoadmin3/pull/3179/files . I hope it's
> not the case for all the service I've split.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/pull/3215#issuecomment-197323295>
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>

**Comment by loicgasser** [comment]
Link to object in not user dependent.

**Comment by gjn** [comment]
@oterral `gaLayersChange` is nowhere else.

**Comment by oterral** [comment]
@gjn  all the gaPermalinkFeaturesManager service is not up to date

I ve also seen that a gaLayersHideManager service is defined in 2 services, you can remove the 2. This service has been renamed gaOpaqueLayers

See https://github.com/geoadmin/mf-geoadmin3/search?utf8=%E2%9C%93&q=gaLayerHideManager&type=Code

**Comment by gjn** [comment]
@oterral are there others that have been renamed? Just to be sure.

**Comment by gjn** [comment]
gaPermalinkFeaturesManager changed considerably. Here's the diff: https://gist.github.com/gjn/2c7a0c15c3bc0d78d252

**Comment by gjn** [comment]
@loicgasser ok, I'll merge.

**Comment by oterral** [comment]
@gjn These 3 have been renamed:
gaLayersHideManager to gaOpaqueLayersmanager
gaFeaturesPermalinkManager to  gaPermalinkFeaturesManager
gaLayersPermalinkManager to  gaPermalinkLayersManager

**Comment by davidoesch** [comment]
tested on win10 latestff chrome ie11

**Pull request merged**
