### PR TITLE
Do not trigger a request if query is an empty str

### PR DESCRIPTION
**Pull request by loicgasser**
Fix for https://github.com/geoadmin/mf-geoadmin3/issues/3350

ping @gjn 

newval used to refer to the whole url which was actually never equal to an empty string...

[Test Link](https://mf-geoadmin3.dev.bgdi.ch/gal_emptystring/?lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege,ch.swisstopo.pixelkarte-farbe-pk25.noscale,ch.swisstopo.lk25-papierkarte.metadata&layers_visibility=false,false,false,false,true,true&layers_timestamp=18641231,,,,,&X=159577.00&Y=535422.62&zoom=7)

### CODE REVIEW

**Comment by gjn** [comment]
Yes, introduced by search tokens PR a couple of weeks ago. 

Changed to watch searchURL, because otherwise a change to a token string (from `limit: 1` to `limit: 10`) would not trigger a new search as the query variable does _ not_ contain the tokens. So this problem re-appears with this PR. I try to come up with something covering both cases.

**Comment by loicgasser** [comment]
Then keep the watcher on the URL and test that $scope.options.query != ''

**Comment by gjn** [comment]
+1
Am 01.06.2016 8:04 nachm. schrieb Gasser Loïc <notifications@github.com>:Then keep the watcher on the URL and test that $scope.options.query != ''

**Comment by loicgasser** [comment]
That s what I came up with initially

**Comment by cedricmoullet** [comment]
The regression is fixed.
But, when I put 1290, for example, in the search field and then click on
the item, then the result list stay. Maybe another regression.

2016-06-01 20:08 GMT+02:00 Gasser Loïc <notifications@github.com>:

> That s what I came up with initially
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/pull/3351#issuecomment-223077427>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AATgvILnZqOKH9zLcC6dvHJjnmOUHUwtks5qHcq3gaJpZM4IrvQ9>
> .
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>

**Comment by gjn** [comment]
Yes, can reproduce, but only for feature search results in combination with the shop layer in the testling. Adding lubis layerl searching for 2000 an selecting feature does close the search results.
Fascinating.

**Comment by loicgasser** [comment]
yes tested on prod. Seems to behave the same way. not directly related to this issue.

**Comment by gjn** [comment]
Might be related to tooltip popping up (different for shop layers as for other layers). Smells digest cycle / timing issue to me.
Am 01.06.2016 8:45 nachm. schrieb Gasser Loïc <notifications@github.com>:yes tested on prod. Seems to behave the same way. not directly related to this issue.

**Comment by loicgasser** [comment]
It happens if when you have one feature result only.

**Comment by loicgasser** [comment]
The situation is as follow:

When we click a result we always execute a `select` according to the search type.
In each select we change the global search scope using `$scope.options.valueSelected` together with `cleanLabel`.
See for instance:
https://github.com/geoadmin/mf-geoadmin3/blob/master/src/components/search/SearchTypesDirectives.js#L463

`$scope.options.valueSelected` then assigns the new cleaned result to `$scope.query` which value is watched and will trigger `startQuery` if the new value is different from the old one.
https://github.com/geoadmin/mf-geoadmin3/blob/master/src/components/search/SearchDirective.js#L87ed

But when we type `1208` the cleaned label string and the query string are exactly the same so that `startQuery` is never executed and as a result `reset` method of ResultStats is never called.
https://github.com/geoadmin/mf-geoadmin3/blob/master/src/components/search/SearchDirective.js#L136

An easy fix is to ensure that `reset` is called when a value is selected which is what I did.
It works as expected now and it doesn't seem to have any side effect.

**Comment by loicgasser** [comment]
jenkins test

**Comment by loicgasser** [comment]
ok now not that easy swissearch parameter fails. with an address now.

**Comment by gjn** [comment]
Thanks for the explanation. Fix looks good to me.

Didn't understand last comment: swisssearch fails now?

**Comment by loicgasser** [comment]
No it's fine now. I adapted the PR.

**Comment by loicgasser** [comment]
selenium tests ;) finally useful

**Comment by gjn** [comment]
Yes. Long live selenium. Safed us already a few times - mostly for swissearch tests.

Thanks alot for this.

**Pull request merged**
