### PR TITLE
Optimize images

### PR DESCRIPTION
**Pull request by loicgasser**
https://github.com/geoadmin/mf-geoadmin3/issues/3902

### CODE REVIEW

**Comment by gjn** [comment]
How much do we gain?

**Comment by loicgasser** [comment]
All images were optimized but these 3. Not much in loading page time I think.

**Comment by oterral** [comment]
thx

**Comment by gjn** [comment]
How much gained in size? Just curious.

**Comment by loicgasser** [comment]
15, 20, 1% respectively.

**Pull request merged**
