### PR TITLE
add av-wms ita

### PR DESCRIPTION
**Pull request by dkottmann**
@davidoesch

### CODE REVIEW

**Comment by pakb** [comment]
It works, but your WMS can't handle when geoadmin asks for what the headers are with a `HTTP HEAD` request. It respond with HTTP 500 (Internal server error) when requested.
Could it be possible to fix that on your WMS?

**Comment by pakb** [comment]
Request
```
:authority: geodienste.ch
:method: HEAD
:path: /db/av/ita?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.3.0
:scheme: https
accept: application/json, text/plain, */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9,fr;q=0.8
cache-control: no-cache
dnt: 1
origin: https://mf-geoadmin3.int.bgdi.ch
pragma: no-cache
referer: https://mf-geoadmin3.int.bgdi.ch/ltbtp_test_pr_5203/2009041252/index.html?lang=en&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege&layers_opacity=1,1,1,0.8&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: cross-site
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
```
Response
```
access-control-allow-methods: *
age: 0
content-length: 1635
content-type: text/html; charset=UTF-8
date: Fri, 04 Sep 2020 10:57:22 GMT
server: nginx/1.14.0 (Ubuntu)
status: 500
status: 500 Internal Server Error
via: 1.1 varnish (Varnish/5.2)
x-powered-by: Phusion Passenger 5.3.4
x-request-id: 7b2732fe-c19c-456f-9fb9-876a50b05509
x-runtime: 0.016637
x-varnish: 6229939
```

**Comment by dkottmann** [comment]
@pakb (cc: @davidoesch )

thanks for the info. we'll have a look at this issue and willl make HEAD requests work.

**Comment by dkottmann** [comment]
@pakb (cc: @davidoesch )

HTTP HEAD requests work now on our test system with: 

https://dev.geodienste.ch/db/kataster_belasteter_standorte_v1_4_0/deu?SERVICE=WMS&REQUEST=GetCapabilities

```
curl -I "https://dev.geodienste.ch/db/kataster_belasteter_standorte_v1_4_0/deu?SERVICE=WMS&REQUEST=GetCapabilities"
HTTP/1.1 200 OK
Server: nginx/1.14.0 (Ubuntu)
Date: Fri, 04 Sep 2020 12:59:04 GMT
Content-Type: text/html
Connection: keep-alive
Cache-Control: private
Referrer-Policy: strict-origin-when-cross-origin
X-Permitted-Cross-Domain-Policies: none
X-XSS-Protection: 1; mode=block
X-Request-Id: 417f3cb2-52ef-4ae1-9950-564b0f46494e
Content-Disposition: inline
X-Download-Options: noopen
Content-Transfer-Encoding: binary
X-Runtime: 0.011833
X-Content-Type-Options: nosniff
X-Powered-By: Phusion Passenger 5.3.4
Status: 200 OK
Access-Control-Allow-Origin: *
X-Varnish: 622627
Age: 0
Via: 1.1 varnish (Varnish/5.2)
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Authorization,Accept,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range, X-CSRF-Token
Access-Control-Allow-Methods: GET,POST,OPTIONS,PUT,DELETE,PATCH
```

could you verify this?

**Comment by pakb** [comment]
Works well on your `dev` environment!

**Comment by pakb** [comment]
@dkottmann has this change been carried to your int and prod environnement?

**Pull request merged**
