### PR TITLE
Link 2d and 3d kml features with an id

### PR DESCRIPTION
**Pull request by oterral**
Now you can select on KML feature in 3d and see the tootip.

In this PR , the height service has been moved to his own service, that's explain the amount of changes.

[Test with the attached kml](//mf-geoadmin3.int.bgdi.ch/teo_tp3d/index.html)
[1414routing.txt](https://github.com/geoadmin/mf-geoadmin3/files/1513120/1414routing.txt)

### CODE REVIEW

**Comment by davidoesch** [comment]
Does not work with https://gist.githubusercontent.com/davidoesch/db110c79e3ff5e89c303105c6534c86c/raw/6c14ef5a318d3b54eb7490aa40e1f63063f6e638/ad4.tsv

(related maybe to the 0 height in kml?)

**Comment by oterral** [comment]
Yes it works in src mode but not in prd.

**Comment by oterral** [comment]
@davidoesch can you retest pls? it works for me.

**Comment by davidoesch** [comment]
EDGE win10 I get  for
https://mf-geoadmin3.int.bgdi.ch/teo_tp3d/index.html?lang=en&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege,KML%7C%7Chttps:%2F%2Fgithub.com%2Fgeoadmin%2Fmf-geoadmin3%2Ffiles%2F1513120%2F1414routing.txt,ch.swisstopo.swissnames3d&layers_visibility=false,false,false,false,true,true&layers_timestamp=18641231,,,,,&lon=9.07229&lat=47.15320&elevation=1963&heading=34.096&pitch=-15.077

and https://gist.githubusercontent.com/davidoesch/db110c79e3ff5e89c303105c6534c86c/raw/6c14ef5a318d3b54eb7490aa40e1f63063f6e638/ad4.tsv

image

**Comment by oterral** [comment]
Seems Ceisum bugs : 
https://github.com/AnalyticalGraphicsInc/cesium/issues/2860
https://github.com/AnalyticalGraphicsInc/cesium/issues/5700

**Comment by oterral** [comment]
I'm gonna revert cesium to the last version otherwise we can't display any vector on edge

**Comment by oterral** [comment]
@davidoesch it works now on edge

**Comment by davidoesch** [comment]
Ok... Let's wait for the fix in cesium. Edge compatibility has higher prio

**Pull request merged**
