### PR TITLE
Fixed popup width when dragged to window's boundaries

### PR DESCRIPTION
**Pull request by kandre**

### CODE REVIEW

**Comment by gjn** [comment]
Can't build it (make all fails)

**Comment by kandre** [comment]
I learnt from @oterral that we dont want popups which are resizable, therefore I go in that direction, for both right and left sides

**Comment by kandre** [comment]
This is an attempt to fix #2286 with those requirements:

- popups width is fixed even if: 
  - popup is dragged outside window's boundaries by dragging
  - window is resized from both right or left
- popup still fit the screen on small screens (e.g mobiles, resized windows)

Code is not cleaned hence not ready for merge

**Comment by oterral** [comment]
Test link please

**Comment by cedricmoullet** [comment]
@kandre what is the status of this PR ?

**Comment by kandre** [comment]
[Testlink](https://mf-geoadmin3.dev.bgdi.ch/kan_popups_width_on_borders)

**Comment by kandre** [comment]
It works, I am currently refactoring a bit the code and I then will remove the wip label

**Comment by kandre** [comment]
I cleaned a bit the code (last commit). However, I still not very satisfied that I stuck in getting rid off this + 4px value (this is actually the difference between the popup container and its child)

**Comment by oterral** [comment]
Ready to revioew/test [Testlink](https://mf-geoadmin3.dev.bgdi.ch/kan_popups_width_on_borders)

**Pull request merged**
