### PR TITLE
Update map libs

### PR DESCRIPTION
**Pull request by oterral**
[Test](https://mf-geoadmin3.int.bgdi.ch/teo_up/?lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&X=190000.00&Y=660000.00&zoom=1&dev3d=true&debug&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,)

### CODE REVIEW

**Comment by oterral** [comment]
Tested on ie9 and chrome . no sign of regression

**Comment by oterral** [comment]
Next deploy is in 2 weeks could be great to have it in master now.

**Comment by loicgasser** [comment]
+1

**Comment by loicgasser** [comment]
Tested on mobile chrome

**Comment by gjn** [comment]
I'll test on FF and IE11 today. If good, I'll merge it.

**Comment by gjn** [comment]
I've tested most. But didn't test offline mode.

Did someone test offline? If yes, please merge it.

ping @oterral

**Comment by oterral** [comment]
Offline tested on iPhone safari

**Pull request merged**
