### PR TITLE
More robust variable def

### PR DESCRIPTION
**Pull request by loicgasser**
When deploying if you source another file before hand, you're in trouble.
With this PR we are explicit.

### CODE REVIEW

**Comment by procrastinatio** [comment]
Yes, some varaibles are defined in source files, while other default are in the `Makefile`. We may also `unset` all variables we use ?

**Comment by loicgasser** [comment]
All are defined in source files. We can't use unset or we will loose the options we use to parameter our scripts. We could remove the ones in the makefile now. But better safe than sorry.

**Comment by oterral** [comment]
To be consstent with orthers urls I've added the `.build-artefacts/last-print-url` target.

**Comment by oterral** [comment]
THx for this @loicgasser

**Pull request merged**
