### PR TITLE
Fix part of #3693: The no info popup is no longer displayed if a vect…

### LINKED ISSUE #3693: External KML Icons are bigger since deploy 20170126
open

http://www.skitourenguru.ch/index.php/routeview?AREA=Switzerland&ID=673&RISKIND=0.28&SERVER=http://www.skitourenguru.ch/calc_data

image

Result Feedback customer
"
Mit dem KML-Attribute “IconStyle\scale” ist es möglich, die Grösse eines Icons festzulegen. Seit heute ist das Scaling auf geo.admin.ch um ca. einen Faktor 4 verändert. D.h. alle Icons auf Skitourenguru sind 4 mal kleiner. Ich kann zwar bei mir ohne weiteres die Werte neu anpassen, aber ich befürchte, dass sich das Scaling auf geo.admin.ch erneut verändern wird.
Bereits zwischen dem 8.11 und 11.11.2015 war das Scaling 3 Tage lang um einen Faktor 2-3 anders. Was ist wohl geschehen?
"

Own observation in 3D

image

-> they seem here quite small

### PR DESCRIPTION
**Pull request by oterral**
…or feature is selected

[Before](https://map.geo.admin.ch/index.html?X=211791.12&Y=705905.01&zoom=8.949734757417549&lang=de&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers_opacity=0.3,0.3,0.3,0.5,1,1&layers=ch.bafu.wrz-jagdbanngebiete_select,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.hangneigung-ueber_30,ch.swisstopo-karto.skitouren,ch.bav.haltestellen-oev,KML%7C%7Chttp:%2F%2Fwww.skitourenguru.ch%2Fcalc_data%2Fkml%2FSwitzerland_RiskSymbol079.kml&layers_visibility=false,true,true,true,false,true)

[After](https://mf-geoadmin3.int.bgdi.ch/teo_tooltip/index.html?X=211791.12&Y=705905.01&zoom=8.949734757417549&lang=de&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers_opacity=0.3,0.3,0.3,0.5,1,1&layers=ch.bafu.wrz-jagdbanngebiete_select,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.hangneigung-ueber_30,ch.swisstopo-karto.skitouren,ch.bav.haltestellen-oev,KML%7C%7Chttp:%2F%2Fwww.skitourenguru.ch%2Fcalc_data%2Fkml%2FSwitzerland_RiskSymbol079.kml&layers_visibility=false,true,true,true,false,true)

How to:

  1) Click on the icon
  2) The tootlip shouldn't be close after 5 secs

Fix #3693

### CODE REVIEW

**Comment by smug007** [comment]
Just tested with the following on the following link:
http://www.skitourenguru.ch/index.php/routeview?AREA=Switzerland&ID=263&RISKIND=1.89&SERVER=http://www.skitourenguru.ch/calc_data

 -WebCams: Isseu got fixed (Object Info Window remains)
- Cofins, Triangles, Lines and Polygons: Object Info Window still disappear after 5 secs

Its the same on all browsers: Firefox, IE, Opera and Chrome

**Comment by oterral** [comment]
I mean, test with the 2 links(before, after) I provided in the description of this Pull Request.

**Comment by smug007** [comment]
Tested with Firefox:
- Before: Object Info disappears after 5 secs
- After: Object Info remains there.

**Comment by oterral** [comment]
perfect, the fix should be available next thursday on production.

**Pull request merged**
