### PR TITLE
New menu

### LINKED ISSUE #2416: Redesign hamburger menu on smartphones
Redesign according to usability spec

### PR DESCRIPTION
**Pull request by oterral**
[Test](https://mf-geoadmin3.dev.bgdi.ch/teo_menu/?lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&X=190000.00&Y=660000.00&dev3d=true&zoom=1&debug)

Fix #2416

### CODE REVIEW

**Comment by loicgasser** [comment]
c'est la grande classe ce nouveau menu.
Works like a charm on samsung s4 and chrome.
Good stuff!

**Comment by cedricmoullet** [comment]
I have lost the offline button on my iPhone 6.... but works fine on chrome.
image

**Comment by cedricmoullet** [comment]
Menu is very good.

**Comment by loicgasser** [comment]
For future work maybe, each section is now scrollable but the entire menu is not (as before).
What about making the entire menu scrollable?

**Comment by oterral** [comment]
I agree with @loicgasser but the problem is the catalog he can be too big. may be we should reordering the sectons first,  putting  the catalog at the bottom.

**Comment by gjn** [comment]
+1 for scrolling of complete menu.

**Comment by oterral** [comment]
@cedricmoullet it's àn ios 9 position:fixed` bug

**Comment by davidoesch** [comment]
perfect

**Comment by oterral** [comment]
Bug fixed can you confirm @cedricmoullet

**Comment by cedricmoullet** [comment]
nice !

**Comment by gjn** [comment]
I think we need to add translations for `menu`.

**Comment by oterral** [comment]
Translations added

**Comment by gjn** [comment]
Should start with capital letter, no? (The reverse, Fermer, does).

**Comment by oterral** [comment]
@davidoesch wanted only small letters, if I remember correctly.

**Comment by gjn** [comment]
This would be the only place in the whole application...

**Comment by loicgasser** [comment]
This also fixes the issue where the offline button appears in 3d.

**Comment by oterral** [comment]
I've capitalized the first letter

**Comment by gjn** [comment]
+1. I'll merge once jenkins is happy.

**Comment by davidoesch** [comment]
Sorry Capital letzter eveywhere

**Comment by gjn** [comment]
jenkins test

**Pull request merged**
