### PR TITLE
Add resizable popups

### PR DESCRIPTION
**Pull request by ponceta**
Add the possibility to the user to resize the popups (not supported on IE)

Enhancement proposal #1401

[Testlink](http://mf-geoadmin3.dev.bgdi.ch/ltpoa/)

### CODE REVIEW

**Comment by ponceta** [comment]
jenkins test

**Comment by gjn** [comment]
What is the change?

**Comment by loicgasser** [comment]
Intresting I didn't know this css property. http://www.w3schools.com/cssref/css3_pr_resize.asp

Not supported on IE and you might need the -moz suffix for Firefox.

**Comment by oterral** [comment]
I've already tried this solution once and  it's really not perfect because sometimes the content of the popup doesn't fit correctly the new size of the popup. To be sure, we should verify each popup content on each browser and fix it if the display is not correct, obviously that can lead to unwanted css bugs.

**Pull request closed without merging**
