### PR TITLE
Fog

### PR DESCRIPTION
**Pull request by gberaudo**
Optional, need a parameter for activation
Test URLS: [0.0001/25, best](https://mf-geoadmin3.dev.bgdi.ch/tmp_fog/?dev3d=true&lang=en&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,&lon=7.61432&lat=46.82189&elevation=17481&heading=305.787&pitch=-24.337&fogEnabled=true&fogDensity=0.0001&fogSseFactor=25&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege,ch.swisstopo.swissimage-product), [0.0002/2](https://mf-geoadmin3.dev.bgdi.ch/tmp_fog/?dev3d=true&lang=en&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,&lon=7.61432&lat=46.82189&elevation=17481&heading=305.787&pitch=-24.337&fogEnabled=true&fogDensity=0.0002&fogSseFactor=2&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege,ch.swisstopo.swissimage-product), [0.0004/5](https://mf-geoadmin3.dev.bgdi.ch/tmp_fog/?dev3d=true&lang=en&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,&lon=7.61432&lat=46.82189&elevation=17481&heading=305.787&pitch=-24.337&fogEnabled=true&fogDensity=0.0002&fogSseFactor=2&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege,ch.swisstopo.swissimage-product)

Parameters:
- `fogEnabled`, boolean, default true, enable fog;
- `fogDensity`, float, default 0.0001, change density;
- `fogSseFactor`, float, default 25, change error correction.

These values are empirical.
The fogDensity has an effect both on the visualizazion and the loading
error. The fogSseFactor only has an effect on the loading error.

### CODE REVIEW

**Comment by fredj** [comment]
+1 !

**Comment by gberaudo** [comment]
@gjn, can we merge?

**Comment by oterral** [comment]
Wait I ask @procrastinatio he's deploying today .

**Comment by davidoesch** [comment]
realy really nice..even if it is quite aggressive

**Comment by gberaudo** [comment]
Thanks @oterral, waiting for the `go`.

**Comment by gjn** [comment]
I like it. Great work.

I'll do the benchmarks

**Comment by gjn** [comment]
Benchmarks done. Panoramic view profits really big, decrease of data transfered is 67% (2/3 less than reference case).

**Comment by davidoesch** [comment]
@gjn: can you adapt as well the estimated additional on s3 we will need
(gretchenfrage)...

**Pull request merged**
