### PR TITLE
Update coordinate of brückenmoostrasse 11 raron

### PR DESCRIPTION
**Pull request by alcapat**

### CODE REVIEW

**Comment by gjn** [comment]
hmm. still not good? @alcapat

**Comment by gjn** [comment]
jenkins test

**Comment by gjn** [comment]
@davidoesch @cedricmoullet FYI, the swissearch data was updated. According to @ltclm 

I did a manual update this morning of the address data.
They wanted us to change the source of the geometry. The new geometry source is the building entrance and not the building center anymore.
The new data is deployed to dev and will be deployed automatically this weekend to int and prod.

**Comment by davidoesch** [comment]
woah this quite a change @ltclm --- finally they agreed. it does not seem to work everywhere. what is th fallback? switch to center as here? https://s.geo.admin.ch/6aaba9a349

**Comment by ltclm** [comment]
yes it is great, you can compare the old and the new position with this url:
https://s.geo.admin.ch/6aabe637e8

**Pull request merged**
