### PR TITLE
Share shorten url

### PR DESCRIPTION
**Pull request by loicgasser**
Fix for https://github.com/geoadmin/mf-geoadmin3/issues/3356

@davidoesch [Test Link](https://mf-geoadmin3.dev.bgdi.ch/gal_share_link/)

### CODE REVIEW

**Comment by gjn** [comment]
Not a fan for it  Doesn't facebook, twitter, etc shorten it already? so clicking the link will just result in an additional redirection.

For mail it might make sense - but then, a long link might educate people on how map.geo can be configured.

**Comment by davidoesch** [comment]
+1 only for mail (whereas if we shorten it already for the others--no issue with that)

Mail: in communication the long link IS bad.... feedback from schulung today

**Comment by loicgasser** [comment]
no none of the urls shared were short ulrs even for qrcode.

See for instance current generated facebook link (Hard to read anyway):
https://www.facebook.com/sharer.php?u=https://mf-chsdi3.dev.bgdi.ch/shorten/6c3d3b8423&t=Maps%20of%20Switzerland%20-%20Swiss%20Confederation%20%20-%20map.geo.admin.chhttps://www.facebook.com/sharer.php?u=https://mf-chsdi3.dev.bgdi.ch/shorten/6c3d3b8423&t=Maps%20of%20Switzerland%20-%20Swiss%20Confederation%20%20-%20map.geo.admin.ch

I think we should only link short urls.

**Comment by loicgasser** [comment]
bad link in initial comment updated

**Comment by gjn** [comment]
For facebook/twitter/G+, the link is never actually shown in full length in the post, shows map.geo.admin.ch (PR...) and points to their respective shortened version.

With the shortend link, the post will show s.geo.admin.ch and will point to their respective shortened version, which points to our shortend version, which points to map.geo.admin.ch (an additional hoop).

Matter of taste, I guess...

**Comment by davidoesch** [comment]
Correct... My taste is add well: show long in social media but not in mail

Gilbert Jeiziner <notifications@github.com> schrieb am Do., 2. Juni 2016,
19:20:

**Comment by loicgasser** [comment]
ok shorten for qrcode and mail. social media with full url, even if I fail to understand why as as you pointed it out URLs are hidden...

**Comment by loicgasser** [comment]
Ok I left the full url for social medias.

**Comment by gjn** [comment]
+1

**Pull request merged**
