### PR TITLE
Change the third party data warning

### PR DESCRIPTION
**Pull request by oterral**
When a third party data (external WMS or KML) is added : 
- [x] the link on bottom right is displayed in red and on click the alert message appears
- [x]  a warning button appears in the layer manager and on click the alert message appears

[Testlink](http://mf-geoadmin3.dev.bgdi.ch/teo_warn/?lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&X=132978.94&Y=596068.36&zoom=2&layers=WMS%7C%7CAusstattung%20Fl%C3%A4chen%7C%7Chttp:%2F%2Fmapserver1.gr.ch%2Fwms%2Fgenerellererschliessungsplan%3F%7C%7CAusstattung_Flaechen,KML%7C%7Chttp:%2F%2Fwww.bikingspots.ch%2FcreateKMLFile.php%3Ffilename%3Dreno333508077c95ddec.xml%26fc%3D1)

Missing translation 

Works with https://github.com/geoadmin/mf-chsdi3/pull/1369

- [x] Options for displaying in layer selection : the Steering committee will decide on a logo an option https://docs.google.com/document/d/12TkfNdB-jZnXEiwJinscnk579L-vLGBEhJpLCTQFb_w/edit?usp=sharing  wait for feedback here by @davidoesch
- [x] alert message has also to contain the URL of the source of the external source in the message. will be done in the translation table

- [x] update translation

- [x] add warning as well in red in PDF export in
   - [x] Copyright: Domain external source is red
   - [x] Disclaimer: red warning text
unbenannt1

### CODE REVIEW

**Comment by oterral** [comment]
@davidoesch , @cedricmoullet  thoughts?

**Comment by procrastinatio** [comment]
Symbol is a bit too proeminent and let think there is a problem..

**Comment by davidoesch** [comment]
symbol size: should be the same size as the I icon,, but imho I like it 
besides that: perfect ( and hold on: not yet confirmed by the steering group)

**Comment by cedricmoullet** [comment]
Yes, please don't merge.
Looks very good. We have to change the text since the use has already loaded the file. We could add a tooltip when hovering the icon "Dataset not provided by geo.admin.ch".

**Comment by davidoesch** [comment]
+1 for cedric points. Did not find the text in translation table

**Comment by oterral** [comment]
@davidoesch it's the same as before third_party_data_warning

**Comment by ponceta** [comment]
jenkins test

**Comment by oterral** [comment]
@davidoesch @cedricmoullet  could you provide th text you want please in this is `external_data_warning`

**Comment by oterral** [comment]
For the size of the ison it's the same as others icons

**Comment by oterral** [comment]
@cedricmoullet tooltips added

Ready for review 


@cedricmoullet @davidoesch @AFoletti @mariokeusen :  

Translations needed with these ids : 
`external_data_warning` 
`external_data_tooltip`

**Comment by ponceta** [comment]
jenkins test

**Comment by davidoesch** [comment]
[  ] Options for displaying in layer selection : the Steering committee will decide on a logo an option https://docs.google.com/document/d/12TkfNdB-jZnXEiwJinscnk579L-vLGBEhJpLCTQFb_w/edit?usp=sharing wait for feedback here by @davidoesch
[  ] alert message has also to contain the URL of the source of the external source in the message. will be done in the translation table

**Comment by davidoesch** [comment]
Ambrogio

can you translate in the translation to FR IT:
external_data_warning
external_data_tooltip

**Comment by cedricmoullet** [comment]
............................

**Comment by ponceta** [comment]
@oterral could you rebase this? I could use this to add the last wms/kml tests using direct links.

**Comment by oterral** [comment]
yes

**Comment by ponceta** [comment]
ty

**Comment by oterral** [comment]
Rebased @ponceta

**Comment by ponceta** [comment]
jenkins test

**Comment by davidoesch** [comment]
Habeamus icon:

icon user with a white background
It is 
unbenannt

please use the corresponindg fontawesome

and very *important* deploy only if all of the above features (checkboxes) in the ticket description are resolved

**Comment by gjn** [comment]
@cedricmoullet @davidoesch This is ready for final tests: [Testlink](http://mf-geoadmin3.dev.bgdi.ch/teo_warn/?lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&X=132978.94&Y=596068.36&zoom=2&layers=WMS%7C%7CAusstattung%20Fl%C3%A4chen%7C%7Chttp:%2F%2Fmapserver1.gr.ch%2Fwms%2Fgenerellererschliessungsplan%3F%7C%7CAusstattung_Flaechen,KML%7C%7Chttp:%2F%2Fwww.bikingspots.ch%2FcreateKMLFile.php%3Ffilename%3Dreno333508077c95ddec.xml%26fc%3D1)

**Comment by cedricmoullet** [comment]
@davidoesch could you please adapt the text ?

**Comment by davidoesch** [comment]
@AFoletti 
can you adapt FR IT of
- external_data_warning

**Comment by davidoesch** [comment]
@gjn "use external_data_warning" for the PDF text.

**Comment by davidoesch** [comment]
@gjn on FF 38 if click on the mapserver gr link in the footer i get an undinfined, on chrome it works
"Mise en garde données tierces (undefined). Le permalien que vo"

**Comment by AFoletti** [comment]
done the IT. I would like to let a real french-speaking person do the FR ;)

**Comment by davidoesch** [comment]
@cedricmoullet speaks french I assume

**Comment by cedricmoullet** [comment]
done the french

**Comment by gjn** [comment]
French text still contains english stuff...

**Comment by cedricmoullet** [comment]
Which item ??

**Comment by cedricmoullet** [comment]
ok, I changed it.

2015-05-21 12:45 GMT+02:00 Gilbert Jeiziner <notifications@github.com>:

> French text still contains english stuff...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/pull/2282#issuecomment-104222906>
> .
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>

**Comment by gjn** [comment]
Everything updated according to comments. Please test [here](http://mf-geoadmin3.dev.bgdi.ch/teo_warn/?lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&X=132978.94&Y=596068.36&zoom=2&layers=WMS%7C%7CAusstattung%20Fl%C3%A4chen%7C%7Chttp:%2F%2Fmapserver1.gr.ch%2Fwms%2Fgenerellererschliessungsplan%3F%7C%7CAusstattung_Flaechen,KML%7C%7Chttp:%2F%2Fwww.bikingspots.ch%2FcreateKMLFile.php%3Ffilename%3Dreno333508077c95ddec.xml%26fc%3D1)

Question: Am I right to assume that kml generated with our new kml saving feature (https://github.com/geoadmin/mf-geoadmin3/pull/2323) is recognized as third party data?

**Comment by cedricmoullet** [comment]
no, it shouldn't since it's stored on public.geo.admin.ch

2015-05-21 13:40 GMT+02:00 Gilbert Jeiziner <notifications@github.com>:

> Everything updated according to comments. Please test here
> <http://mf-geoadmin3.dev.bgdi.ch/teo_warn/?lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&X=132978.94&Y=596068.36&zoom=2&layers=WMS%7C%7CAusstattung%20Fl%C3%A4chen%7C%7Chttp:%2F%2Fmapserver1.gr.ch%2Fwms%2Fgenerellererschliessungsplan%3F%7C%7CAusstattung_Flaechen,KML%7C%7Chttp:%2F%2Fwww.bikingspots.ch%2FcreateKMLFile.php%3Ffilename%3Dreno333508077c95ddec.xml%26fc%3D1>
>
> Question: Am I right to assume that kml generated with our new kml saving
> feature (#2323 <https://github.com/geoadmin/mf-geoadmin3/pull/2323>) is
> recognized as third party data?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/pull/2282#issuecomment-104237112>
> .
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>

**Comment by gjn** [comment]
But it's not created by us, nor do we have direct control over it. We only host it.
@davidoesch ?

**Comment by davidoesch** [comment]
to be on the save side: it is not created by us , it is created by a user (see icon) and therefore did not pass our data ingest system.
proposal: Keep it simple and on the save side: keep the warning always on, even for  *admin.ch  domains. since for a kml hosted on bafu servers: what do you want to show instead of the user icon ? we do not control availability....

**Comment by gjn** [comment]
So all kml/wms (externals) are recognized as third party?

**Comment by cedricmoullet** [comment]
ok, +1

2015-05-21 14:14 GMT+02:00 Gilbert Jeiziner <notifications@github.com>:

> So all kml/wms (externals) are recognized as third party?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/pull/2282#issuecomment-104252191>
> .
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>

**Comment by davidoesch** [comment]
+1

**Comment by davidoesch** [comment]
@gjin: there seems to be a  double  ": :" before the admin link....

**Comment by gjn** [comment]
Wrong thread :=) But good find.

I've corrected so that all external wms/kml are recognized as third party warning (test link updated). If it's good, I'd like to merge.

**Comment by cedricmoullet** [comment]
thanks. please merge

2015-05-21 14:36 GMT+02:00 Gilbert Jeiziner <notifications@github.com>:

> Wrong thread :=) But good find.
>
> I've corrected so that all external wms/kml are recognized as third party
> warning (test link updated). If it's good, I'd like to merge.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/pull/2282#issuecomment-104256088>
> .
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>

**Comment by gjn** [comment]
jenkins test

**Pull request merged**
