### PR TITLE
Use level 18 for imagery layers

### PR DESCRIPTION
**Pull request by loicgasser**
For 3d tile branch as requested.

Replaces https://github.com/geoadmin/mf-geoadmin3/pull/3495

### CODE REVIEW

**Comment by oterral** [comment]
Can you made 2 different commit one for the code to revert after i twill be merged in master and one for the rest, pls?

**Comment by loicgasser** [comment]
Quesako?

**Comment by loicgasser** [comment]
revert what?

**Comment by oterral** [comment]
The hardcoded metadataurl stuff. https://github.com/geoadmin/mf-geoadmin3/pull/3511/files#diff-66ac86f99915855fde57c0a20d8f6d6bR713

I'm pretty sure this url will be in the LayersConfig when we will merge this into master

**Comment by oterral** [comment]
Ah my bad, I thought this was the terrain metadat url and not only the imagery metadata url so we can put this on master. Sorry.

@loicgasser I've reopend your old PR against master https://github.com/geoadmin/mf-geoadmin3/pull/3495.

**Pull request closed without merging**
