### PR TITLE
Fix dnd on firefox

### LINKED ISSUE #3197: FF: select box does not work
FF: select box does not work
Windows 10 mit Firefox 44 od. 45 => funktioniert nicht
Windows 7 mit Firefox 42 => funktioniert ebenfalls nicht

unbenannt

### PR DESCRIPTION
**Pull request by oterral**
Fix #3197 and also deactivate swipe.

[Test] (https://mf-geoadmin3.dev.bgdi.ch/teo_fixff/?)

I've used part of #3202, the commit https://github.com/ioda-net/mf-geoadmin3/commit/ac8c4615d6257b159289d9a10f56cb113ed69ab8

We could update slipjs and remove the slipjs patch when https://github.com/pornel/slip/issues/66 will be fixed.

### CODE REVIEW

**Comment by oterral** [comment]
Thx to @Jenselme for the debugging slipjs.

**Comment by oterral** [comment]
jenkins test

**Comment by Jenselme** [comment]
@oterral you're welcome.

**Comment by cedricmoullet** [comment]
Tested on Mac: Safari, Firefox, Chrome -> all is fine.
Cursor change is not implemented -> could be in another PR.
@davidoesch ?

**Comment by gjn** [comment]
Tested in IE11, FF44 and latest chrome. All good.
@davidoesch Please merge when good.

Thanks @Jenselme and @oterral for the joined effort.

**Pull request merged**
