### PR TITLE
[3D] Use ogcproxy for external WMS in 3d (CORS issue)

### PR DESCRIPTION
**Pull request by oterral**
[test](https://mf-geoadmin3.dev.bgdi.ch/teo_proxy/?lang=fr&topic=ech&bgLayer=ch.swisstopo.swisstlm3d-karte-farbe&dev3d=true&layers=WMS%7C%7COrthophoto%20Avenches%20Haras%7C%7Chttp:%2F%2Fogc.heig-vd.ch%2Fmapserver%2Fwms%3F%7C%7Cr-pod_avenches_haras&lon=7.00738&lat=46.87824&elevation=6379&heading=358.684&pitch=-85.726)

### CODE REVIEW

**Comment by gjn** [comment]
It's not needed for wms.geo.admin.ch, is it?

**Comment by oterral** [comment]
no it's the only one with CORS headers

**Comment by gjn** [comment]
Shouldn't we exclude it here then? As I understand it, we use ogcproxy now for all wms resources in 3D.

**Comment by oterral** [comment]
Yes we could .

**Comment by gjn** [comment]
I think we should. Most wms source will be our wms.

**Comment by oterral** [comment]
ok I change

**Comment by oterral** [comment]
@gjn PR updated with test link [test](https://mf-geoadmin3.dev.bgdi.ch/teo_proxy/?lang=fr&topic=ech&bgLayer=ch.swisstopo.swisstlm3d-karte-farbe&dev3d=true&layers=WMS%7C%7COrthophoto%20Avenches%20Haras%7C%7Chttp:%2F%2Fogc.heig-vd.ch%2Fmapserver%2Fwms%3F%7C%7Cr-pod_avenches_haras&lon=7.00738&lat=46.87824&elevation=6379&heading=358.684&pitch=-85.726)

**Pull request merged**
