### PR TITLE
Handle group synchronization

### PR DESCRIPTION
**Pull request by gberaudo**
Synchronization of a layer to Cesium was only performed on `ol.layer.layer`.
This PR allows the synchronization of an`ol.layer.Group` to Cesium.

A test link is available at https://mf-geoadmin3.dev.bgdi.ch/teo_lg/src/?dev3d=true

### CODE REVIEW

**Comment by gberaudo** [comment]
Depends on https://github.com/openlayers/ol3-cesium/pull/251

**Comment by cedricmoullet** [comment]
I'm wondering why the TLM names layer is visible in 3D. Any idea ?

**Comment by gberaudo** [comment]
When removing all the extra layers through the menu and I look at the network view in chromium, I only see requests for two 3D layers, which is what I expect:
- https://wmts12.geo.admin.ch/1.0.0/ch.swisstopo.swissnames3d/default/20150101/4326/5/30/7.png
- https://wmts11.geo.admin.ch/1.0.0/ch.swisstopo.swisstlm3d-karte-farbe/default/20150401/4326/10/1066/240.png

Cédric, do you mean the tiles are not generated correctly?

**Comment by cedricmoullet** [comment]
I see requests to https://wmts13.geo.admin.ch/1.0.0/ch.swisstopo.swissnames3d/default/20150101/4326/14/17115/3919.png

image

**Comment by gberaudo** [comment]
Isn't it expected?
The hardcoded layer config we use contains:
```
              response.data['ch.swisstopo.pixelkarte-farbe_3d'] = {
                subLayersIds: [
                  'ch.swisstopo.swisstlm3d-karte-farbe',
                  'ch.swisstopo.swissnames3d'
                ],
```

**Comment by cedricmoullet** [comment]
Ok, I see. Thanks for investigating. We can currently remove ch.swisstopo.swissnames3d. When we'll get the 3D representation of this layer (billboard), then we'll reintroduce it.

**Comment by gberaudo** [comment]
I updated the PR and updated the test link.

**Comment by cedricmoullet** [comment]
Thanks, it works well.

**Comment by gjn** [comment]
Nice. This fixes also https://github.com/geoadmin/mf-geoadmin3/issues/2692

Looking at code now.

**Comment by gjn** [comment]
Nicely done. Thanks alot @gberaudo

**Pull request merged**
