### PR TITLE
Update_rm.json

### PR DESCRIPTION
**Pull request by mariokeusen**
New RM strings entered from the translation project.
@davidoesch @AFoletti pls review

<jenkins>[Test link](https://mf-geoadmin3.int.bgdi.ch/mariokeusen_new_RM_translations/1905280620/index.html)</jenkins>

### CODE REVIEW

**Comment by davidoesch** [comment]
No ... The test view link has to stay.

**Comment by pakb** [comment]
Here are the diff between this PR and a `make translate` :

- `azimuth_label` : `\n` in the spreadsheet
- `external_data_tooltip` : `\n` in the spreadsheet
- `layer_invalid_outside_map` : `\r\n\n` in the spreadsheet
- `link_validate_kml` switches back to `Link to KML validation` (translation missing in the spreadsheet)
- `locations_results_header_fuzzy` : `\n` in the spreadsheet
- `print_layout` : `\n` in the spreadsheet
- `shop_msg_title` : trailing space in the spreadsheet
- `topic_meteoschweiz_tooltip` : `\r\n\n` in the spreadsheet

@davidoesch please check that `try_test_viewer` is defined in the spreadsheet

**Comment by davidoesch** [comment]
defined it in the spreadsheet.

**Comment by mariokeusen** [comment]
@pakb : I have removed all those carriage returns and not needed spaces in the spreadsheet. No RM translation available for link_validate_kml, therefore DE translation is set.

**Pull request merged**
