### PR TITLE
[WIP] Config for pk shop layer

### PR DESCRIPTION
**Pull request by pfanguin**
This works but we still need to adapt the tests
Ping @pauloamado

### CODE REVIEW

**Comment by pfanguin** [comment]
jenkins test

**Comment by gjn** [comment]
jenkins test

**Comment by gjn** [comment]
jenkins test

**Comment by gjn** [comment]
Working now. In jenkins config, only 3dtiles target branches was enabled. Now all PR.

**Comment by pfanguin** [comment]
Ok Thanks

**Comment by gjn** [comment]
jenkins test

**Comment by procrastinatio** [comment]
Failing test is related to PR https://github.com/geoadmin/mf-geoadmin3/pull/3648 which was merged while no jenkins was no active.
We may safely merge this PR.

**Pull request merged**
