### PR TITLE
Detection of WMS/WMTS urls

### LINKED ISSUE #3784: WMS Services geodienste.ch
www.geodienste.ch has now a coouple of aggregated WMS sources ready
can they be added to the pulldown menu in "import"

- Amtliche Vermessung (MOpublic) : https://geodienste.ch/db/av/deu?SERVICE=WMS&REQUEST=GetCapabilities

-Amtliche Vermessung (MOpublic, Jahresstand) https://geodienste.ch/db/av_jahresstand/deu?SERVICE=WMS&REQUEST=GetCapabilities

### LINKED ISSUE #3823: IE9:  No more checkboxes in catalog

### LINKED ISSUE #3844: WMTS sigip not working on new geoservice import tool.
Hi! Great feature local and WMTS import!

Having trouble on both WMTS
image
and WMS (parsing error)
image

services based on a GMF 1.6.10 for sigip.

URLS : 
WMS : https://www.sigip.ch/main/wsgi/mapserv_proxy
WMTS : https://www.sigip.ch/main/tiles/1.0.0/WMTSCapabilities.xml

Works fine on https://ows.asitvd.ch/wmts/1.0.0/WMTSCapabilities.xml which could be added to the suggested geoservices.

### PR DESCRIPTION
**Pull request by oterral**
Fix #3784
Fix #3844
Fix #3823 

It's not perfect but fit 95% of the usecases.

[Test](https://mf-geoadmin3.int.bgdi.ch/teo_detect/index.html)

### CODE REVIEW

**Comment by davidoesch** [comment]
tested geodienste import works

**Comment by oterral** [comment]
don't merge yet I'm adding tests.

**Comment by oterral** [comment]
jenkins test

**Comment by oterral** [comment]
Tests added pleas ereview

**Comment by procrastinatio** [comment]
Nice
https://public.int.bgdi.ch/PiX2rwhSTrOTcrD7_VdtrA

**Comment by oterral** [comment]
jenkins test

**Pull request merged**
