### PR TITLE
Update links to vtg

### PR DESCRIPTION
**Pull request by loicgasser**
Fix for https://github.com/geoadmin/mf-geoadmin3/issues/3523
same as https://github.com/geoadmin/mf-geoadmin3/issues/3521

### CODE REVIEW

**Comment by gjn** [comment]
Not sure about the attributation. Current link goes to www.vbs.admin.ch, not www.vtg.admin.ch

https://map.geo.admin.ch/?topic=verteidigung&lang=fr&bgLayer=ch.swisstopo.pixelkarte-grau&catalogNodes=1562,1572&layers=ch.vbs.territorialregionen,ch.vbs.logistikraeume-armeelogistikcenter,ch.vbs.retablierungsstellen&layers_opacity=0.6,0.75,0.75&layers_visibility=false,false,true

**Comment by gjn** [comment]
please change vbs links as well.

**Comment by loicgasser** [comment]
Some of the attributions actually come from BOD. I adapt now.

**Comment by loicgasser** [comment]
VBS translations in https://github.com/geoadmin/mf-chsdi3/pull/2248/files

**Pull request merged**
