### PR TITLE
[ON HOLD] Fix #3146: Send the geojson feature to the parent window

### LINKED ISSUE #3146: Post message of kml id/name on click
Currently, in iframe mode, we post a message containing the id of the clicked element to the parent page.

This functionality should be extended. When a kml is integrated in the page and the user clicks on an placement of the kml, the name/id of the clicked element should be send.

@oterral Possible? Effort?

### PR DESCRIPTION
**Pull request by oterral**
Fix #3146

### CODE REVIEW

**Comment by gjn** [comment]
Does this change the message send in any way? Because we have hydrodaten website that already uses this, which would need adaption.

**Comment by oterral** [comment]
Yes that changes (we pass the entire  feature with GeoJSON format).  Hydrodaten website owner must be warned

**Comment by gjn** [comment]
Can we have old and new in parallel? So we can deploy both without risk to have hydrodaten broken?

This should be a cearly defined interface that doesn't change often. It will be used by multiple clients in the future.

Do you think current state is ok going forward?

**Comment by oterral** [comment]
I think sending the feature with the geometry, properties and htmlpopup content, we fill 90% of usecases.

Maybe we can send an object with a feature propertiy in case we need to add more values like the layer or click informations.

**Comment by oterral** [comment]
Living with the 2 in parallel seems complicated. I don't think we can.

**Comment by gjn** [comment]
I think https://github.com/geoadmin/mf-geoadmin3/issues/3146 is enough for the use case we want. And it doesn't break the GeoJSON. So I close this one.

**Pull request closed without merging**
