### PR TITLE
Fix #2502: Improve detection of non third party data

### LINKED ISSUE #2502: Warning message on wms-bgdi import
Would it be so complicated to add a further "if..then" in the code so that:

if wms_import_url=wms.geo.admin.ch/ then warning icon/message is not shown?

### PR DESCRIPTION
**Pull request by oterral**
Fix #2502 with tests

### CODE REVIEW

**Comment by gjn** [comment]
Hmm. I think we want to keep the warning for public.geo.admin.ch, because it's created by 3rd party (clients create the kml)

**Comment by oterral** [comment]
Yes you're right, I will improve the regex

**Comment by oterral** [comment]
@gjn fixed

Tests with all kind of third  and non third party links:

https://mf-geoadmin3.dev.bgdi.ch/teo_fix_2502/?lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&X=190000.00&Y=660000.00&zoom=1&layers=KML%7C%7Chttps:%2F%2Fpublic.dev.bgdi.ch%2F7Fl0LkvzSJmzFlKFJaCMmQ,WMS%7C%7CAGNES%7C%7Chttps:%2F%2Fwms.geo.admin.ch%2F%7C%7Cch.swisstopo.fixpunkte-agnes,WMS%7C%7COrthophoto%20Bern%20Puzzle%202%7C%7Chttp:%2F%2Fogc.heig-vd.ch%2Fmapserver%2Fwms%3F%7C%7Cr-pod_bern_puzzle-2

**Comment by gjn** [comment]
Very nice. Thanks alot.

**Pull request merged**
