### PR TITLE
Fix share title

### PR DESCRIPTION
**Pull request by loicgasser**
Fix for https://github.com/geoadmin/mf-geoadmin3/issues/3221

### CODE REVIEW

**Comment by davidoesch** [comment]
This one was on my wishlist since a long time

**Comment by loicgasser** [comment]
[Test Link](https://mf-geoadmin3.dev.bgdi.ch/gal_share/)

**Comment by cedricmoullet** [comment]
ok for me.

2016-03-16 18:23 GMT+01:00 Gasser Loïc <notifications@github.com>:

> Test Link <https://mf-geoadmin3.dev.bgdi.ch/gal_share/>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/pull/3222#issuecomment-197441523>
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>

**Comment by davidoesch** [comment]
OK (droid)

**Comment by cedricmoullet** [comment]
Can be merged after checks are working

**Comment by gjn** [comment]
jenkins test

**Comment by gjn** [comment]
Jenkins failure is unrealted.

**Pull request merged**
