### PR TITLE
Fix nvm usage by adding the same loading script as in .bash_profile

### PR DESCRIPTION
**Pull request by pakb**
This assume that env variable NVM_DIR is defined

<jenkins>[Test link](https://mf-geoadmin3.int.bgdi.ch/bap_fix_makefile/index.html)</jenkins>

### CODE REVIEW

**Comment by oterral** [comment]
Works for me

**Comment by oterral** [comment]
I merge too fast, for ng-annotate use it's not useable.

**Comment by oterral** [comment]
Just run ` make clean user`  see the difference with before.  Now it set the nvm version for each annotated file, which means  hundred of times.

**Comment by pakb** [comment]
If ng-annotate doesn't need explicitly node version 6.13.0 but is fine with version 5.x.x (which is the default version delivered with debian) we could remove this NVM call before ng-annotate.
But that would leave us with a future issue when ng-annotate will need a higher version of node.

Alternatively, we could have as prerequisite for this project to have node 6.13.0 installed (and stop building it if not at the correct version)

**Pull request merged**
