### PR TITLE
Fix the ol version and add missing export

### LINKED ISSUE #2252: [WGS84 Pos not displayed anymore]
Is this a regression? 

From Helpdesk

`Hallo, Wieso zeigt es die WGS 84 Koordinaten nicht mehr an Gruß Herre.`

### PR DESCRIPTION
**Pull request by oterral**
Fix #2252 

[Test](http://mf-geoadmin3.dev.bgdi.ch/teo_fix_2252/index.html)

### CODE REVIEW

**Comment by ponceta** [comment]
jenkins test

**Comment by ponceta** [comment]
@kandre If you have time to test on IOS, I'll check android and Surface, since update ol 3.4.0, could be great to test before!

**Comment by ponceta** [comment]
Tested on android chrome windows and firefox. Works fine

**Comment by gjn** [comment]
I've tested on IE9, no apparent problems. Please merge this when you think tests are finished.

**Comment by kandre** [comment]
about ios..., a bit late, but no bugs found !

**Pull request merged**
