### PR TITLE
BGDIINF_SB-2077 Changing backend name for Qrcode and Feedback services

### PR DESCRIPTION
**Pull request by procrastinatio**
Changing backend hostnames again!

See https://jira.swisstopo.ch/browse/BGDIINF_SB-2077

For shortener, see https://github.com/geoadmin/mf-geoadmin3/pull/5249

For KML, see https://github.com/geoadmin/mf-geoadmin3/pull/5254

Testing (QRCODE & FEEDBACK only): https://mf-geoadmin3.dev.bgdi.ch/feature_BGDIINF_SB-2077_service_backends/2203101719/index.html?qrcode_url=//map.geo.admin.ch&feedback_url=//map.geo.admin.ch

or even better

https://mf-geoadmin3.dev.bgdi.ch/feature_BGDIINF_SB-2077_service_backends/2203101719/index.html?staging=prod

check that both services are using the new url in _map.geo.admin.ch_.

See : view-source:https://mf-geoadmin3.dev.bgdi.ch/feature_BGDIINF_SB-2077_service_backends/2203101719/index.html should be OK.

### CODE REVIEW

**Comment by hansmannj** [comment]
Are the links correct or should we use new ones? (The former type in the branch name is still present in the test links)

**Review by hansmannj — APPROVED** [review]
LGTM, thanks!

**Comment by procrastinatio** [comment]
@hansmannj branch's name was wrong but code was correct. Redeployed only (no code change)

**Comment by procrastinatio** [comment]
@hansmannj OK, merci

**Pull request merged**
