### PR TITLE
Renable 3d metadata usage

### PR DESCRIPTION
**Pull request by loicgasser**
@oterral You know what to do when the current issue is solved.

This PR reactivates  the metadataUrl

### CODE REVIEW

**Comment by oterral** [comment]
Ok I continue this PR

**Comment by loicgasser** [comment]
Well, raster extent is smaller than terrain extent. As a result everything works as expected except that we have black tiles again (terrain is defined but imagery is not which ends up in a black tile)

I propose that we use the pixelkarte `layer.json` ranges to work around this problem.

[Test Link](https://mf-chsdi3.dev.bgdi.ch/shorten/6844ee7c90)

**Comment by loicgasser** [comment]
Ready for review. If the PR is ok with you let me know as I still need to remove https://github.com/geoadmin/mf-geoadmin3/commit/973680dbbc39642b204698a12e6d368ca13589ab and upload the new `layer.json` to S3 for the timestamp `20160101`.

Layers with a 3d config at the moment are:
`ch.bafu.wrz-wildruhezonen_portal`
`ch.swisstopo.swisstlm3d-wanderwege`
`ch.swisstopo.fixpunkte-agnes`
`ch.swisstopo.swisstlm3d-karte-grau.3d`
`ch.swisstopo.swisstlm3d-karte-farbe.3d`
`ch.swisstopo.swissimage-product_3d`

It avoids a lot of `204` responses on pre-generated tiles.
MapProxy returns empty transparent tiles with a `200` response code, thoses are avoided as well.

**Comment by gjn** [comment]
How big are the layer.json files for these layers?

**Comment by loicgasser** [comment]
```
60.1 KB
125 KB
3.2 KB
12.1 KB
12.1 KB
12.1 KB
12.1 KB
```

**Comment by gjn** [comment]
Those are good sizes. Thanks alot for the info.

**Comment by loicgasser** [comment]
squashed and rebased, this should be good to go.

**Comment by loicgasser** [comment]
jenkins test

**Comment by loicgasser** [comment]
`NoSuchElementError: no such element: Unable to locate element: {"method":"xpath","selector":"//a[contains(@href, 'X=128114.80&Y=629758.13&zoom=10')]"}`

we basically have this error all the time any idea?

**Comment by oterral** [comment]
jenkins test

**Comment by oterral** [comment]
@gjn good to review/merge

**Comment by loicgasser** [comment]
probably worth ta try on mobile as well. @oterral have you tried?

**Comment by gjn** [comment]
This needs a rebase.

Also, it will likely conflict with https://github.com/geoadmin/mf-geoadmin3/pull/2955

But it looks good to me and I want to merge it ASAP.

**Comment by oterral** [comment]
I've rebased this morning :) I re-rebase.

**Comment by oterral** [comment]
Rebased @gjn

**Comment by gjn** [comment]
We have 3 PR's in conflict currently. :=)

I'll merge this one once build is done.

**Comment by gjn** [comment]
Good work. Thanks alot, it's worth the effort.

**Pull request merged**
