### PR TITLE
Use pixel detection to determine which layers to query

### PR DESCRIPTION
**Pull request by oterral**
This PR complete https://github.com/geoadmin/mf-geoadmin3/pull/2865

Works for good browsers and IE > 10

[Test](https://mf-geoadmin3.dev.bgdi.ch/teo_noinfo/?lang=de&topic=ech&bgLayer=ch.swisstopo.swissimage&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege,ch.swisstopo.fixpunkte-agnes,ch.astra.wanderland&layers_visibility=false,false,false,false,true,true&layers_timestamp=18641231,,,,,&X=170321.70&Y=631614.30&zoom=13)

### CODE REVIEW

**Comment by gjn** [comment]
jenkins test

**Comment by gjn** [comment]
don't we have same/similar code to change/adapt the cursor that we could re-use?

(I'm on mobile)

**Comment by oterral** [comment]
Not exactly the same and I wanted to be sure to don't break anything.

**Comment by loicgasser** [comment]
jenkins test

**Comment by oterral** [comment]
@loicgasser can you merge this one ?

**Comment by loicgasser** [comment]
LGTM

**Pull request merged**
