### PR TITLE
[WIP] DIEMO integration

### PR DESCRIPTION
**Pull request by pakb**
<jenkins>A test link will be added here if the deploy on int succeeded.</jenkins>

<jenkins>[Test link](https://mf-geoadmin3.int.bgdi.ch/ltkum_diemo_css/1908120813/index.html)</jenkins>

### CODE REVIEW

**Comment by pakb** [comment]
Test link on INT here : https://mf-chsdi3.int.bgdi.ch/diemo/shorten/82d8d2de5a
https://github.com/geoadmin/mf-chsdi3/pull/3223 has to be merged for this PR to work

**Comment by AFoletti** [comment]
Hello @pakb and @ltkum 
could you please deploy the last fix (CSS issue) to the INT environment? I would like to give the customer a testlink with that fix already implemented.
Thanks!

**Comment by pakb** [comment]
We have something to fix on the test link on AWS S3, something went wrong when I deployed the branch this morning

**Comment by ltkum** [comment]
response headers of different requests : 

through **curl**

curl -I https://mf-chsdi3.int.bgdi.ch/diemo/shorten/82d8d2de5a

`HTTP/1.1 301 Moved Permanently
Date: Wed, 03 Jul 2019 12:06:30 GMT
**Content-Type: application/json**
Content-Length: 54
Connection: keep-alive
Server: Apache/2.4.10 (Debian)
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: POST, GET, OPTIONS
Access-Control-Allow-Headers: x-requested-with, Content-Type, origin, authorization, accept, client-security-token
Location: https://mf-geoadmin3.int.bgdi.ch/ltkum_diemo_css/index.html?api_url=%2F%2Fmf-chsdi3.int.bgdi.ch%2Fdiemo&bgLayer=ch.swisstopo.pixelkarte-grau&layers=ch.bfe.ladestellen-elektromobilitaet&topic=ech&lang=fr&config_url=%2F%2Fmf-chsdi3.int.bgdi.ch%2Fdiemo%2Fconfigs
X-UA-Compatible: IE=Edge
Cache-Control: max-age=1800, public
X-Varnish: 160179325
Age: 0
Via: 1.1 varnish-v4
X-Cache: MISS
`

curl -I https://mf-geoadmin3.int.bgdi.ch/ltkum_diemo_css/index.html?api_url=%2F%2Fmf-chsdi3.int.bgdi.ch%2Fdiemo&bgLayer=ch.swisstopo.pixelkarte-grau&layers=ch.bfe.ladestellen-elektromobilitaet&topic=ech&lang=fr&config_url=%2F%2Fmf-chsdi3.int.bgdi.ch%2Fdiemo%2Fconfigs

`HTTP/1.1 200 OK
**Content-Type: text/html**
Content-Length: 7976
Connection: keep-alive
Date: Wed, 03 Jul 2019 12:05:46 GMT
Last-Modified: Wed, 03 Jul 2019 10:07:32 GMT
ETag: "b3c321a2214ca26270c03eb865c93b76"
Cache-Control: max-age=0, must-revalidate, s-maxage=300
Content-Encoding: gzip
x-amz-meta-pragma: no-cache
Expires: Mon, 01 Jan 1990 00:00:00 GMT
x-amz-version-id: gNWkHDw8uENGS2wPgFDc8CBBQ7e4Monp
x-amz-meta-vary: *
Accept-Ranges: bytes
Server: AmazonS3
Age: 102
X-Cache: Hit from cloudfront
Via: 1.1 ce024f609b66dae59e41a6b53a8757ba.cloudfront.net (CloudFront)
X-Amz-Cf-Pop: DUB2-C1
X-Amz-Cf-Id: 5CMdJKtP-vmj0xU5dhWKTLTKTC4HrCPRfN1Mv33lK2tbPWbWFcpScg==
`
accessing through **browser** (both firefox and chrome) : 

https://mf-geoadmin3.int.bgdi.ch/ltkum_diemo_css/index.html?api_url=%2F%2Fmf-chsdi3.int.bgdi.ch%2Fdiemo&bgLayer=ch.swisstopo.pixelkarte-grau&layers=ch.bfe.ladestellen-elektromobilitaet&topic=ech&lang=fr&config_url=%2F%2Fmf-chsdi3.int.bgdi.ch%2Fdiemo%2Fconfigs
`
HTTP/2.0 200 OK
**content-type: binary/octet-stream**
content-length: 7976
date: Wed, 03 Jul 2019 08:04:12 GMT
last-modified: Wed, 03 Jul 2019 07:53:34 GMT
etag: "5dbf9c7997cd225533412ff5ed0c7b40-1"
x-amz-version-id: kUbFmf4qJcDRISdgkEUC_PXJoAK4HWlV
accept-ranges: bytes
server: AmazonS3
age: 14645
x-cache: Hit from cloudfront
via: 1.1 a4f3f56409fe4e0b42683dc15dd52ef8.cloudfront.net (CloudFront)
x-amz-cf-pop: ZRH50-C1
x-amz-cf-id: yqkDtm6ttP1Wb4NLYAtYtEBONcBAFq_3HKLrEE8q6VONyKGdJmckDg==
X-Firefox-Spdy: h2
`

https://mf-chsdi3.int.bgdi.ch/diemo/shorten/82d8d2de5a

`
HTTP/2.0 301 Moved Permanently
date: Wed, 03 Jul 2019 12:10:54 GMT
**content-type: application/json**
content-length: 54
location: https://mf-geoadmin3.int.bgdi.ch/ltkum_diemo_css/index.html?api_url=%2F%2Fmf-chsdi3.int.bgdi.ch%2Fdiemo&bgLayer=ch.swisstopo.pixelkarte-grau&layers=ch.bfe.ladestellen-elektromobilitaet&topic=ech&lang=fr&config_url=%2F%2Fmf-chsdi3.int.bgdi.ch%2Fdiemo%2Fconfigs
server: Apache/2.4.10 (Debian)
access-control-allow-origin: *
access-control-allow-methods: POST, GET, OPTIONS
access-control-allow-headers: x-requested-with, Content-Type, origin, authorization, accept, client-security-token
x-ua-compatible: IE=Edge
cache-control: max-age=1800, public
x-varnish: 162694601
age: 0
via: 1.1 varnish-v4
x-cache: MISS
X-Firefox-Spdy: h2
`
and 
`
HTTP/2.0 200 OK
**content-type: binary/octet-stream**
content-length: 7976
date: Wed, 03 Jul 2019 08:04:12 GMT
last-modified: Wed, 03 Jul 2019 07:53:34 GMT
etag: "5dbf9c7997cd225533412ff5ed0c7b40-1"
x-amz-version-id: kUbFmf4qJcDRISdgkEUC_PXJoAK4HWlV
accept-ranges: bytes
server: AmazonS3
age: 14803
x-cache: Hit from cloudfront
via: 1.1 a4f3f56409fe4e0b42683dc15dd52ef8.cloudfront.net (CloudFront)
x-amz-cf-pop: ZRH50-C1
x-amz-cf-id: TxUCRdY9yoPmWDk3hs4k8sNNLdgDz0XKaoRLdPrF23lS7s2kNCCOZA==
X-Firefox-Spdy: h2
`

@sontags , @danduk82 , Any of you have an idea why we have such a result ?

**Comment by ltkum** [comment]
image

I do not know if this is normal (and I guess this is not the case), but build.js is served as an octet-stream too.

**Comment by sontags** [comment]
Are the source files correctly (UTF-8) encoded? This looks a bit fishy to me. And skimming trough paths other that /ltkum_diemo_css/ I was not able to find similar behaviour...

**Comment by pakb** [comment]
It was maybe induces by the software I used to move some files at the root of folder `/ltkum_diemo_css` instead of using AWS CI through `make s3activateint`.
I've not been able to reproduce this behaviour on other branches, but I haven't used anything but `make s3activateint` for other branches.

**Pull request merged**
