### PR TITLE
Redesign search

### PR DESCRIPTION
**Pull request by kandre**
According to #2325

[Testlink](https://mf-geoadmin3.dev.bgdi.ch/kan_redesign_search)

Translation may need to be enhanced

### CODE REVIEW

**Comment by gjn** [comment]
help icon and delete text icon are wrongly placed (FF and chrome) because of newly added text.

Otherwise, I like it.

**Comment by ponceta** [comment]
Need a "rumantsch Übersetzung" but otherwise looks fine indeed.

**Comment by kandre** [comment]
I redeployed the branch, now the icon are properly placed

**Comment by kandre** [comment]
I also made the categories labels (such as 'Go to ...', Add map ...') in bold, but there are still not so visible

**Comment by kandre** [comment]
@davidoesch @AFoletti have you an idea to translate the following in RM respectively IT ?
- Search for a place or map:
- Carte du bruit
- Go to ...
- Add map ...
- Go to the object ...

Thks

**Comment by AFoletti** [comment]
- Cercare un luogo od un set di dati
- Mappa del rumore
- Vai a...
- Aggiungi set di dati
- Vai all'oggetto...

**Comment by kandre** [comment]
jenkins test

**Comment by davidoesch** [comment]
Suche Ort oder Karte :
    Lärmkarte
    Gehe nach ...
    Karte hinzufügen ...
    Gehe zum Objekt ...

**Comment by kandre** [comment]
@davidoesch thank you for the german translation. What about romanche, how would you translate it?

**Comment by kandre** [comment]
jenkins test

**Comment by davidoesch** [comment]
@kandre  we have actaully already  a msgid for the first line: search_placeholder 

Therefore in rumantsch
- Tschertgar lieu u charta
- Charta canera
- Ir a...
- Agiuntar charta ...
- Ir al object

**Comment by gjn** [comment]
If this is ready, please squash it.

**Comment by gjn** [comment]
@kandre Please squash/rebase and remove the WIP when ready.

**Comment by kandre** [comment]
Squashed. 

Ready for review / merge

**Comment by gjn** [comment]
`Suche Ort oder hinzufügen Karte` for german? I think it would be better `Ort suchen order Karte hinzufügen`, no @davidoesch

**Comment by gjn** [comment]
The removal of the footer is good, but can you try to keep a little white border at the bottom of the result list?

**Comment by gjn** [comment]
Code is very nice!

**Comment by davidoesch** [comment]
+1 for  Ort suchen order Karte hinzufügen,

**Comment by gjn** [comment]
@kandre How did you update the translations? I don't see them in the google spreadsheet.

**Comment by kandre** [comment]
@gjn for the border I had the same idea, I hesitated. I you also also lets go with a bit of white vorder at the bottom

**Comment by kandre** [comment]
Maybe I will learn something...which google spreadsheet ? There is one for translations ?

**Comment by gjn** [comment]
Email send :)

**Comment by davidoesch** [comment]
Hilarious

**Comment by kandre** [comment]
Haha definitely, explain why I misunderstoods some messages from you David ! Sorry about that !

**Comment by davidoesch** [comment]
Seems like we need to introduce a new process

**Comment by kandre** [comment]
I made the corrections, it is ready.

**Comment by kandre** [comment]
and thank you for the review you did

**Comment by gjn** [comment]
Good stuff. Thanks alot.

**Comment by kandre** [comment]
Thanks !

**Pull request merged**
