### PR TITLE
Offline obsolete warning

### PR DESCRIPTION
**Pull request by oterral**
Fix part of https://github.com/geoadmin/mf-geoadmin3/issues/3246

[Test](https://mf-geoadmin3.dev.bgdi.ch/teo_offup/mobile.html)

### CODE REVIEW

**Comment by oterral** [comment]
@gjn @david can you test this pr ? comments are welcome.

**Comment by gjn** [comment]
Is there an easy way to test this?

We only alert the warning, but we don't do anything, correct? User has to delete/safe the map on his own?

If so, the message should give clear instructions on what to do.

ping @davidoesch .

**Comment by davidoesch** [comment]
How can I test this?

**Comment by oterral** [comment]
That only warn the user when the app starts

Only way to test:

1) Open mobile version on desktop
2) Download layers for offline use
3) Open the debug console -> Resources -> Local storage (on the left) -> Change timestamps
4) Reload the app

**Comment by gjn** [comment]
This approach is fine with me for now. I've created the item in the translation file: `offline_cache_obsolete`.

Note that the message will always appear as long as the user didn't delete the saved map.

@davidoesch Please verify english/german text
@AFoletti Can you create the italian version?
@oterral  Can you create the french version and integrate the translations in the PR?

We still have the issue when the 'current' timestamp is updated. For this, we would need the [cacheUpdate service](http://api3.geo.admin.ch/services/sdiservices.html#cache-update) service. I create a low prio issue for this.

**Comment by davidoesch** [comment]
offline_cache_obsolete Text is ok fpr DE FR EN RM(placeholder)
-> @AFoletti update IT pls

**Comment by AFoletti** [comment]
done IT

**Comment by oterral** [comment]
Rebased and translated

**Pull request merged**
