### PR TITLE
disable shop popup

### PR DESCRIPTION
**Pull request by rfrancel**
test link for fertig produkte:
https://mf-chsdi3.dev.bgdi.ch/frr_fertigprod_tooltips/shorten/6b5ef07902

test link for a few papierkarten:
https://mf-chsdi3.dev.bgdi.ch/frr_fertigprod_tooltips/shorten/6b5ef25431

linked to:
https://github.com/geoadmin/mf-chsdi3/pull/2036/commits/8b4cd3bac2e1a75ebe62f0a1b6554789e2e3eeb7

### CODE REVIEW

**Comment by oterral** [comment]
lgtm

**Comment by gjn** [comment]
@rfrancel Thanks alot for this. Looks good to me. I think on mobile (iPhone 4), this could be a little bit improved. Maybe even remove image when screen is too small? @davidoesch ?

@rfrancel Could you provide a testlink with all the fertigprodukte layers? (I assume the above does not contain all the fertigprodukte layers)

**Comment by davidoesch** [comment]
+1 for removing the image if on a small screen like iPhone 4s. This means that tooltip Mako will be responsive ....

**Comment by gjn** [comment]
This can be merged once https://github.com/geoadmin/mf-chsdi3/pull/2036 is merged.

**Comment by rfrancel** [comment]
image is no more displayed when small screen, resolved in #2036

**Comment by rfrancel** [comment]
@gjn I merge this as geoadmin/mf-chsdi3#2036 is merged.

**Comment by gjn** [comment]
+1

**Pull request merged**
