### PR TITLE
Add KmlService tests

### PR DESCRIPTION
**Pull request by oterral**
Add 1% of tests

[Test](https://mf-geoadmin3.dev.bgdi.ch/teo_tests/)

### CODE REVIEW

**Comment by gjn** [comment]
@mariavkourouni @rfrancel Can you test this branch with the testlink above with a couple of simple and advanced kml files? Let me know if you find something.

**Comment by rfrancel** [comment]
It seems fine to me.
I guess you already discussed this, but couldn't we give a hint to the user about what maximal size a kml should be when the 'file too big' message pops up?

**Comment by mariavkourouni** [comment]
It works fine also for me

**Comment by oterral** [comment]
good idea @rfrancel create an issue please.

**Comment by gjn** [comment]
Thanks alot for testing!

**Pull request merged**
