### PR TITLE
Cancel the print process

### LINKED ISSUE #2117: Add cancel button to stop print process
Like the offline component , the print button should be transformed in a cancel button when the print progress begins.

### PR DESCRIPTION
**Pull request by oterral**
Fix #2117

[Test](http://mf-geoadmin3.dev.bgdi.ch/teo_cancel/);

In the case a multiprint that send a cancel request to the print server.

-  [x] chsdi needs to be modify to handle the cancel request

### CODE REVIEW

**Comment by gjn** [comment]
FYI, there won't be a possibility to cancel a multiprint serverside because of multiple back-ends and cookie less state.

We could work around that using zadara back-end (create and check cancel file on shared volume), but I'm not sure it's worth the pain (given how rarelry the multiprint is used).

**Comment by procrastinatio** [comment]
@gjn I agree it is not very used, but with this PR, a single user may start, stop, change his mind and restart  print jobs and destroy the server.

**Comment by gjn** [comment]
I'll create a PR tomorrow for back-end.

**Comment by gjn** [comment]
PR is back-end is ready. https://github.com/geoadmin/mf-chsdi3/pull/1258

I've tested it with this branch and it works well. On deploy, also needs testing on int (because of multi-machine setup)

@procrastinatio @oterral Please test/review as well.

**Comment by oterral** [comment]
@procrastinatio can you review  pls?

**Comment by procrastinatio** [comment]
Looks good for this part, I am testing the backend.

**Comment by oterral** [comment]
thx @procrastinatio

**Pull request merged**
