### PR TITLE
[3dtiles] Update to latest AGI set

### PR DESCRIPTION
**Pull request by gjn**
ping @oterral

### CODE REVIEW

**Comment by gjn** [comment]
[Testlink](https://mf-geoadmin3.int.bgdi.ch/gjn_3dtiles/index.html?lang=de&topic=ech&bgLayer=ch.swisstopo.pixelkarte-grau&layers=ch.swisstopo.swissimage-product,ch.swisstopo.pixelkarte-pk25.metadata&layers_visibility=false,false&lon=6.95455&lat=47.00000&elevation=848&heading=61.471&pitch=-39.999)

**Comment by gjn** [comment]
Not sure it's correct. I see missing buildings here in city of Neuchatel:

https://mf-geoadmin3.int.bgdi.ch/gjn_3dtiles/index.html?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers_visibility=false&layers_timestamp=18641231&lon=6.92475&lat=46.99309&elevation=692&heading=49.908&pitch=-23.680

(compared to old tileset, we have v2 here now, before we had v1).

@davidoesch So this is not demo-worthy, probably.

**Comment by gjn** [comment]
Bridges are disappearing when moving closer:

https://mf-geoadmin3.dev.bgdi.ch/ltjeg/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,&lon=7.44132&lat=46.95551&elevation=703&heading=169.205&pitch=-52.308

**Comment by davidoesch** [comment]
Bridges are appearing and  disappearing:

Load
https://mf-geoadmin3.dev.bgdi.ch/ltjeg/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,&lon=7.44328&lat=46.95359&elevation=764&heading=232.955&pitch=-64.997

 
image


The tilt a few degrees

https://mf-geoadmin3.dev.bgdi.ch/ltjeg/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,&lon=7.44163&lat=46.95272&elevation=815&heading=59.784&pitch=-80.232


bridges appear
image

 

All chrome

**Comment by gjn** [comment]
This doesn't happen with bridgetests data set (current 3ddemo branch)

**Comment by davidoesch** [comment]
Shadow is crap: buildings to dark, no contrast
https://mf-geoadmin3.dev.bgdi.ch/ltjeg/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,&lon=7.46012&lat=46.96969&elevation=690&heading=207.022&pitch=-12.680
image

comapred with 3ddemo branch
https://mf-geoadmin3.int.bgdi.ch/3ddemo/index.html?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,&lon=7.46012&lat=46.96969&elevation=690&heading=207.022&pitch=-12.680

image

**Comment by gjn** [comment]
Same in 3ddemo?

**Comment by davidoesch** [comment]
no 3ddemo is a clear difference between roof and sidewalls

**Comment by gjn** [comment]
frankly, this is starting to be very frustrating. We have absolutely no repeatability of anything.

**Comment by davidoesch** [comment]
only a few buildings are loaded
https://mf-geoadmin3.dev.bgdi.ch/ltjeg/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,&lon=7.46543&lat=46.97229&elevation=1948&heading=212.576&pitch=-39.608

image


in 3dddemo we have more buildings (but even here at this zoomlevel it coudl be more

https://mf-geoadmin3.int.bgdi.ch/3ddemo/index.html?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,&lon=7.46543&lat=46.97229&elevation=1948&heading=212.576&pitch=-39.608

image

**Comment by oterral** [comment]
needs rebase

**Comment by oterral** [comment]
3dtiles branch updated to 20161121

**Comment by davidoesch** [comment]
Hi @oterral ...i still have the same issues I stated above: can you confirm that this is data and not sw related?

**Comment by oterral** [comment]
@davidoesch all buildings are display here: https://mf-geoadmin3.int.bgdi.ch/3dtiles/index.html?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,&lon=7.46543&lat=46.97229&elevation=1948&heading=212.576&pitch=-39.608

**Comment by davidoesch** [comment]
Ok can you @oterral do a quick info mail on The re3 dev mailing list what the current status of 3dtiles 3ddemo branches regarding sw and content  is and when it will be merged in 3ddemo?

**Comment by oterral** [comment]
@davidoesch done. When it will be merged is up to you :)

**Comment by davidoesch** [comment]
See comments in mailing list... I don't think this branch here is OK...

**Comment by davidoesch** [comment]
@gjn  I dont think we need this PR for BETA ?

**Pull request closed without merging**
