### PR TITLE
Cesium update to 1.48

### PR DESCRIPTION
**Pull request by gjn**
Update Cesium from 1.44 to 1.48.

[Testlink with prod backends](https://mf-geoadmin3.int.bgdi.ch/gjn_cesium_update/index.html?wms_url=%2F%2Fwms.geo.admin.ch&wmts_url=%2F%2Fwmts100.geo.admin.ch&terrain_url=%2F%2Fterrain100.geo.admin.ch&vectortiles_url=%2F%2Fvectortiles100.geo.admin.ch&lang=en&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.bazl.luftfahrthindernis,ch.bafu.hydroweb-messstationen_gefahren,ch.swisstopo.swissnames3d&layers_visibility=false,false,true&lon=7.54382&lat=46.66435&elevation=911&heading=360.000&pitch=-40.002)

### CODE REVIEW

**Comment by gjn** [comment]
It doesn't work on Edge as the same error is produces as described in https://github.com/geoadmin/mf-geoadmin3/issues/4358.

The testlink from the ol5_migration i sent out this week was workign in Edge 41, but, but, but, ol5_migration branch is still using Cesium 1.44 (and not 1.48 or newer). So we actually tested only the ol5 version, but not a new cesium version.

This means for the go-live next week, we have to live with Cesium 1.44...

**Comment by davidoesch** [comment]
Ahhh ... This is real PITA. ... And since approx 50% visits is BV internally ( this was the case couple years ago according to moc) we can't just ignore EDGE 41. What about : detecting browser and loading different version of cesium

**Comment by gjn** [comment]
Possible, quite some work. Bad weekend. Maybe I find time next Monday.

**Comment by gjn** [comment]
ok. try now loading 1.44 in Edge < 41. Loading 1.48 in all other browsers. but:

1) some assets (json, js, etc) are mixed (1.44 loads assets from 1.48 - 1.48 should be fine). So Edge 41 might be worst than current prod, please test well.
2) NOT tested on Edge 42
3) NOT tested on Firefox
4) KML is not tested

If we want this on prod, this needs good testing.

**Comment by davidoesch** [comment]
private off the shelf  win10 machine:
EDGE 42 
- HUGE performance compared to current prod: current prod not usable
- kml works : https://mf-chsdi3.int.bgdi.ch/shorten/7d263eaa5b 

FF 61 64bit 
- works: with kml https://mf-chsdi3.int.bgdi.ch/shorten/7d2639e0de 

ALL browsers
- https://mf-chsdi3.int.bgdi.ch/shorten/7d262879df u see names behind the hills (not the case in current prod)
- time stamp layers LFHK is visible even if not active

- when multiple browser windows in 3d are open: GPU fails and warning is issued (3d mode) in chrome ff and EDGE. so we might add a warning: 3d mode: close all other browser windows

conclusio:
- EDGE 42 is a huge improvement imho we need such a fix

next step:
- test according  to https://docs.google.com/spreadsheets/d/14n3JYNL-4ACiqExUeoqqbHmWmqtfq2BB-qC21Beb6Dw/edit#gid=429800091
- fix issues above

**Comment by pauloamado** [comment]
Link tested :
Google Chrome 69 with external wlan : good performance
Microdoft Edge 42 with external wlan : medium-good performance
Microdoft Edge 41 with external wlan : bad performance 
_(worse than 41 with external wlan and current prod version)_

**Comment by Sgachet** [comment]
In general, the different tests succeed but  ... 

Ipad (Safari) with intern wlan : bad performance (sometimes the webpage must be reloaded)
Ipad (Safari) with external wlan : bad/medium performance (worse than the current prod version)
Surface with intern wlan : medium performance

Edge 41 with intern wlan : bad / medium performance

**Comment by danduk82** [comment]
no-go

**Pull request closed without merging**
