### PR TITLE
Restrict the terrain levels to 8-17

### LINKED ISSUE #2832: Permalink issue
The link: https://mf-geoadmin3.dev.bgdi.ch/ltmoc/?dev3d=true&lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege,ch.swisstopo.swissimage-product&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,&lon=6.93164&lat=46.81563&elevation=578&heading=359.997&pitch=-24.987

is transformed in (elevation changed):

https://mf-geoadmin3.dev.bgdi.ch/ltmoc/?dev3d=true&lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege,ch.swisstopo.swissimage-product&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,&lon=6.93164&lat=46.81563&elevation=1579&heading=359.997&pitch=-24.987

Elevation should be the same.

### PR DESCRIPTION
**Pull request by fredj**
Fixes #2832

### CODE REVIEW

**Comment by fredj** [comment]
demo: https://mf-geoadmin3.dev.bgdi.ch/restrict_terrain/?dev3d=true

**Comment by gjn** [comment]
Height is still corrected, but by not as much as before. For me, this is good enough (80/20)

@cedricmoullet @davidoesch ?

**Comment by davidoesch** [comment]
ok for me

**Comment by cedricmoullet** [comment]
+1

2015-11-12 14:21 GMT+01:00 davidoesch <notifications@github.com>:

> ok for me
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/pull/2866#issuecomment-156100991>
> .
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>

**Pull request merged**
