### PR TITLE
Update ol3cesium

### PR DESCRIPTION
**Pull request by loicgasser**
https://github.com/geoadmin/mf-geoadmin3/pull/3361

From this project

```
make ol3cesium
```

This fails with:

`cp: cannot stat `cesium/Build/Cesium/Cesium.js': No such file or directory`

Build appears to work but this file is never created.

I can't get Cesium to build correctly on mf0 (even from a fresh clone of Cesium only)

```
https://github.com/AnalyticalGraphicsInc/cesium.git
cd cesium
npm install
```

Already npm install fails... The second time it passes.

Then use the same commands as in ol3cesium target

```
node_modules/.bin/gulp minifyRelease
node_modules/.bin/gulp generateStubs combine
```

No error but the files don't get created in `Build`.

@gjn can you confirm you observe the same.

### CODE REVIEW

**Comment by gjn** [comment]
Yes, it's because our version of node is not compatible anymore with the version needed to build cesium. I think @oterral worked around this by installing the correct version locally under his account.
@procrastinatio knows also about it.

Can't you re-take what Oli already did on his branch?

**Comment by gjn** [comment]
FYI, I push forced the teo_up branch again (it was overwritten with master). So it should contain original work of @oterral .

**Comment by loicgasser** [comment]
thanks. I am installing it locally to test it and so that I can update ol3cesium in the future.

**Comment by gjn** [comment]
No need to repeat the work oli already did. Let's test what he did.

Upgrading instances should be separate issue. Can't depend on locally installed stuff for our build system.

**Comment by loicgasser** [comment]
Yes I am using what he did

**Comment by loicgasser** [comment]
@mariavkourouni @pfanguin @rfrancel We need a test session for this PR that validates the whole application on most browsers.

Please have a close look at the [open layers release notes for 3.15 and 3.16](https://github.com/openlayers/ol3/releases)

Testing should include:
- Most browsers, especially IE9, IE10, FF and mobile browsers
- Test all drawing features on IE, chrome and FF
- Test all types of layers: wmts, wms internal and external, geojson (hydroweb), treasurehunt, external kmls and their interaction (tooltip)

@pfanguin Could you coordinate the testing effort?

[Test Link](https://mf-geoadmin3.dev.bgdi.ch/gal_up/)

**Comment by pfanguin** [comment]
Yes, I prepare the testing.

**Comment by gjn** [comment]
Thanks @loicgasser !

**Comment by pfanguin** [comment]
@loicgasser : the tooltip of hydrowb layer does not work. Have you a branch in chsdi linked with this branch ?

**Comment by loicgasser** [comment]
I have a geoadmin one. We changed the behaviour won't work until https://github.com/geoadmin/mf-geoadmin3/pull/3364 is merged.

**Comment by rfrancel** [comment]
treasure hunt layer is not displayed in chrome, IE 10 desktop and surface, safari on Ipad. Otherwise, I did not see any problem, apart from the other geojson tooltips mentioned above.

**Comment by mariavkourouni** [comment]
At theme 'Eau':  'Atteintes' and 'Dévelopment à venir' do not work.

**Comment by loicgasser** [comment]
treasure hunt stuff is hidden :dancers:

**Comment by gjn** [comment]
Bug:
[External WMS of canton zürich](https://mf-geoadmin3.dev.bgdi.ch/gal_up/?topic=ech&lang=de&bgLayer=voidLayer&layers=WMS%7C%7CLuftbild_1999%7C%7Chttps:%2F%2Fwww.gis.stadt-zuerich.ch%2Fmaps%2Fservices%2Fwms%2FWMS-ZH-STZH-OGD%2FMapServer%2FWMSServer%7C%7CLuftbild_1999%7C%7C1.3.0&X=247755.00&Y=681980.00&zoom=5) does not work (it's in official wms import dropdown). It's [working](https://mf-geoadmin3.dev.bgdi.ch/?topic=ech&lang=de&bgLayer=voidLayer&layers=WMS%7C%7CLuftbild_1999%7C%7Chttps:%2F%2Fwww.gis.stadt-zuerich.ch%2Fmaps%2Fservices%2Fwms%2FWMS-ZH-STZH-OGD%2FMapServer%2FWMSServer%7C%7CLuftbild_1999%7C%7C1.3.0&X=247755.00&Y=681980.00&zoom=5) on main dev and in prod as well.

I've tested other WMS imports as well (Yverdon and Canton of Grison) and they worked well.

**Comment by procrastinatio** [comment]
WMS Error: `StylesNotDefined">Parameter 'styles' is required.`

**Comment by gjn** [comment]
@mariavkourouni Could you specify technical names and/or provide testlink? Also, link on prod where it works would be great.

**Comment by gjn** [comment]
@mariavkourouni I think those are dev only entries, no? Catalog looks different on prod.

@AFoletti @alcapat @mariokeusen Could you verify to topic 'wasser' and tell if those entries are for dev only?

**Comment by loicgasser** [comment]
Backend error on their server via ogcproxy

https://mf-chsdi3.dev.bgdi.ch/ogcproxy?url=https%3A%2F%2Fwww.gis.stadt-zuerich.ch%2Fmaps%2Fservices%2Fwms%2FWMS-ZH-STZH-OGD%2FMapServer%2FWMSServer%3FSERVICE%3DWMS%26VERSION%3D1.3.0%26REQUEST%3DGetFeatureInfo%26FORMAT%3Dimage%252Fpng%26TRANSPARENT%3Dtrue%26QUERY_LAYERS%3DLuftbild_1999%26LAYERS%3DLuftbild_1999%26INFO_FORMAT%3Dtext%252Fplain%26I%3D50%26J%3D50%26CRS%3DEPSG%253A21781%26STYLES%26WIDTH%3D101%26HEIGHT%3D101%26BBOX%3D667875.0000000001%252C287950%252C733525.0000000001%252C353600

**Comment by gjn** [comment]
But works for others...

**Comment by mariavkourouni** [comment]
@gjn yes, only dev entries

**Comment by gjn** [comment]
I've tested quite heavily in IE11. Except the mentioned points, I didn't find anything. 3D was tested in chrome without anything.

Print should be tested in a little more details - but in general, this looks good.

**Comment by loicgasser** [comment]
I think it comes from https://github.com/openlayers/ol3/commit/27853ea7dd8f4d7416ec9523b5acc2ea7bd43dc4#diff-4e8b936e2e779b01c7ad31bef5e9aa6a

I have a fix but it's more of a hack.

**Comment by loicgasser** [comment]
I think what I just pointed to is actually the fix. we're still with the goog dep.
Upgrading to the commit mentionned above fixes the issue.

Here is what we would add to ol3.

https://github.com/openlayers/ol3/compare/1038b2abea136b029c9d4c2aecaaf4028a9de606...27853ea7dd8f4d7416ec9523b5acc2ea7bd43dc4

I think it makes sense to add it.

**Comment by loicgasser** [comment]
PR update with a few extra commits. I'm closing my fix.

**Comment by loicgasser** [comment]
@AFoletti Can you check the treasure hunt layer. I see it's loaded but I don't find the icons.
[Test Link](https://mf-geoadmin3.dev.bgdi.ch/gal_up/?layers=ch.swisstopo.treasurehunt&topic=ech&lang=fr&bgLayer=ch.swisstopo.pixelkarte-grau&X=177451.93&Y=615981.93&zoom=8)

**Comment by gjn** [comment]
I've tested it on the gal_up branch this afternoon. Was all good.

A treasure can be found on stadium of fc thun.

**Comment by gjn** [comment]
Di d you adapt the ol3 version?

**Comment by loicgasser** [comment]
Yes it fixes the wms bug.

**Comment by loicgasser** [comment]
Thanks everyone for the testing.

**Pull request merged**
