### PR TITLE
Add feedback test

### LINKED ISSUE #2335: [Feedback Tool] doesn't allows to browse/upload files on chrome/firefox
It works without any issue on IE but clicking on the browse button doesn't do anything on chrome/FF AND spartan

### PR DESCRIPTION
**Pull request by ponceta**
Preliminary version, needs to fix #2335 before going further

Test is actually only on IE 10 to avoid too many messages to the webgis mailbox

### CODE REVIEW

**Comment by gjn** [comment]
We should think about avoiding sending the messages to the help desk. Hmm...how?

Can we filter them out before they appear in the inbox? (Remember, soon those emails will have to be treated by the SPOC, which is outside IWI/IKP.

**Comment by ponceta** [comment]
I tried an outlook rule to make these directly moved into a specific folder but I did not manage to get it to the destination folder. We could just delete theses but in this case it's maybe not worth? Who is our outlook server manager? :)

**Comment by cedricmoullet** [comment]
I think that we could avoid to send emails.

**Comment by gjn** [comment]
In light of SPOC, I think it's too cumbersome to send emails with every PR and every test run of jenkins. I'll close this.

**Pull request closed without merging**
