### PR TITLE
Fix state of initial 3D view

### PR DESCRIPTION
**Pull request by gjn**
This fixes https://github.com/geoadmin/mf-geoadmin3/issues/2724

[Testlink](https://mf-geoadmin3.dev.bgdi.ch/gjn_updateol3cesium/?dev3d=true)

### CODE REVIEW

**Comment by gjn** [comment]
@gberaudo Can't say why it doesn't work anymore. I know it worked when I tested with https://github.com/openlayers/ol3-cesium/pull/253, but now in this branch, it doesn't anymore.

I've rebased both ol3-cesium and mf-geoadmin3, so might be that there's a conflict there with the recently merged stuff....

**Comment by gjn** [comment]
I suspect the merging of https://github.com/geoadmin/mf-geoadmin3/pull/2637 might be the culprit.

**Comment by gjn** [comment]
It's working now. The culprit was https://github.com/geoadmin/mf-geoadmin3/pull/2646 :=). Bad coincidence of 2 changes conflicting each other.

@gberaudo @oterral Ready for review/merge.

**Comment by fredj** [comment]
I don't think you need to add the `applyInitialRotation` function.
Can you please test if
```diff
diff --git a/src/js/MainController.js b/src/js/MainController.js
index 7be227b..fdc37cb 100644
--- a/src/js/MainController.js
+++ b/src/js/MainController.js
@@ -99,14 +99,11 @@ goog.require('ga_topic_service');
       globe.baseColor = Cesium.Color.WHITE;
       globe.tileCacheSize = tileCacheSize;
       globe.maximumScreenSpaceError = maximumScreenSpaceError;
-      cesiumViewer.setEnabled(enabled);
       var scene = cesiumViewer.getCesiumScene();
-      scene.camera.setView({
-        pitch: -Cesium.Math.toRadians(50)
-      });
       scene.globe.depthTestAgainstTerrain = true;
       scene.terrainProvider =
           gaLayers.getCesiumTerrainProviderById(gaGlobalOptions.defaultTerrain);
+      enableOl3d(cesiumViewer, enabled);
       return cesiumViewer;
     };
```
works ?

**Comment by gberaudo** [comment]
There are issues when the URL is 3D:

- the tilt should stay unchanged:
https://mf-geoadmin3.dev.bgdi.ch/gjn_updateol3cesium/?dev3d=trueportal,ch.swisstopo.swisstlm3d-wanderwege&topic=ech&lang=en&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,&lon=8.97236&lat=47.00738&elevation=150395&heading=22.328&pitch=-89.990

- with a bigger tilt:
https://mf-geoadmin3.dev.bgdi.ch/gjn_updateol3cesium/?dev3d=trueportal,ch.swisstopo.swisstlm3d-wanderwege&topic=ech&lang=en&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,&lon=8.09642&lat=45.50454&elevation=247606&heading=21.696&pitch=-41.608

**Comment by gjn** [comment]
@fredj Yes, this results in same behaviour.

@gberaudo Will have a look with this. @fredj Any idea about this?

**Comment by gjn** [comment]
There's a conflict between the initial

**Comment by gjn** [comment]
I'm closing the PR as concerned code is part of https://github.com/geoadmin/mf-geoadmin3/pull/2729 as well.

**Pull request closed without merging**
