### PR TITLE
Revert "Update coordinates in tests"

### PR DESCRIPTION
**Pull request by oterral**
Reverts geoadmin/mf-geoadmin3#2943

### CODE REVIEW

**Comment by gjn** [comment]
We have 2 result sets, it seems. Please see https://github.com/geoadmin/service-sphinxsearch/pull/245

**Comment by gjn** [comment]
I think what's currently on master is now correct with the new index as specified in sphinxsearch PR above. So this should fail now. Let's see.

jenkins test

**Comment by oterral** [comment]
Ok thx for the check

**Comment by gjn** [comment]
Note, it's wrong yet again. It will be unstable until tonight. Then I hope we'll have it under control.

**Pull request closed without merging**
