### PR TITLE
Transform string representation of the feature in an object

### LINKED ISSUE #2154: [KML] Print kml fails
Print kml fails on all browsers

Console log:
 
TypeError: Cannot set property '_gx_style' of undefined
    at http://map.geo.admin.ch/1423674319/lib/build.js:1479:310
    at Object.r [as forEach] (http://map.geo.admin.ch/1423674319/lib/build.js:32:302)
    at d.encoders.layers.Vector (http://map.geo.admin.ch/1423674319/lib/build.js:1478:241)
    at w (http://map.geo.admin.ch/1423674319/lib/build.js:1474:194)
    at http://map.geo.admin.ch/1423674319/lib/build.js:1484:40
    at Array.forEach (native)
    at Oa (http://map.geo.admin.ch/1423674319/lib/build.js:301:552)
    at C.l.forEach (http://map.geo.admin.ch/1423674319/lib/build.js:367:485)
    at Object.r [as forEach] (http://map.geo.admin.ch/1423674319/lib/build.js:32:354)
    at k.d.submit (http://map.geo.admin.ch/1423674319/lib/build.js:1483:367)

### PR DESCRIPTION
**Pull request by oterral**
Fix #2154 

[Test](http://mf-geoadmin3.dev.bgdi.ch/teo_fix_print/)
Needs a emergency deploy for this, I think.

### CODE REVIEW

**Comment by cedricmoullet** [comment]
@oterral could you make an emergency deploy today  only with this fix ? Thanks !

**Comment by oterral** [comment]
Yes it is planned

**Comment by ponceta** [comment]
image

This induces circular error on all browsers when printing imported KML

[Testlink01](http://mf-geoadmin3.dev.bgdi.ch/teo_fix_print/?X=147632.74&Y=546288.07&zoom=1&lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=KML%7C%7Chttps:%2F%2Fraw.githubusercontent.com%2Fponceta%2Ftestfiles%2Fmaster%2Fkml%2Ftesting.kml)
Testlink02
Testlink03

**Comment by oterral** [comment]
only KML we draw with draw tool, isn't it?  it could be more difficult to fix. 
I suggest to deploy this fix which fix 99% of the use case. I'll cretae a different issue for that.

**Comment by ponceta** [comment]
OK, we can just add steps to @kandre issue #2154

**Comment by kandre** [comment]
Tested on Chrome, Firefox, an IE11, it works perfectly with KML not coming from our drawing tool.

**Comment by oterral** [comment]
Fix has been deployed on prod https://github.com/geoadmin/mf-geoadmin3/releases/tag/r_150211_1

**Comment by oterral** [comment]
Don't merge I've found a better fix

**Comment by oterral** [comment]
Updated ready to review/merge

**Comment by kandre** [comment]
Very elegant! Tested on Chrome, Firefox and IE11, no bugs found, and print drawn kml works!

**Comment by ponceta** [comment]
Much better :+1: Tested on IE 11 / Moz and Chrome Works fine!

**Pull request merged**
