### PR TITLE
Enlarge popups to avoid slidebar

### PR DESCRIPTION
**Pull request by ponceta**
Greater popups for greater content and less slidebar

Test [HERE](http://mf-geoadmin3.dev.bgdi.ch/ltpoa/)

### CODE REVIEW

**Comment by ponceta** [comment]
Before
image

After
image

**Comment by gjn** [comment]
Impact on mobile?

**Comment by ponceta** [comment]
There are no help popups on mobile.
Actually there is no link to the help from mobile version (which is bad, no?) (or I didn't find it!)

**Comment by ponceta** [comment]
And on very small screens the popups are reduced with slidebar natively. Since we change only the max-height and max-width it will not affect these.

**Comment by gjn** [comment]
This PR changes all popups, not just help popups.

Tooltips and Feedback, I think, are active on mobile (there might be others). Please test them.

**Comment by ponceta** [comment]
Fine on Android, @kandre could you please test feedback and tooltip on IOS?
I'll check on Win Mobile with lumia.

**Comment by kandre** [comment]
I works well on ios iphone 4

**Comment by gjn** [comment]
Very good. Thanks alot for testing and having a 2nd look!

**Comment by ponceta** [comment]
Ty @kandre

**Pull request merged**
