### PR TITLE
Fix PLConfig to have correct topic initialisatoin

### PR DESCRIPTION
**Pull request by gjn**
Fix for https://github.com/geoadmin/mf-geoadmin3/issues/3096
Fix for https://github.com/geoadmin/mf-geoadmin3/issues/3093

Second part of 3096 will come with a data fix.

[Test](https://mf-geoadmin3.dev.bgdi.ch/gjn_plconfigFix/?topic=schneesport)

### CODE REVIEW

**Comment by loicgasser** [comment]
I cannot reproduce the bug with uncompiled code. (Before this PR of course) 

I see that it works but I don't really understand why.

**Comment by oterral** [comment]
LGTM but shouldn't we remove what has been added in https://github.com/geoadmin/mf-geoadmin3/pull/3068/files ?

**Comment by loicgasser** [comment]
what about opacity and timestamps?

**Comment by loicgasser** [comment]
PS I achieve the same result if I remove the usage of the currently useless parameter backgroundLayers from the topic service.

See:
[TestLink](https://mf-geoadmin3.dev.bgdi.ch/gal_bglayers/?topic=schneesport)

Diff:
https://github.com/geoadmin/mf-geoadmin3/compare/gal_bglayers?expand=1


Why not simply get rid of this parameter, remove code instead of adding some?

**Comment by gjn** [comment]
if we remove this parameters, all topics will have the same backgroundlayers as selection. I'm not sure that's currently the case. Should be checked in the db.
Am 29.01.2016 4:46 nachm. schrieb Gasser Loïc <notifications@github.com>:PS I achieve the same result if I remove the usage of the currently useless parameter backgroundLayers from the topic service.

See:
TestLink

Diff:
https://github.com/geoadmin/mf-geoadmin3/compare/gal_bglayers?expand=1

Why not simply get rid of this parameter, remove code instead of adding some?

**Comment by gjn** [comment]
What about them? They are already applied.
Am 29.01.2016 4:26 nachm. schrieb Gasser Loïc <notifications@github.com>:what about opacity and timestamps?

**Comment by gjn** [comment]
No, here we apply active bsckground and layers visibility/opacity/timestamps.
For sure it could be optimized.
Once bod is cleaned up, we can do that.
Am 29.01.2016 4:17 nachm. schrieb oterral <notifications@github.com>:LGTM but shouldn't we remove what has been added in https://github.com/geoadmin/mf-geoadmin3/pull/3068/files ?

**Comment by loicgasser** [comment]
backgroundLayers always has the same 3 layers for all topics.

**Comment by gjn** [comment]
Yes, you are right. I'll remove this parameter next week.

**Comment by oterral** [comment]
@gjn @loicgasser I'm not against removing this config but I think @Jenselme needs it,  see [old PR](https://github.com/geoadmin/mf-geoadmin3/pull/2440#issuecomment-114081017)

**Comment by loicgasser** [comment]
We could maybe define the default backgrounds in the Makefile then instead and inject it in the `index.html` like we do it for a bunch of other things.

**Comment by oterral** [comment]
We could go far and totally remove the request to [https://mf-geoadmin3.dev.bgdi.ch/ioda-net_dndrop/1454319773/services] and statify this in the build process.

**Comment by gjn** [comment]
topics request is part of the ERSI rest standard and we need to support it in api3. But nothing against statifying it here in kf-geoadmin3.
Am 01.02.2016 11:01 vorm. schrieb oterral <notifications@github.com>:We could go far and totally remove the request to [https://mf-geoadmin3.dev.bgdi.ch/ioda-net_dndrop/1454319773/services] and statify this in the build process.

**Comment by oterral** [comment]
@gjn are you sure the definition of topics is an ESRI REST Service ?  

I don't find anything in [doc](http://resources.arcgis.com/en/help/arcgis-rest-api/#/What_s_new_in_the_ArcGIS_REST_API/02r3000000q6000000/) about this.

**Comment by oterral** [comment]
Whatever I merge this PR because it fixes the bug but I think we should use one way (plConfig) or the other (json object) but both  at the same time.

**Comment by AFoletti** [comment]
I just tested with the link provided and I found a bug:
if I open the bgselector in FF, the options are there and they work as defined, but they all display a swissimage thumbnail
This is confirmed in PROD too, by me and by a webgis email.

**Comment by oterral** [comment]
omg thx fo finding this. I fix.

**Comment by Jenselme** [comment]
@gjn @loicgasser @oterral I indeed need the `backgroundLayers` parameter since as explained in the old PR, we don't have the same background layers on all of our topics. I would appreciate that this parameters stays.

But, if you do remove it, please mention me in the PR so that I know it before our next merge and avoid searching why bg selection is broken ;-)

**Comment by gjn** [comment]
@Jenselme We will keep it. Just for you. :)

**Comment by gjn** [comment]
@oterral @loicgasser Next steps after tomorrows deploy is to get rid of all the unneeded columns in the bod regarding topic configuration and put it into the plConfig column.

Regarding ESRI Rest Services API. I think the root of the service point (/rest/services/) is used to give an overview of the available 'maps'. This is from memory. @loicgasser Can you confirm?

**Comment by loicgasser** [comment]
Yes it is defined as the Catalogues Resource (our so called topics). Of course we just kept the principle and gave it our own geoadmon flavour. :D Here is the official doc: http://resources.arcgis.com/en/help/arcgis-rest-api/#/Catalog/02r3000000tn000000/

**Comment by oterral** [comment]
Thanks for the link. But apart the name there is nothing common in the response.

**Comment by loicgasser** [comment]
Indeed, I wouldn't know what to do with all that,

**Comment by Jenselme** [comment]
@gjn Thanks!

**Pull request merged**
