### PR TITLE
Split MapService file

### PR DESCRIPTION
**Pull request by oterral**
[Test](https://mf-geoadmin3.dev.bgdi.ch/teo_mapservice/)

File added:
src/components/map/KmlService.js
src/components/map/OpaqueLayersService.js
src/components/map/PermalinkFeaturesService.js
src/components/map/PermalinkLayersService.js
src/components/map/PreviewFeaturesService.js
src/components/map/PreviewLayersService.js
src/components/map/RealtimeLayersService.js
src/components/map/WmsService.js

Review/merge as soon as possible please

### CODE REVIEW

**Comment by loicgasser** [comment]
Nice :+1:

**Comment by oterral** [comment]
@gjn Can we merge thisa one ? I don't want to rebase ad vitam aeternam :)

**Comment by gjn** [comment]
looking niw

**Comment by gjn** [comment]
I merge it, assuming no functional changes.

**Pull request merged**
