### PR TITLE
Add warning when query results +200

### PR DESCRIPTION
**Pull request by gjn**
This PR addresses https://github.com/geoadmin/mf-geoadmin3/issues/2470

[Testlink](https://mf-geoadmin3.dev.bgdi.ch/gjn_query_warning/?lang=de&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege,ch.bazl.luftfahrthindernis&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,&X=155964.11&Y=634035.89&zoom=1)

@mariokeusen Please test

@oterral Please review. It's should be in master for next deploy.

### CODE REVIEW

**Comment by gjn** [comment]
@mariokeusen Please see alternative here:
https://github.com/geoadmin/mf-geoadmin3/pull/2965

It's a little different, theres' no popup, but tooltip on hover. And coloring is for each layer.

@loicgasser Can you provide a test link for your solution?

Please decide which you want

**Comment by loicgasser** [comment]
Alternative: [Test Link](https://mf-geoadmin3.dev.bgdi.ch/gal_2470/?dev3d=true&lang=fr&topic=aviation&bgLayer=ch.swisstopo.pixelkarte-grau&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege,ch.bazl.luftfahrthindernis,ch.bafu.schutzgebiete-aulav_jagdbanngebiete&layers_visibility=false,false,false,false,true,true&layers_timestamp=18641231,,,,,&X=163061.70&Y=627775.32&zoom=1&catalogNodes=1379,1381,1514&layers_opacity=1,1,1,1,1,0.75)

**Comment by oterral** [comment]
I'm in favor of @loicgasser version, more clear.

**Comment by mariokeusen** [comment]
Thanks for the options. Does all work as expected. For me also the second alternative is favorable. Even better, if we could do it with the red and bold font of the title from version 1? : 
alert_query_font

Like this it's even more obvious for the user....

**Comment by gjn** [comment]
Yes, it's the better solution.

@loicgasser I'll create a PR to your Pr to add the header.

**Pull request closed without merging**
