### PR TITLE
LV95

### PR DESCRIPTION
**Pull request by gjn**
** Do Not Merge Before Tiles On Demand is in Place **

[Testlink](https://mf-geoadmin3.int.bgdi.ch/gjn_lv95/index.html?lang=en&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,&E=2666150.00&N=1188975.00&zoom=2)

Needs https://github.com/geoadmin/mf-chsdi3/pull/2553

- [x] Context Popup
- [x] Map configured for LV95
- [x] Identify requests
- [x] Permalink. Now uses E and N instead of Y and X. Old Permalinks will continue to work.
- [x] WMTS/WMS layers work
- [x] Drawing works
- [x] Query Tool
- [x] Coordinates in search
- [x] Print (see https://github.com/geoadmin/mf-geoadmin3/pull/3982 and https://github.com/geoadmin/service-print/pull/44)
- [x] Height and profile services (see https://github.com/geoadmin/service-alti/pull/26)
- [x] GeoJSON layers
- [x] Search (location and feature search)
- [x] Link with crosshair, permalink in context popup
- [x] Switch to 3D
- [x] Check example WMS/WMTS services for LV95 support
etc...

use:
[Test print](https://mf-geoadmin3.int.bgdi.ch/gjn_lv95/index.html?print_url=//service-print.int.bgdi.ch)`using print_url=//service-print.int.bgdi.ch`
[Test height/profile](https://mf-geoadmin3.int.bgdi.ch/gjn_lv95/index.html?alti_url=//service-alti.int.bgdi.ch) using `alti_url=//service-alti.int.bgdi.ch`

Needs extensive testing

### CODE REVIEW

**Comment by loicgasser** [comment]
ah nice thank you for that.

**Comment by oterral** [comment]
Ready to test

**Comment by oterral** [comment]
search and feature searchb y permalink  fixed.
[test](https://mf-geoadmin3.int.bgdi.ch/gjn_lv95/index.html?ch.bfs.gebaeude_wohnungs_register=400079387_0)

**Comment by gjn** [comment]
I'll rebase this...

**Comment by gjn** [comment]
I've squashed and rebased it on latest master and deployed to int again.

Old commit history is still available on backup branch here: https://github.com/geoadmin/mf-geoadmin3/tree/gjn_lv95_old

**Comment by gjn** [comment]
I've rebased this to master and added some options.

**Comment by procrastinatio** [comment]
You may test **print** and **height/profile** using:

[Test print](https://mf-geoadmin3.int.bgdi.ch/gjn_lv95/index.html?print_url=//service-print.int.bgdi.ch)`using print_url=//service-print.int.bgdi.ch`
[Test height/profile](https://mf-geoadmin3.int.bgdi.ch/gjn_lv95/index.html?alti_url=//service-alti.int.bgdi.ch) using `alti_url=//service-alti.int.bgdi.ch`

**Comment by procrastinatio** [comment]
jenkins test

**Comment by gjn** [comment]
+++1

**Pull request merged**
