### PR TITLE
[WIP] Layer selector 2

### PR DESCRIPTION
**Pull request by oterral**
[test](https://mf-geoadmin3.dev.bgdi.ch/teo_ls_2/?lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&X=190000.00&Y=660000.00&zoom=1)
This PR reflects what we have discuss during the last design session:

Topic definition changes (on CHSDI side) : 
 - A topic has now an array of `activatedLayers`, these layers are added to the map but hidden,
on the contrary the list of  `selectedLayers` which are added to the map but visible.
 - A topic should have a property `activatedLayers` OR a property `selectedLayers` OR neither of the two

Pulldown management changes:
 - When `selectedLayers` property is present in the topic the catalog is shown and the rest is closed.
 - When `activatedLayers` property  is present in the topic the layer manager is shown  and the rest is closed.
 - If a topic has `activatedLayers` and `selectedLayers` the catalog is shown and the rest is closed but this case should not happen.
 - If no `XXXLayers` properties, all is closed.
 - When we open the page, the `widgets` permalink parameter has the priority on the `XXXLayers` properties.

Layer manager changes:
 - The mobile design is used event on desktop (with icon a bit smaller)
 - An `Add more layer` button is added. This button opens, on click, the help "How to search data"

### CODE REVIEW

**Comment by cedricmoullet** [comment]
@oterral Could you configure a topic with some "activated layers" ?
@davidoesch could you test this PR and validate the design ?
I'm not a big fan of the help as "Add more layers". We should at least make a dedicated help page for the layer search.

**Comment by davidoesch** [comment]
need some topic with activated layers

Desisgn

[ ] I dont like the plus. remove the plus icon and add at the end of text the question mark icon  we use on contextual help
[ ] help: how about an animated gif wghich shows the mouse moving to the search field?
[ ] activate the cursor in the search field on click of add layers

**Comment by oterral** [comment]
@cedricmoullet there is the `dev` topic with activated layers : https://mf-geoadmin3.dev.bgdi.ch/teo_ls_2/?topic=dev

**Comment by oterral** [comment]
@davidoesch  @cedricmoullet . Instead of a button "add layer" what do you think if we just display a link with the text " How to add more layers ? "  and on click : 
       -  the search box is focused with a tooltip.
or 
       - a toolitp is displayed near the link, explaining how you user must do.

**Comment by davidoesch** [comment]
+1 for " How to add more layers" since it is  an instruction  and after the user gets it he will not use ist
Layout: same as we had it in the footer at the end of the search result in an earlier version with the phone and twitter logo

for action when clicking on the text, I propose to cover the website semitransparent layer except for the search field (analog to the print modus)

and add a help window analog to http://www.oldmapsonline.org
unbenannt

**Comment by oterral** [comment]
Exactly what I had in mind

**Comment by oterral** [comment]
@davidoesch New [demo](https://mf-geoadmin3.dev.bgdi.ch/teo_ls_2/?lang=fr&topic=dev&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.swisstlm3d-karte-farbe,ch.swisstopo.zeitreihen,ch.swisstopo.swissboundaries3d-kanton-flaeche.fill,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,false&layers_timestamp=,18641231,,) , what do you think ?

**Comment by davidoesch** [comment]
Yes.

for the link text: I suggest to use left align plus the caret symbol, no
underline on mousover and on click . I know the user expects her to open a
tree, but it is tempting to open suth if u look for more


​
for the help text: I suggest to use directly the text of
http://help.geo.admin.ch/?id=31

mobile: what is the behaviour there? in this case the highlight won't work.
here I suggest to link to the help directyl

**Comment by cedricmoullet** [comment]
Very nice. I would also make the "Cherchez vous d'autres données" more
visible.

2015-09-02 17:34 GMT+02:00 davidoesch <notifications@github.com>:

> Yes.
>
> for the link text: I suggest to use left align plus the caret symbol, no
> underline on mousover and on click . I know the user expects her to open a
> tree, but it is tempting to open suth if u look for more
>
>
> ​
> for the help text: I suggest to use directly the text of
> http://help.geo.admin.ch/?id=31
>
> mobile: what is the behaviour there? in this case the highlight won't work.
> here I suggest to link to the help directyl
>
> On Wed, Sep 2, 2015 at 5:10 PM, oterral <notifications@github.com> wrote:
>
> > @davidoesch <https://github.com/davidoesch> New demo
> > <
> https://mf-geoadmin3.dev.bgdi.ch/teo_ls_2/?lang=fr&topic=dev&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.swisstlm3d-karte-farbe,ch.swisstopo.zeitreihen,ch.swisstopo.swissboundaries3d-kanton-flaeche.fill,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,false&layers_timestamp=,18641231,,
> >
> > , what do you think ?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/geoadmin/mf-geoadmin3/pull/2588#issuecomment-137119175>
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/pull/2588#issuecomment-137135443>
> .
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://t.sidekickopen16.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XYgf6M1WN1qfVVMRYFRqW8qlQyH56dByMf1q8vLz02?t=http%3A%2F%2Ftwitter.com%2Fcedricmoullet&si=6057645868318720&pi=1137f48e-e23b-4f74-ae0b-22929e11dbca>

**Comment by davidoesch** [comment]
I would stick to "more data" big and bold as a catalog tree . On mouse over the entry " are you looking for more data?" or even activate directly the hint mask

**Comment by gjn** [comment]
The tooltip for the search is really nice. I like it.

Something that bites me: in the demolink, we now start with the layermanager open, with text 'Maps displayed' and a list of layers...but in fact, those are not the maps that are _not_ displayed :). Might be detail, but might also be confusing. Does the user understand that he has to activate the layer to see it? Maybe we need to adapt the title of the layermanager...

Also, I would put the 'looking for more data' on top on the layermanager. But no problem it being on the bottom either.

**Comment by davidoesch** [comment]
Layer manager title:'Maps displayed'
-> we should rename it to "maps available"

on top: don't agree, since it is less obvious

for the link text: I suggest to use left align plus the caret symbol, no underline on mousover and on click . I know the user expects her to open a tree, but it is tempting to open sth if u look for more
see image below
unnamed

**Comment by oterral** [comment]
-1 for the caret with "more data", I think the question link " Are you looking for more data?"  is more basic user friendly. 

+1 to change the title of layer manager

The text content is the content of http://help.geo.admin.ch/?id=31

On mobile is currently it the same. I just need to close the pulldown menu when the user click on the link. But we could display the help instead. Like you wish.

**Comment by davidoesch** [comment]
A) Text
- adapted msgid in the translation spreadsheet
layers_displayed
help_search_data_link
help_search_data_title

@AFoletti can you do the IT? Grazie

"On mobile is currently it the same. I just need to close the pulldown menu when the user click on the link"
-> ok

**Comment by AFoletti** [comment]
done IT

**Comment by oterral** [comment]
Mobile updated

**Comment by oterral** [comment]
jenkins buil

**Comment by oterral** [comment]
jenkins build

**Comment by oterral** [comment]
jenkins test

**Pull request merged**
