### PR TITLE
Parsing webmercator in search box

### PR DESCRIPTION
**Pull request by procrastinatio**
Bern should be 828064.773289789, 5934093.187456297 Webmercator

<jenkins>[Test link](https://mf-geoadmin3.int.bgdi.ch/mom_webmerc_search/index.html)</jenkins>

### CODE REVIEW

**Comment by loicgasser** [comment]
Is this a change for the test viewer as well?

**Comment by davidoesch** [comment]
> Is this a change for the test viewer as well?

if @loicgasser approves the PR .-..yes

**Comment by procrastinatio** [comment]
@loicgasser I have not the faintest idea what going on

**Comment by oterral** [comment]
Don t we have tests for this damn detection ? @procrastinatio @loicgasser 

-180,-90,180,90 are also valid mercator coordinates.

**Comment by danduk82** [comment]
@boecklic , please check if this is in the testviewer, if not please add this to MVT cleanup stuff

**Comment by boecklic** [comment]
Since this PR is against `master`: should the functionality to search in webmerc coordinates be included in `master` or only in `mvt`?

**Comment by danduk82** [comment]
I think this is meargeable, when the tests will pass

**Comment by boecklic** [comment]
Rebased on `master`

**Pull request merged**
