### PR TITLE
Small css improvements

### PR DESCRIPTION
**Pull request by loicgasser**

### CODE REVIEW

**Comment by oterral** [comment]
Please @loicgasser provide test link

**Comment by loicgasser** [comment]
seems like deploy branch is broken....

**Comment by oterral** [comment]
ah ok so if you have tested it's good for me.

**Comment by loicgasser** [comment]
[Test Link](https://mf-geoadmin3.dev.bgdi.ch/gal_rec_css/?topic=ech&lang=fr&X=187500.00&Y=657550.00&zoom=4&bgLayer=ch.swisstopo.swissimage&layers=ch.swisstopo.digitales-hoehenmodell_25_reliefschattierung)

**Comment by oterral** [comment]
ok it's good

**Pull request merged**
