### PR TITLE
Ioda net background layers promise config

### PR DESCRIPTION
**Pull request by oterral**
Need #1646 to be merged first

[Test](https://mf-geoadmin3.dev.bgdi.ch/ioda-net-background-layers-promise-config?)

### CODE REVIEW

**Comment by oterral** [comment]
@Jenselme can you review pls?

**Comment by oterral** [comment]
jenkins test

**Comment by oterral** [comment]
jenkins test

**Comment by Jenselme** [comment]
I suggested an improvement. Feel free to take or reject it. Appart form that, this works fine, you can merge.

**Comment by oterral** [comment]
PR updated

**Comment by Jenselme** [comment]
@oterral Thanks!

**Pull request merged**
