### PR TITLE
[MVT] showing copyright links for mobile

### PR DESCRIPTION
**Pull request by pakb**
Will fix https://github.com/geoadmin/mf-geoadmin3/issues/4604

<jenkins>[Test link](https://mf-geoadmin4.int.bgdi.ch/mvt_clean_copyright_even_for_mobile/1905060551/index.html)</jenkins>

### CODE REVIEW

**Comment by danduk82** [comment]
in both [tileset.json](https://vectortiles.geo.admin.ch/mbtiles/ch.swisstopo.leichte-basiskarte.vt/v006.json) files, there is an `attribution` field, which can be used. In the [test mapbox viewer](https://vectortiles.geo.admin.ch/gl-styles/ch.swisstopo.leichte-basiskarte.vt/v006/#7/47/8/0/6), this field is used dynamically to aggregate all the various contributors displayed

**Comment by davidoesch** [comment]
Not good....

**Comment by davidoesch** [comment]
3D8AA04F-6C38-4C4F-9D72-55C5CF9AEE7E

**Comment by DerKarlos** [comment]
Cyclic restart in iPad

**Comment by pakb** [comment]
@DerKarlos with the test link on this PR or with test.map.geo.admin.ch?

**Comment by DerKarlos** [comment]
> @DerKarlos with the test link on this PR or with test.map.geo.admin.ch?

Both of them. A view seconds the screen is getting full of dialogs, then iOS „thinks“, the page refresh cycle is to slow and reloads it.

**Comment by pakb** [comment]
@DerKarlos Which model of iPad do you have (model and iOs version if possible)?
Do you run test.map.geo.admin.ch directly from Safari or do you use a third party browser?

We've done tests on iOs 12 on iPhone with Safari, and it worked well. So I'm wondering if you have maybe a different browser / system than the one we tested on.

**Comment by davidoesch** [comment]
And make sure you are flushing local cache

**Comment by DerKarlos** [comment]
I am using an iPad 5. Generation with iOS 12.2
I also could test with an iPhone 6 if you like (after clear cash, showing you page, Safari crashed)

Yes flushing (Verlauf und Websitedaten löschen) avoids using old versions of files.
And it offers the maximal load time :-)

I now only test this test.map.geo.admin.ch 
The iPad Safari did not crash but shows the “Wurde neu geladen, weil ein Problem …”

I will try to send a screenshot before reboot. It looks crowded and the function “auf ihre Startseite”
points to the frame.

Then I also used Firefox and got the same; probably  the same render engine anyway.


You certainly know this:
// To see errors on touch devices, activate this Errorhandler producing alert dialogs
window.onerror = function(msg,url,line){ alert(msg+'\n'+url+'\nLine: '+line); return true; };

**Comment by boecklic** [comment]
Please don't comment on merged PRs (which solve sth unrelated to the issue anyhow.) The iOS issue is known and tracked here: #4924, hints and comments welcome!

**Pull request merged**
