### PR TITLE
Fix heading

### LINKED ISSUE #4154: Orientation failed on new Android
On android 6+

Steps to reproduce:
1) Open map.geo.admin.ch
2) Click on the geoloaction bt twice

Results:
The button has only 2 states, the orientation mode is not detected.

### PR DESCRIPTION
**Pull request by oterral**
Fix #4154 

<jenkins>[Test link](https://mf-geoadmin3.int.bgdi.ch/fix_4154/index.html)</jenkins>

### CODE REVIEW

**Comment by oterral** [comment]
@davidoesch does this PR works for you phone?

**Comment by davidoesch** [comment]
on iphone  yes..droid I'll have to test later

**Comment by davidoesch** [comment]
Nope. Does not work on 4.4.4 Samsung t560 and 7.0 Samsung t580 with native browser and chrome. See https://photos.app.goo.gl/ncL05yPFAtciEB2k1

**Comment by oterral** [comment]
@davidoesch  Don't you have a newer Android? 4.4.4 is dead :)

**Comment by davidoesch** [comment]
7.0 Samsung t580 .. same issue

**Comment by oterral** [comment]
I merge let's see what's happens.

**Pull request merged**
