### PR TITLE
Add print test enhancements

### LINKED ISSUE #2339: [Testing] Add A3 option to the print test
To avoid issues such as #2338 on D-day

### PR DESCRIPTION
**Pull request by ponceta**
Fix #2339 to avoid things like #2338

### CODE REVIEW

**Comment by ponceta** [comment]
jenkins test

**Comment by ponceta** [comment]
jenkins test

**Comment by ponceta** [comment]
jenkins test

**Comment by ponceta** [comment]
jenkins test

**Comment by ponceta** [comment]
jenkins test

**Comment by ponceta** [comment]
jenkins test

**Comment by ponceta** [comment]
jenkins test

**Comment by gjn** [comment]
That's very nice.

**Pull request merged**
