### PR TITLE
Prevent WMS import zoom to extent to go outside the portal

### PR DESCRIPTION
**Pull request by Jenselme**
More or less the same patch that I did for KML.

### CODE REVIEW

**Comment by oterral** [comment]
DO you have an example of WMS ? 

I thought we had fix this with modifying this [line](https://github.com/ioda-net/mf-geoadmin3/blob/prevent-wms-extent-outside-portal/src/components/importwms/ImportWmsDirective.js#L246)

**Comment by Jenselme** [comment]
> I thought we had fix this with modifying this line

I have this line on my code and the problem with imported WMS extent. My problems occurs when I click on the WMS tool. See this screenshot: http://jenselme.perso.centrale-marseille.fr/visible/wms_import_extent.png

> DO you have an example of WMS ? 

In our portal I use http://www.geoservice.apps.be.ch/geoservice/services/a4p/a4p_basiswms_d_fk_s/MapServer/WMSServer? but it works correctly on map.geo.admin.ch since its extent is part of Switzerland. Sadly, I don't have a WMS to reproduce it on map.geo.admin. Maybe a French one ?

**Comment by oterral** [comment]
I think i can test, we have tested with an american wms one time.

What is the projection of your map ? and the extent of this projection? any chance to have temporary link where I can test?

**Comment by oterral** [comment]
If the extent is outside the projection extent, the layer has its property `extent` to undefined and so the zoom button shouldn't appear.

**Comment by Jenselme** [comment]
You can reproduce the behavior on https://map.geojb.ch Import http://www.geoservice.apps.be.ch/geoservice/services/a4p/a4p_basiswms_d_fk_s/MapServer/WMSServer?, layer UP5.

I think that part of the problem is that our portal uses the swiss coordinate (epsg 21781) but is restricted to a region of Swisstzerland. That would explain why extent is not undefined and why I need to use `intersectWithDefaultExtent`. Here are the relevant values:
- epsg = "EPSG:21781"
- epsg_extent = [420000, 30000, 900000, 350000]
- portal extent = [550000, 210000, 620000, 245000]

**Comment by oterral** [comment]
Ok I see but I'll prefer to keep the extent logic in the `getLayerExtentFromGetCap ` function , I think that makes sense if [here](https://github.com/ioda-net/mf-geoadmin3/blob/prevent-wms-extent-outside-portal/src/components/importwms/ImportWmsDirective.js#L244) you replace `proj.getExtent()` by the ` gaGlobalOptions.defautlExtent`  . What do you think ?

**Comment by Jenselme** [comment]
Except that in our case, we exit the function [here](https://github.com/ioda-net/mf-geoadmin3/blob/prevent-wms-extent-outside-portal/src/components/importwms/ImportWmsDirective.js#L231) hence your solution will not work.

**Comment by gjn** [comment]
@oterral What do we do?

**Comment by oterral** [comment]
For our use cases I think it's good.

**Comment by gjn** [comment]
@davidoesch @cedricmoullet We don't have a use case for this, but the fix does make sense if components are used for a subset of Switerzland. It affects external wms layers, but I didn't detect any side effects:

[Testlink](https://mf-geoadmin3.dev.bgdi.ch/iodawms/?topic=ech&lang=en&bgLayer=ch.swisstopo.pixelkarte-farbe&X=261563.38&Y=626273.37&zoom=4&layers=WMS||LANDSAT%201975||http:%2F%2Frips-gdi.lubw.baden-wuerttemberg.de%2Farcgis%2Fservices%2Fwms%2FUIS_0100000017900001%2FMapServer%2FWMSServer||0||1.3.0||true)

It would be good to have it.

**Comment by davidoesch** [comment]
there are 31000 uses cases for this http://www.europeandataportal.eu/data/en/dataset?res_format=WMS 

tested it with our wms .

Can't wait until  we have https://github.com/geoadmin/mf-geoadmin3/pull/2917 in https://github.com/geoadmin/mf-geoadmin3/issues/2414

**Comment by gjn** [comment]
Ok, I didn't found any to reproduce the bug that this PR adresses. Also @Jenselme didn't found any for map.geo.admin.ch (only for their protal, which is not whole of Switzerland)

Would be great to have it reproducable in map.geo.admin.ch...so if you know how, let us know :=)

**Comment by oterral** [comment]
I think reducing the default extent (on Bern for example) then use this wms (http://ogc.heig-vd.ch/mapserver/wms ) in importWMS then use the zoomToExtent button of a layer. The map should not move outside the Bern area.

**Comment by gjn** [comment]
This is good to me. I'll merge it. Thanks alot @Jenselme .

**Pull request merged**
