### PR TITLE
Update ol3

### PR DESCRIPTION
**Pull request by oterral**
https://github.com/openlayers/ol3/commit/480f352cc6b42a20d76ea0acf1abcfd266778c7d

[Test](http://mf-geoadmin3.dev.bgdi.ch/teo_updateol/)

### CODE REVIEW

**Comment by procrastinatio** [comment]
Looks very promising ;-)

**Comment by ponceta** [comment]
Tested on chrome / FF / IE 11 / Android / Surface

No bugs found yet

**Comment by ponceta** [comment]
And IOS on iPad Mini

**Comment by oterral** [comment]
thx @ponceta  for the tests

**Pull request merged**
