### PR TITLE
Open catalog on topic change

### PR DESCRIPTION
**Pull request by loicgasser**
Fix for https://github.com/geoadmin/mf-geoadmin3/issues/3177

[Test link](https://mf-geoadmin3.dev.bgdi.ch/gal_catalog_topic/)

@davidoesch Is that what you want?

UC:
Open Test link
Switch to sachplan

### CODE REVIEW

**Comment by davidoesch** [comment]
perfect! tested with sachplan and schneesport

**Comment by gjn** [comment]
Big improvemen IMO for those kind of topics (almost all!).

A couple of discussion points:

1. When coming from PL with active layers on a topic without pre-defined layers, we open the catalog, and not the active layers. Might also open the layermanager instead.
2. When choosing a layer from a catalog when being in a topic without pre-defined layers, open the layermanager?

Thoughts?

**Comment by davidoesch** [comment]
"When coming from PL with active layers on a topic without pre-defined layers, we open the catalog, and not the active layers. Might also open the layermanager instead."
-> +1 , if the layermanager is empty we open catalog

"When choosing a layer from a catalog when being in a topic without pre-defined layers, open the layermanager?"
-> yes, as it is currently defined in the TEst link above fpr e.g. sachplan

**Comment by gjn** [comment]
@loicgasser Can you address the first point. Otherwise, this is a very good improvement.

**Comment by loicgasser** [comment]
> "When coming from PL with active layers on a topic without pre-defined layers, we open the catalog, and not the active layers. Might also open the layermanager instead."
-> +1 , if the layermanager is empty we open catalog

What I understand from the above.
I guess step to reproduce are:

1. open the following permalink: ?topic=sachplan&lang=en&bgLayer=ch.swisstopo.pixelkarte-grau&X=171191.20&Y=610348.10&zoom=0&catalogNodes=419,1245,420,1654,421,424,426,427,430&layers=ch.bav.sachplan-infrastruktur-schiene_kraft

(no pre-defined layers and one selected layer in the permalink)

Result with this PR:
- catalog is open
- layermanager is closed

Expected Result
- catalog is closed
- layermanger is open


Second use case is:

1. Open the following permalink: ?topic=sachplan&lang=en&bgLayer=ch.swisstopo.pixelkarte-grau&X=171191.20&Y=610348.10&zoom=0&catalogNodes=419,1245,420,1654,421,424,426,427,430&layers=ch.bav.sachplan-infrastruktur-schiene_kraft&layers_visibility=false

(no pre-defined layers and no selected layer in the permalink)


Result with this PR:
- catalog is open
- layermanager is closed

**Comment by gjn** [comment]
Yes.

**Comment by loicgasser** [comment]
ok adapted please test again

**Comment by davidoesch** [comment]
ok
@gjn pls double check

**Comment by gjn** [comment]
Very nice. Thanks alot @loicgasser

**Pull request merged**
