### PR TITLE
Cleaning

### PR DESCRIPTION
**Pull request by oterral**
Remove useless custom export.

Needs to test the print, the offline and tooltip on WMS (external, reprojected  or not)

[Test](//mf-geoadmin3.int.bgdi.ch/teo_clean/index.html)

### CODE REVIEW

**Comment by oterral** [comment]
jenkins test

**Comment by oterral** [comment]
jenkins test

**Comment by procrastinatio** [comment]
- [x] Print
- [x] Offline (needed to update pre-ToD tiles)
- [x] WMS tooltips (didn't find any reprojected WMS tooltips though)

**Comment by oterral** [comment]
jenkins test

**Comment by oterral** [comment]
[Reprojected WMS tooltip](https://mf-geoadmin3.int.bgdi.ch/teo_clean/index.html?lang=fr&topic=ech&bgLayer=voidLayer&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,WMS%7C%7CFlussdeich,%20L%C3%A4ngsdamm,%20Schutzeinrichtung%7C%7Chttp:%2F%2Frips-gdi.lubw.baden-wuerttemberg.de%2Farcgis%2Fservices%2Fwms%2FUIS_0100000004200001%2FMapServer%2FWMSServer%7C%7C0%7C%7C1.3.0%7C%7Ctrue&layers_visibility=false,false,false,true&layers_timestamp=18641231,,,&X=320995.45&Y=626455.11&zoom=9)

**Pull request merged**
