### PR TITLE
Wms layer do not have projection set

### PR DESCRIPTION
**Pull request by procrastinatio**

### CODE REVIEW

**Comment by gjn** [comment]
Most probably a rebase is needed.

**Comment by procrastinatio** [comment]
Where is the rest of my branch?

**Comment by procrastinatio** [comment]
Rebase --> foobar

**Comment by gjn** [comment]
Close?

**Comment by procrastinatio** [comment]
See https://github.com/geoadmin/mf-geoadmin3/pull/3908

**Pull request closed without merging**
