### PR TITLE
Clean gaBrowserSniffer

### PR DESCRIPTION
**Pull request by oterral**
Begin for  #3820

To test:

- Geolocation
- Tooltip 
- Context popup
- Draggable popups
- Swipe
- "Add to home screen" window

[Test](https://mf-geoadmin3.int.bgdi.ch/fix_3820_/index.html)

### CODE REVIEW

**Comment by davidoesch** [comment]
I get a 404 https://mf-geoadmin3.dev.bgdi.ch/fix_3820_/index.html

**Comment by oterral** [comment]
Link fixed

**Comment by oterral** [comment]
It woul be great to have this for the deploy. It will avoid a hudge commit for #3820.

**Comment by davidoesch** [comment]
The add to home screen button does not appear on first load on iPhone

**Comment by oterral** [comment]
I have it on our iPhone

**Comment by davidoesch** [comment]
OK. All the rest works.

**Comment by gjn** [comment]
Good stuff!

I think we need to test this well on all platforms and browsers.  Therefore, I would suggest not to deploy this today.

If you need this as base for the continuation of 3820, I propose to branch off of this branch for that.

**Comment by oterral** [comment]
Squash tests are tehre for that .

**Comment by oterral** [comment]
It's really minor changes only Geolocation behavior has  a bit changed. The rest is only bug fixing on tablet like surface.

**Comment by oterral** [comment]
@gjn I made the changes according to your comment

**Comment by gjn** [comment]
Thanks alot. Very nice code simplification.

**Pull request merged**
