### PR TITLE
geoservices sg added (WMS, WMTS)

### PR DESCRIPTION
**Pull request by AREGSG**
Ressource URL of public Geoservices Kanton St.Gallen added.
Service-Types WMS and WMTS

### CODE REVIEW

**Comment by AREGSG** [comment]
according to email exchange 02./ 03.05.2022

**Comment by pakb** [comment]
Wouldn't it be cleaner to create two capabilities endpoints (`WMTSCapabilities.xml` and `?REQUEST=GetCapabilities` for WMS) to your services? That's a lot of URL to be added

This way you would also be able to add/remove layers to the import tool without having to update our code here.

**Comment by davidoesch** [comment]
hi @AREGSG let us know if you have one master WMS / WMTS with GetCapabilities which could be added . Because : it is then easier for the user to browse in the GUI the tree. The GUI  will display the title abstract etc eg as in http://wms.geo.bs.ch/ 

the current WMS url like "SG00002_WMS" does not give a hint which data is behind and therefore is not findable

We do have Visions like https://github.com/geoadmin/mf-geoadmin3/issues/4668  whcih might become  implemented in the far future


Conclusio: if you don't have a master WMTS WMTS GetCapability: we will go forward with this PR as proposed

**Comment by AREGSG** [comment]
Hi David
We currently do not have a master WMS/WMTS GetCapability available.
Please go ahead with the PR as proposed.
Best regards,
Stefan



Stefan Brühlmann
Geoinformatiker
Kompetenzzentrum GDI

T + 41 58 229 60 03  [skype icon] ***@***.***>
***@***.******@***.***>

Kanton St.Gallen
Bau- und Umweltdepartement
Amt für Raumentwicklung und Geoinformation

Von: David Oesch ***@***.***>
Gesendet: Freitag, 3. Juni 2022 09:31
An: geoadmin/mf-geoadmin3 ***@***.***>
Cc: BUD-AREG Informatik ***@***.***>; Mention ***@***.***>
Betreff: Re: [geoadmin/mf-geoadmin3] geoservices sg added (WMS, WMTS) (PR #5275)


hi @AREGSG<https://github.com/AREGSG> let us know if you have one master WMS / WMTS with GetCapabilities which could be added . Because : it is then easier for the user to browse in the GUI the tree. The GUI will display the title abstract etc eg as in http://wms.geo.bs.ch/

the current WMS url like "SG00002_WMS" does not give a hint which data is behind and therefore is not findable

We do have Visions like #4668<https://github.com/geoadmin/mf-geoadmin3/issues/4668> whcih might become implemented in the far future

Conclusio: if you don't have a master WMTS WMTS GetCapability: we will go forward with this PR as proposed

**Pull request merged**
