### PR TITLE
[3dtiles] Fix draw and deprecated method

### LINKED ISSUE #3577: Remove KML hacks
[Here](https://github.com/geoadmin/mf-geoadmin3/blob/master/src/components/map/KmlService.js#L44) and [here](https://github.com/geoadmin/mf-geoadmin3/blob/master/src/components/map/KmlService.js#L154)

A PR in OpneLayers is needed

### PR DESCRIPTION
**Pull request by oterral**
Due to OL update, [the draw of measures was broken](https://github.com/openlayers/ol3/pull/6027) and [old view animations are deprecated](https://github.com/openlayers/ol3/pull/6079)

and fix #3577 removing KML hacks
also fix https://github.com/geoadmin/mf-geoadmin3/issues/3448

Contains an OL update for  https://github.com/openlayers/ol3/pull/6198

### CODE REVIEW

**Comment by loicgasser** [comment]
jenkins test

**Comment by loicgasser** [comment]
jenkins test

**Comment by loicgasser** [comment]
I will close and re-open for testing purposes sorry for the noise.

**Comment by loicgasser** [comment]
jenkins test

**Comment by loicgasser** [comment]
jenkins test

**Comment by loicgasser** [comment]
jenkins test

**Comment by loicgasser** [comment]
jenkins test

**Comment by oterral** [comment]
jenkins test

**Comment by oterral** [comment]
jenkins test

**Comment by oterral** [comment]
I merge this in 3dtiles. The review could be done with the 3dtiles PR

**Pull request merged**
