### PR TITLE
Use automatic render loop to save resources when idle

### PR DESCRIPTION
**Pull request by gberaudo**
The browser will stop rendering the globe after a few seconds of inactivity like no mouse action and no downloading of tiles.
Test link: https://mf-geoadmin3.dev.bgdi.ch/gberaudo_autorenderloop/?dev3d=true

### CODE REVIEW

**Comment by gberaudo** [comment]
This PR brings in the latest version of Cesium.

Todo:
- [ ] wait for November release of Cesium and rebase.

**Comment by cedricmoullet** [comment]
Test link ?

**Comment by gberaudo** [comment]
Added test link.

**Comment by gberaudo** [comment]
Updated Cesium dependency to include newly released Cesium 1.15.
This PR is ready for review.

**Comment by fredj** [comment]
LGTM

**Comment by fredj** [comment]
OL3_CESIUM_VERSION should be updated (see https://github.com/openlayers/ol3-cesium/pull/279)

**Comment by fredj** [comment]
@gberaudo please cherry-pick https://github.com/geoadmin/mf-geoadmin3/commit/77d538cd4e2efb0ec2a714b86fc7147af1842615

**Comment by fredj** [comment]
`setView` in GaCesium.js must be changed too

**Comment by fredj** [comment]
TODO: fix controls3d icons issue

**Comment by fredj** [comment]
All issues fixed, good to merge.

**Comment by oterral** [comment]
Can you squash please ?

**Comment by fredj** [comment]
@oterral done.

**Comment by oterral** [comment]
Thx

**Comment by gjn** [comment]
Please merge once deploy is done.

**Comment by gberaudo** [comment]
@gjn, what do you mean?

**Comment by loicgasser** [comment]
He meant the deploy of the app to prod. It's done so you should be fine.

**Pull request merged**
