### PR TITLE
changed a topic translation

### PR DESCRIPTION
**Pull request by AFoletti**
Changed the Sachplan topic name as requested by owner
Please merge ASAP

### CODE REVIEW

**Comment by oterral** [comment]
I found this less understandable but if they want that.

**Comment by AFoletti** [comment]
I agree with you and I'm negotiating a change. But thanks for the merge ;)

**Comment by davidoesch** [comment]
This is really bad: no abbreviations should be used. And again: it is not user centered.

**Comment by AFoletti** [comment]
@davidoesch I repeat myself: I agree that's bad.
But, for the Nth time, it's not easy to go to some customer with whichever rule pretending it has to be kept and then a rapid look at the viewer throws your credibility out of the window.
Some topics already HAVE abbreviations. I'm negotiating but, as usual, I'm not in an easy position.

**Comment by davidoesch** [comment]
ther is even an open request  at @beat-github for getting rid off KGS . literally since years

**Comment by AFoletti** [comment]
there are others.
Wildlife areas, historische verkehswege, geothermal energy (ok, that's beta)
But still. I **absolutely** see your point. I hope you see mine

**Pull request merged**
