### PR TITLE
Add current timestamp support 

### PR DESCRIPTION
**Pull request by loicgasser**
Fix for https://github.com/geoadmin/mf-geoadmin3/issues/3253

### CODE REVIEW

**Comment by ltclm** [comment]
this is just replacing ``current`` with ``currentYear`` for the timeslider label, 
the services identify, wmts, wms, etc. will be used with ``current``, right?

**Comment by gjn** [comment]
I think we need to discuss this in group. Let's do this in the afternoon.

**Comment by loicgasser** [comment]
This is only for the timeslider.

**Comment by loicgasser** [comment]
@gjn Can we accept that as temporary solution?

It fixes all our current use cases and apparently the new use cases require more refactoring back and front end.

**Comment by oterral** [comment]
can we have a test link  ?

**Comment by gjn** [comment]
For me it's ok as temporary solution. As disussed in #3253, we need to analyse this in a broader context.

@oterral Good for you?

**Comment by oterral** [comment]
as you want. I can't test.

**Pull request merged**
