### PR TITLE
Remove Array overwrite and more robust code

### PR DESCRIPTION
**Pull request by gjn**
This fixes https://github.com/geoadmin/mf-geoadmin3/issues/2980

### CODE REVIEW

**Comment by oterral** [comment]
There is one more in https://github.com/geoadmin/mf-geoadmin3/blob/master/src/components/StylesFromLiteralsService.js#L121

**Comment by gjn** [comment]
Isn't `this.styles[geomType]` an object, and not an array?

**Comment by oterral** [comment]
yes it's an object.

**Comment by loicgasser** [comment]
LGTM

**Pull request merged**
