### PR TITLE
add wmts canton solothurn

### PR DESCRIPTION
**Pull request by edigonzales**
<jenkins>A test link will be added here if the deploy on int succeeded.</jenkins>

<jenkins>[Test link](https://mf-geoadmin3.int.bgdi.ch/wmts-kanton-solothurn/index.html)</jenkins>

### CODE REVIEW

**Comment by edigonzales** [comment]
I don't get it. Why does the last element of an array need a comma? There was no comma before. Or am I too blind to see?

**Comment by danduk82** [comment]
@edigonzales , the code is OK, but before merging this could you try to optimize a bit your WMTS config? When loading your layers there is a white bounding box around that overrides the basemap...
image

**Comment by edigonzales** [comment]
https://github.com/sogis/docker-mapcache/issues/16

**Comment by davidoesch** [comment]
@andrea - not our problem. Can't be solved. This is the price of wmts
U can merge

**Comment by edigonzales** [comment]
btw: when will the updated url be visible?

**Comment by davidoesch** [comment]
After the deploy - see release notes

**Pull request merged**
