### PR TITLE
[3D] Controls3d icons

### PR DESCRIPTION
**Pull request by fredj**
Demo: https://mf-geoadmin3.dev.bgdi.ch/controls3d_icons/?dev3d=true

### CODE REVIEW

**Comment by davidoesch** [comment]
improvement

- [ ] start with default 45° tilt (as in mf-chmobil3.int.bgdi.ch)
- [ ]  limit tilt range as in (as in mf-chmobil3.int.bgdi.ch)
- [ ]  arrow to rotate and tilt: make them red (as in mf-chmobil3.int.bgdi.ch) if they are in the valid range for tilt, always for rotate
- [ ]  remove the north arrow when in 3d mode in upper left toolset
- [ ] proposal: when cklicking on rotate or tilt icon : reset to north at a 45° view at current position

..and can't wayit for pegman

**Comment by cedricmoullet** [comment]
@oterral could you please review ?

**Comment by cedricmoullet** [comment]
Please rebase

**Comment by fredj** [comment]
rebased

**Comment by cedricmoullet** [comment]
@oterral please review

**Pull request merged**
