### PR TITLE
Fix #3707: Add geometry's properties to the KML exported

### LINKED ISSUE #3707: Add tessellate tag in KML exported in draw
Without this tag the line will not be clamp to ground by cesium

```
<LineString>
    <tessellate>1</tessellate>
```

### PR DESCRIPTION
**Pull request by oterral**
[Export a draw then re import it and go to 3d](https://mf-chsdi3.int.bgdi.ch/shorten/75c6159b07)

### CODE REVIEW

**Comment by gjn** [comment]
A unit test seems to fail.

**Comment by oterral** [comment]
jenkins test

**Comment by oterral** [comment]
nothing to do with this PR .

We need it for the deploy.

**Comment by loicgasser** [comment]
LGTM, tessalate is indeed important.

**Pull request merged**
