### PR TITLE
Hide header, pulldown, copyright and footer until the language is loaded

### PR DESCRIPTION
**Pull request by oterral**
Avoid to see elements from the beginning of loading to the translation end event 

[Test](http://mf-geoadmin3.dev.bgdi.ch/teo_cloak/)

### CODE REVIEW

**Comment by gjn** [comment]
Very nice! On fast connections, this looks great/better.

Should be tested on slow connections, especially mobile. Might get the impression that nothing is loading. Would it be possible to add a loading indicator while the page is cloaked?

**Comment by oterral** [comment]
I think we could add something like a loader or just display the actual loader (the red bar on the top)

**Comment by oterral** [comment]
New version with an application loader only for mobile [test](http://mf-geoadmin3.dev.bgdi.ch/teo_cloak/mobile.html?mobile=true&lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&X=190000.00&Y=660000.00&zoom=1)

**Comment by ponceta** [comment]
Nice! Works great on android 4.1.1.

**Comment by oterral** [comment]
@davidoesch @cedricmoullet @gjn @loicgasser @procrastinatio any opinions for the loader?

**Comment by davidoesch** [comment]
sorry to be here the fun breaker:
- by law the confederation logo shall not be animated (Wappenschutzgesetzt
1933 , no joke)

in general: "a loader " icon si a big step backward... : "this application
is loading...." etc is admintting that sth is slow. please no loading icon.
I'm 100% sure that @cedricmoullet agrees on that (since he always teased me
when i wanted a loading icon  ;-))

the approaach we had no: the top thin red line when loading the app on
mobile was very good...why chnage this behaviour?

**Comment by ponceta** [comment]
Or we could just roll the geoportal logo? ;)

Ok I'm out!

**Comment by oterral** [comment]
On IE11 mobile that was so beautiful :)

I can put the red loading bar instead.

**Comment by davidoesch** [comment]
+11: red loading bar.....

**Comment by oterral** [comment]
Loader removed,  the red bar or spin icon  is displaying when application loading (only on small screen)

Good to review

**Comment by gjn** [comment]
Fantastico.

**Pull request merged**
