### PR TITLE
Fix Cesium warnings

### LINKED ISSUE #4213: Fix warnings before next release of Cesium
WARN: 'loadJson is deprecated and will be removed in Cesium 1.44. Please use Resource.fetchJson instead.'
WARN: 'The options.proxy parameter has been deprecated. Specify options.url as a Resource instance and set the proxy property there.'

### PR DESCRIPTION
**Pull request by oterral**
Fix #4213 

[WMS test](https://mf-geoadmin3.int.bgdi.ch/fix_4213/index.html?lang=fr&topic=ech&bgLayer=voidLayer&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege,WMS%7C%7CGemeindegrenzen%202015%7C%7Chttp:%2F%2Fwms.geo.gr.ch%2Fadmineinteilung%3F%7C%7CGemeindegrenzen_2015%7C%7C1.3.0%7C%7Ctrue,ch.swisstopo.swissnames3d&layers_visibility=false,false,false,false,true,true&layers_timestamp=18641231,,,,,&lon=9.58875&lat=46.20136&elevation=41742&heading=360.000&pitch=-40.412)
[WMTS test](https://mf-geoadmin3.int.bgdi.ch/fix_4213/index.html?lang=fr&topic=ech&bgLayer=voidLayer&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege,ch.swisstopo.swissnames3d,WMTS%7C%7CWorld_Shaded_Relief%7C%7Chttps:%2F%2Fservices.arcgisonline.com%2Farcgis%2Frest%2Fservices%2FWorld_Shaded_Relief%2FMapServer%2FWMTS%2F1.0.0%2FWMTSCapabilities.xml&layers_visibility=false,false,false,false,true,true&layers_timestamp=18641231,,,,,&lon=9.58875&lat=46.20136&elevation=41742&heading=360.000&pitch=-40.412)
[KML test](https://mf-geoadmin3.int.bgdi.ch/fix_4213/index.html?lang=fr&topic=ech&bgLayer=voidLayer&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege,ch.swisstopo.swissnames3d,KML%7C%7Chttps:%2F%2Fservice-proxy.int.bgdi.ch%2Fhttp%2Fwww.bikingspots.ch%252FcreateKMLFile.php%253Ffilename%253Dreno333508077c95ddec.xml%2526fc%253D1&layers_visibility=false,false,false,false,true,true&layers_timestamp=18641231,,,,,&lon=6.68034&lat=46.45100&elevation=7232&heading=0.000&pitch=-40.240)

<jenkins>[Test link](https://mf-geoadmin3.int.bgdi.ch/fix_4213/index.html)</jenkins>

### CODE REVIEW

**Comment by oterral** [comment]
Still need to remove the use of image ion-credit

**Comment by oterral** [comment]
Wait for https://github.com/camptocamp/cesium/pull/52

**Comment by oterral** [comment]
ready to review

**Comment by oterral** [comment]
I haven't this error . @Sgachet can you test please ?

**Comment by Sgachet** [comment]
@oterral Yep I have the same error as Marc (after waiting 2-3 minutes)

**Comment by oterral** [comment]
Same on prod it seems some tile are missing in the bucket. I hop eit will be fixed with the terrain update.

https://terrain100.geo.admin.ch/1.0.0/ch.swisstopo.terrain.3d/default/20160115/4326/12/4302/3110.terrain?v=1.0.0

So not related to this PR

**Pull request merged**
