### PR TITLE
[MVT] Composite renderer (Mapbox layer)

### PR DESCRIPTION
**Pull request by pakb**
<jenkins>A test link will be added here if the deploy on int succeeded.</jenkins>

<jenkins>[Test link](https://mf-geoadmin4.int.bgdi.ch/mvt_clean_mapbox_layer/1905141454/index.html)</jenkins>

### CODE REVIEW

**Comment by davidoesch** [comment]
Holy schmoly .. . Now we are talking performance.

**Comment by pakb** [comment]
And no more diff in style rendering, not bad

**Comment by gjn** [comment]
This looks indeed very good!

**Comment by pakb** [comment]
Layers can be added now, zoom button size have been fixed too. I will start to test all testviewer features and see if it works well.
Please let me know on this PR if you have any feedback

**Comment by pakb** [comment]
I still need to fix zooming buttons (and compas button) position and size

**Comment by pakb** [comment]
We are waiting for a cleaner solution to be merge into Mapbox (that doesn't use private stuff from Mapbox but a public API).
The general feeling of this hybridation will be the same regardless of this improvement.
@davidoesch and @danduk82 : do we want to merge this regardless or do we wait on Mapbox (it can take as long as they see fit) ?

**Comment by davidoesch** [comment]
for test phase of test.map.geo.admin.ch : no need to wait for Mapbox
Therefore : go

**Pull request merged**
