### PR TITLE
Hiking time: fix overlapping in footer

### PR DESCRIPTION
**Pull request by mariavkourouni**
Fix for https://github.com/geoadmin/mf-geoadmin3/issues/3003

[Demo](http://mf-geoadmin3.dev.bgdi.ch/kom_hikingTime/)

### CODE REVIEW

**Comment by gjn** [comment]
oops, needs rebase now.

**Comment by gjn** [comment]
@mariavkourouni I still think the distance between the label and the numbers is too big (in vertical direction).
image

Also, in the PR post (first), please add the issue when you are adressing the issue. And use the 'fix for' prefix, which will autoclose the issue once it's merged.

**Comment by mariavkourouni** [comment]
do you mean too small? Yes, I agree. The svg low boundary is one pixel below the numbers. I can try adjust the diagram height or the svg height and see which option is better.

**Comment by oterral** [comment]
lgtm

**Pull request merged**
