### PR TITLE
add wms Wildruhezonen and Fruchtfolgeflächen

### PR DESCRIPTION
**Pull request by dkottmann**
<jenkins>A test link will be added here if the deploy on int succeeded.</jenkins>
@davidoesch

### CODE REVIEW

**Comment by davidoesch** [comment]
@procrastinatio — Jenkins?

**Comment by pakb** [comment]
Jenkins can't create a testlink from a fork sadly (it wasn't configured to be able to checkout the code from a fork).
Here's a testlink : https://mf-geoadmin3.int.bgdi.ch/ltbtp_dkottmann_patch-8/2002250634/index.html

**Comment by davidoesch** [comment]
Lgtm (even there is only data for TG) https://mf-chsdi3.int.bgdi.ch/shorten/87a649b820

@pakb : Jenkins worked for forks in the past

**Comment by davidoesch** [comment]
@pakb  can u merge it please?

**Pull request merged**
