### PR TITLE
Real official formula of hiking time

### PR DESCRIPTION
**Pull request by mariavkourouni**
[Demo](http://mf-geoadmin3.dev.bgdi.ch/kom_official_hikTime/)

### CODE REVIEW

**Comment by davidoesch** [comment]
Hi all, before putting this on production: we need to have the to do the test as described in the mail to gilbert. Currently the calculated times are in sync with schweizmobil and swiss map online. So: do not put this in production

**Comment by mariavkourouni** [comment]
@gjn @davidoesch  The '-25% to 25%' formula gives the "best" hiking time results (i.e. closer to the wandern.ch hiking times). Have a look at the mail for all the details.

**Comment by procrastinatio** [comment]
I just did check the proposed hiking time with known and other commonly accepted reference time, and these are very slow I find, something like +20% slower.

**Comment by mariavkourouni** [comment]
Yes actually the official formula is 27% slower than the wander.ch hik.times and the "-25% to 25%" formula is 25% slower than the wander.ch hik.times

**Comment by gjn** [comment]
@davidoesch @mariavkourouni So is this the one to use? Can we merge?

**Comment by mariavkourouni** [comment]
@gjn no, this is not the optimal formula in comparison to the wander.ch hiking times.
The optimal formula is the one which now on prod.

**Comment by davidoesch** [comment]
-> we are awaiting feedback and decision from the different stakeholders. the we have to define WHEN we we would do a switch, if at all.

**Comment by davidoesch** [comment]
close this one thsi has to be solved on mmgt Ebene

**Pull request closed without merging**
