### PR TITLE
Log the styles error

### PR DESCRIPTION
**Pull request by oterral**
The alert message is displayed on every rendring frame, it is very annoying. Log the errors is enough

### CODE REVIEW

**Comment by loicgasser** [comment]
yes but not as obvious.
errors could easily go undetected. I agree it's annoying though. The real fix would be to validate the JSON schema validator before allowing pushes.
https://github.com/tdegrunt/jsonschema
Code LGTM

**Comment by oterral** [comment]
The info is only useful for devs not for the user.

**Comment by loicgasser** [comment]
yes

**Comment by oterral** [comment]
Thx for the review

**Pull request merged**
