### PR TITLE
Use the layers config for WMS and allow template url (for subdomain) …

### LINKED ISSUE #4256: Use cached wms-bgdi when imported via import-wms
Now that wms-bgdi is behind a cloudfront, visualization of WMS-based chsdi layers can better take advantage of the cache.

### Please extend the wms-import tool so that it can use the cache too for **wms-bgdi layers**.

This development is vital for the rapidmapping project and should be online no later than 02.05

Thanks!

### PR DESCRIPTION
**Pull request by oterral**
…in WMSs list

Fix #4256

<jenkins>[Test link](https://mf-geoadmin3.int.bgdi.ch/fix_4256/index.html)</jenkins>

### CODE REVIEW

**Comment by oterral** [comment]
It's WIP

**Comment by oterral** [comment]
But it's testable I think .

**Comment by oterral** [comment]
No more WIP.

**Comment by AFoletti** [comment]
[Testlink](https://mf-chsdi3.int.bgdi.ch/shorten/7a65bf2f7a)

**Comment by oterral** [comment]
With the layer visible is better [Test](https://mf-geoadmin3.int.bgdi.ch/fix_4256/index.html?lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&dev3d=true&zoom=5&debug&layers=WMS%7C%7Crapid%20RGB%20NOT%20tiled%7C%7Chttp:%2F%2Fwms{s}.geo.admin.ch%2F%3F%7C%7Cch.swisstopo.rapidmapping.rgb%2F001%7C%7C1.3.0,WMS%7C%7Crapid%20RGB%20tiled%7C%7Chttp:%2F%2Fwms{s}.geo.admin.ch%2F%3F%7C%7Cch.swisstopo.rapidmapping.rgb%2F001%7C%7C1.3.0,WMS%7C%7Crapid%20singleband%20NOT%20tiled%7C%7Chttp:%2F%2Fwms.geo.admin.ch%2F%3F%7C%7Cch.swisstopo.rapidmapping.singleband%2F002%7C%7C1.3.0,WMS%7C%7Crapid%20singleband%20Tiled%7C%7Chttp:%2F%2Fwms{s}.geo.admin.ch%2F%3F%7C%7Cch.swisstopo.rapidmapping.singleband%2F002%7C%7C1.3.0&E=2767319.12&N=1132073.91)

**Comment by ltclm** [comment]
is it possible to increase the tile widht/height to 512 or 1024?

**Comment by oterral** [comment]
currently no. we should extend permalink parameters to do it properly.

**Pull request merged**
