### PR TITLE
Hide timestamp wh real-time layer invisible

### PR DESCRIPTION
**Pull request by loicgasser**
Fix for https://github.com/geoadmin/mf-geoadmin3/issues/3370 + tests

### CODE REVIEW

**Comment by loicgasser** [comment]
Ping @davidoesch , please let me know if you find anything otherwise I'll merge.

[Test Link](https://mf-geoadmin3.dev.bgdi.ch/gal_realtime_timestamp/?topic=ech&lang=fr&bgLayer=ch.swisstopo.pixelkarte-farbe&X=205192.24&Y=645845.31&zoom=3&catalogNodes=752&layers=ch.bafu.hydroweb-messstationen_vorhersage,ch.bafu.hydroweb-messstationen_gefahren)

**Comment by davidoesch** [comment]
tested: ok
(more to come: as we need a realtime time stamp concept for diffferent layers with different time snapshots: as eg in https://mf-chsdi3.dev.bgdi.ch/shorten/6c768d7f6b)

**Comment by loicgasser** [comment]
yes we can brainstorm whenever you want to find a proper solution, which covers both technical and usability aspects. Thank you for testing.

**Comment by davidoesch** [comment]
we will brainstorm when we have realtime meteoschweiz data, 10 min updates with the possibility to go frw and bckw in 10min steps.

**Pull request merged**
