### PR TITLE
[WIP] Add tracking of a KML feature

### PR DESCRIPTION
**Pull request by oterral**
[Follow @cedricmoullet to his new office !!!](https://mf-geoadmin3.int.bgdi.ch/teo_track/index.html?lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=KML%7C%7Chttps:%2F%2Fservice-proxy.int.bgdi.ch%2Fhttps%2Fgithub.com%252Fgeoadmin%252Fmf-geoadmin3%252Ffiles%252F1574905%252Froad-to-zollikofen.txt,ch.swisstopo.swissnames3d&lon=7.44844&lat=46.92883&elevation=739&heading=322.238&pitch=-56.621)

Clikc on the blue line then click 'Track feature' in the tooltip.

[road-to-zollikofen.txt](https://github.com/geoadmin/mf-geoadmin3/files/1574905/road-to-zollikofen.txt)

<jenkins>[Test link](https://mf-geoadmin3.int.bgdi.ch/teo_track/1904300925/index.html)</jenkins>

### CODE REVIEW

**Comment by davidoesch** [comment]
Awesome

**Comment by gjn** [comment]
Doesn't work with my chrome. I get the moc face, but it jitters only and it seems it doesn't advance. Zooms in very close.

**Comment by oterral** [comment]
you need to zoom out to see him correctly

**Comment by oterral** [comment]
It's not efficient also because I need to get the height from the service-alti for each coordinate.

**Comment by davidoesch** [comment]
works on desktop only (and you cant use the controls..but I still do like it...)

**Comment by gjn** [comment]
Ok, now I see it.

Any way to use the profile service to get the heights? As those are points on the kml, you could get them in advance in bulk using profile (maybe every 100 meters one profile request or something like that)

**Comment by oterral** [comment]
I caclulate a coordinate every 10 meters  along the line for example ([see](https://github.com/geoadmin/mf-geoadmin3/pull/4092/files#diff-890243f9e84eb338305d7c34b6038487R48)).

I should  be able to calculate a bunch of coordinates  and send it to the height service.

**Comment by gjn** [comment]
You could get them in bunches using [gaProfile](https://github.com/geoadmin/mf-geoadmin3/blob/582b2e1d01cd868f3cd487135cb3c75338acfcfd/src/components/profile/ProfileService.js)

**Comment by danduk82** [comment]
@davidoesch , funny feature, shall we re-priorise this kind of things or is it dead?

**Comment by davidoesch** [comment]
A NTH but killer feature: imagine the tooltip of a feature in 2d (like hiking or biking line/polygon) has a besides link to object as well a link" fly along in 3D“
Therefore:  upvote

**Comment by procrastinatio** [comment]
Don't work anymore?

**Pull request closed without merging**
