### PR TITLE
Add new test with wordforms

### PR DESCRIPTION
**Pull request by alcapat**
rte berne -> route de berne

### CODE REVIEW

**Comment by gjn** [comment]
Why remove an existing test?

**Comment by alcapat** [comment]
@gjn sorry it's a mistake. i only want to add a new test, not replace. i will correct that soon

**Comment by gjn** [comment]
I think you can add it in the same file, same function. Just start load a new url with `driver.get`, it's like typing a new address in the address bar.

The first test is useful I think. It checks if a click on the search result does indeed navigate to the selected point.

**Comment by alcapat** [comment]
@gjn it's done.

**Comment by gjn** [comment]
Very nice. Thanks alot.

**Comment by alcapat** [comment]
@gjn i don't know if we need test other wordforms and/or in other language ?

**Comment by gjn** [comment]
As it's run only in one browser, it might make sense to add more. But it's also not a top feature of map.geo...I'll let you decide

All wordforms: https://github.com/geoadmin/service-sphinxsearch/blob/master/conf/wordforms_main.txt

**Pull request merged**
