### PR TITLE
Update translation

### PR DESCRIPTION
**Pull request by pakb**
remove ISOS topic, and edit text for corsshair and 3D disclaimer

[Test link](https://mf-geoadmin3.int.bgdi.ch/BGDIINF_SB-1828_update_translation/2106291131/index.html)

### CODE REVIEW

**Comment by boecklic** [comment]
@davidoesch @consta-v please review/verify

**Comment by davidoesch** [comment]
3d: ok
"share Position": ok
ISOS: not ok @rebert @mariokeusen :pls revert the ISOS Topic Name with @pakb

**Review by consta-v — CHANGES_REQUESTED** [review]
The translation of the ISOS topic doesn't work any more.

**Comment by pakb** [comment]
@consta-v Test link updated, could you give it another look?

**Comment by ltclm** [comment]
@davidoesch @consta-v
we need a review of this so that we can continue the deploy!

**Review by consta-v — APPROVED** [review]
It looks good to me now for ISOS.

**Pull request merged**
