### PR TITLE
3d keyboard controls

### LINKED ISSUE #2938: 3d keyboard navigation
- +/- : zoom in / zoom out center
- left/right: move camera left / right
- Up/down: move camera up / down
- Shift left/right: rotate
- Shift up/down: pitch

### PR DESCRIPTION
**Pull request by fredj**
fixes #2938 

preview: https://mf-geoadmin3.dev.bgdi.ch/3d_keyboard_controls/?dev3d=true

### CODE REVIEW

**Comment by fredj** [comment]
@cedricmoullet , @davidoesch Can you please test the demo and tell me if it's what you expect?

**Comment by davidoesch** [comment]
Nice one

-[ ] Shift down: pitch : if you go with shift up arrow to the top , somteimes the shift don does not work anymore

-[ ]  +/- : zoom in / zoom out center doe snot work on chrome

**Comment by oterral** [comment]
Does the directions shoudln't be reversed right arrow -> rotate to left,left arrow -> rotate to right ? same for tilt.

**Comment by davidoesch** [comment]
no imho  it is correct

**Comment by cedricmoullet** [comment]
I think we should make this exactly like google maps

**Comment by davidoesch** [comment]
+1 for like google maps

**Comment by fredj** [comment]
To make exactly like google maps:
 - [ ] remove the shift up/down to pitch
 - [ ] remove the shift left/right to rotate
 - [ ] if pitch is "low" (look at the ground) left/right pan the map
 - [ ] if pitch is "high" (look at the horizon)  left/right rotate the map

**Comment by fredj** [comment]
> +1 for like google maps

demo updated, please test:  https://mf-geoadmin3.dev.bgdi.ch/3d_keyboard_controls/?dev3d=true

Note: the change between the pan or rotate it at -30deg but can easily be changed

**Comment by cedricmoullet** [comment]
@oterral can you review and merge if it's fine ?

**Comment by cedricmoullet** [comment]
@pfanguin can you describe in the help the usage of the keyboard ?

**Comment by davidoesch** [comment]
SORRY - the SHIFT+ keyboard  function was usdefull, after testing for a while
 I know SHIFT is not used in gmaps but in gearth. 
so

**Pull request merged**
