### PR TITLE
Update ol3cesium, ol and cesium

### PR DESCRIPTION
**Pull request by oterral**
[Test](https://mf-geoadmin3.int.bgdi.ch/teo_up/index.html)

The KML is still a mess.

### CODE REVIEW

**Comment by oterral** [comment]
@gjn @loicgasser review please

**Comment by oterral** [comment]
I'll merge it tomorrow morning.

**Comment by loicgasser** [comment]
https://github.com/geoadmin/mf-geoadmin3/pull/3570/commits/d7a172843e9cf85a3a7d1074f209cbf03e2ebd3c

Can you put ol3 reference, what broke it?

**Comment by oterral** [comment]
Refs added

**Pull request merged**
