### PR TITLE
More compact measure tool, more space for profile

### PR DESCRIPTION
**Pull request by loicgasser**
No functional change. Not tested on IE.

[Test Link] (http://mf-geoadmin3.dev.bgdi.ch/gal_profile_style/)

*Before*:
profile_1_before
profile_2_before

*After*:
profile_1_after
profile_2_after

### CODE REVIEW

**Comment by oterral** [comment]
Can't we let  buttons on the right but reduce the popup height to 200px ?

**Comment by loicgasser** [comment]
I tested that as well looks really small... But yes I can provide an alternative PR and we can choose what seems to be the best approach. We could also reduce the buttons size. Seems really big.

**Comment by loicgasser** [comment]
Or align btns horizontally.

**Comment by loicgasser** [comment]
@oterral I changed it to 280px, I think we can go down to 230-240px if we align btns horizontally and make them a little smaller. I think we should leave as much space as possible on the right to display the profile.

**Comment by oterral** [comment]
Yes button horizontally could be good.

**Comment by loicgasser** [comment]
Updated, it is much less invasive.
@davidoesch what about download icon with the save btn. http://fortawesome.github.io/Font-Awesome/3.2.1/icon/download/

I saw that people thought they were saving the state of the measure during user tests. Or simply change the text.

**Comment by oterral** [comment]
What about hiding the display profile button when there is no profile (or no line drawn)?

**Comment by oterral** [comment]
It's nice with horizontal button. There is just a font problem for the save button.

**Comment by davidoesch** [comment]
icon : nope - we have to be consistent- either we use icons everywhere or nowhere.
therefore : changing the text from sauvgarde to export might make sense

**Comment by loicgasser** [comment]
I like the idea of not displaying the show profile btn when there is no line drawn.
I even prefer the idea of using the drawing line/polygon (from drawing tool) if already here.
@davidoesch ?

I'll change the text.

**Comment by gjn** [comment]
Or maybe even removing the profile button altogether and just draw the profile when there's a line?

(Yeah, I like removing stuff)

**Comment by davidoesch** [comment]
- not displaying the show profile btn when there is no line drawn. see
https://github.com/geoadmin/mf-geoadmin3/issues/1912
-"Or maybe even removing the profile butto just draw the profile when
there's a line " +1

**Comment by kandre** [comment]
Really nice ! Tested on IE11 and IE9, works great

**Comment by gjn** [comment]
jenkins test

**Comment by loicgasser** [comment]
rebased, I implemented the display/hide profile button as discussed above.
Translations changes should be done in a separate PR as these have an impact beyond the profile tool and might require other changes.

**Comment by oterral** [comment]
@loicgasser the button should appear when you create the 2nd point, not when you move the mouse after the first point.

**Comment by davidoesch** [comment]
otherwise- nice one!

**Comment by gjn** [comment]
LGTM.

@loicgasser Can you adapt to latest request?

**Comment by loicgasser** [comment]
ok do it now

**Comment by loicgasser** [comment]
ok adapted on second point.

**Comment by gjn** [comment]
@oterral Please merge before/after the deploy. You decide.

**Comment by oterral** [comment]
I will do after the deploy

**Comment by oterral** [comment]
thx for this @loicgasser

**Pull request merged**
