### PR TITLE
Display measure tooltips well-positioned in 3d

### LINKED ISSUE #2783: Overlays are not well positionned
Measure overlays .

### PR DESCRIPTION
**Pull request by oterral**
[Test](https://mf-geoadmin3.dev.bgdi.ch/teo_overlays3d/?lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&dev3d=true&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege,KML%7C%7Chttps:%2F%2Fpublic.dev.bgdi.ch%2FcfG9RDtiR7W54Kg7RWwotA&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,&lon=7.25159&lat=46.62316&elevation=12260&heading=328.830&pitch=-43.380)

Fix #2783

Works only for polygon because lines are under the terrain.

### CODE REVIEW

**Comment by oterral** [comment]
Any opinions @davidoesch @cedricmoullet ? 

I can make antoher PR hiding the overlay in 3d if you prefer.

**Comment by davidoesch** [comment]
the curretn reault is a no go

- no clamping to ground paramter in 3D?

either we show all types correctly or we don't show KML at all

**Comment by oterral** [comment]
This PR is about only the measurment tooltips. Not Geometry.

**Comment by davidoesch** [comment]
measurement tooltips: they are ok

**Comment by gjn** [comment]
It does not seem to work in prd mode. There's an error in the console that ol.proj.toLonLat is not a function (Maybe it's missing in the exports).

**Comment by oterral** [comment]
Yes that's why it was in WIP . Forget to  update ol.

**Comment by oterral** [comment]
PR and testlink Updated

**Pull request closed without merging**
