### PR TITLE
[WIP] Web mercator

### PR DESCRIPTION
**Pull request by oterral**
<jenkins>A test link will be added here if the deploy on int succeeded.</jenkins>

<jenkins>[Test link](https://mf-geoadmin3.int.bgdi.ch/teo_wm/index.html)</jenkins>

### CODE REVIEW

**Comment by davidoesch** [comment]
Performance on mobile not that bad :-)

**Comment by davidoesch** [comment]
Keep this on Dev ... We need first a clear go from BL, GL, Tag-gkg,Gkg ( and I'm sure I forgot already one or two gremium)

**Comment by oterral** [comment]
@davidoesch I guess you want this change in thi PR https://github.com/geoadmin/mf-geoadmin3/pull/4272

**Comment by oterral** [comment]
I've added the measurement using the wgs 84 sphere , [see](https://mf-geoadmin3.int.bgdi.ch/teo_wm/index.html?lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&dev3d=true&zoom=15&debug&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege,KML%7C%7Chttps:%2F%2Fpublic.int.bgdi.ch%2Fg1PLG6BASWSIYfp1GZEcMQ&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,&E=895902.29&N=5918703.98)

**Comment by davidoesch** [comment]
OMG!

You mean: Measure draw is fixed?

the 100m track in Lugano is now a 100m track --please confirm @gjn 

grafik

**Comment by oterral** [comment]
It's less precise I think but works

**Comment by davidoesch** [comment]
Define: Precision

**Comment by gjn** [comment]
It's on the WGS84 ellipsoid, I guess.

I think more precise and correct would be to transform coordinates to LV95 (using ol transformation functions, which is already used correctly in the mouse-position indication in the footer) and then calculate the distances/areas. This could be done quite fast.

But this is good enough for demo purposes. Same would need to be done for area calculations.

**Comment by davidoesch** [comment]
uh azimuth is not yet correct
150°  in webmercator viewer https://mf-chs150°  in webmercator viewer https://mf-chsdi3.int.bgdi.ch/shorten/7a8df97e22



350° in LV03 viewer https://s.geo.admin.ch/7a8dfc1fb9

**Comment by oterral** [comment]
Yes the transformation to swiss coordinates is a good idea. That simplify the code also

**Comment by procrastinatio** [comment]
To check for distortion: [link](https://mf-chsdi3.int.bgdi.ch/mom_merc/shorten/7a8edec146)

**Comment by davidoesch** [comment]
ETA for the azimut error mentioned above?

**Comment by oterral** [comment]
I will check

**Comment by davidoesch** [comment]
works now

**Pull request closed without merging**
