### PR TITLE
Fix offline

### LINKED ISSUE #2192: [Offline] Tiles are not displayed
Cached background tiles now need a page refresh to be displayed.

### PR DESCRIPTION
**Pull request by oterral**
This PR includes:
    - fix  #2192  : offline regression caused by the ol3 update.
    - fix the detection of network status change

[Test](http://mf-geoadmin3.dev.bgdi.ch/teo_fix_offline/)

### CODE REVIEW

**Comment by cedricmoullet** [comment]
emergency deploy ?


On Wed, Mar 4, 2015 at 2:59 PM, oterral <notifications@github.com> wrote:

> This PR includes:
> - fix #2192 <https://github.com/geoadmin/mf-geoadmin3/issues/2192> :
> offline regression caused by the ol3 update.
> - fix the detection of network status change
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/geoadmin/mf-geoadmin3/pull/2193
> Commit Summary
>
>    - Use a checker debounced on http service response errors
>    - Fix #2192 : According to ol3 setMinResolution doesn't allow
>    undefined value anymore
>
> File Changes
>
>    - *M* src/components/NetworkStatusService.js
>    <https://github.com/geoadmin/mf-geoadmin3/pull/2193/files#diff-0> (10)
>    - *M* src/components/offline/OfflineService.js
>    <https://github.com/geoadmin/mf-geoadmin3/pull/2193/files#diff-1> (2)
>
> Patch Links:
>
>    - https://github.com/geoadmin/mf-geoadmin3/pull/2193.patch
>    - https://github.com/geoadmin/mf-geoadmin3/pull/2193.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/pull/2193>.
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>

**Comment by oterral** [comment]
+1

**Comment by oterral** [comment]
Deployed

**Comment by oterral** [comment]
I selfmerge because it's already on prod

**Pull request merged**
