### PR TITLE
No-Info box shown only when cursor was pointer

### PR DESCRIPTION
**Pull request by gjn**
This is a fix for https://github.com/geoadmin/mf-geoadmin3/issues/3120 and as discussed.

[Testlink](https://mf-geoadmin3.dev.bgdi.ch/gjn_ni/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege,ch.are.gueteklassen_oev,ch.bav.haltestellen-oev&layers_visibility=false,false,false,false,true,true&layers_timestamp=18641231,,,,,&X=129038.02&Y=609270.67&zoom=6&layers_opacity=1,1,1,1,0.75,1)

### CODE REVIEW

**Comment by gjn** [comment]
ping @davidoesch and  @oterral

**Comment by davidoesch** [comment]
mobile: ok 
desktop: as intermediate workaround ok ( the "hand" still appears for areas with a tooltip and no info is shown)
unbennant

**Comment by oterral** [comment]
lgtm

**Comment by gjn** [comment]
yes, we still have this and we will have this until we have pixel-detected cursor change.

I would vote to remove the hand altogether...

**Comment by davidoesch** [comment]
Remove the Hand

**Pull request merged**
