### PR TITLE
Transform automatically geojson data to the map's projection

### LINKED ISSUE #3921: GeoJSON in map.geo and LV95
All creatoes need to create lv95 _and_ lv03.

### PR DESCRIPTION
**Pull request by oterral**
Fix #3921 

[Test](https://mf-geoadmin3.int.bgdi.ch/teo_geojson/index.html?lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&dev3d=true&zoom=1&debug&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege,ch.bfe.bikesharing&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,&E=600709.24&N=198927.30&X=208613.60&Y=676077.51)

### CODE REVIEW

**Comment by loicgasser** [comment]
I see that this work in progress, but please consider that hydroweb layers don't specify the projection in their geojson at the moment. So if the projection is not defined, we should try to guess, what it is as I am not sure they will adapt it in time for our go live.

See for instance:
https://data.geo.admin.ch/ch.bafu.hydroweb-messstationen_gefahren/ch.bafu.hydroweb-messstationen_gefahren_fr.json

@mariokeusen Is it possible to tell them to specify the crs in their geojson to make sure they will be compatible with LV95 ?

```json
"crs":{"type":"name","properties":{"name":"EPSG:21781"}}
````

That is the entry they need to add to be LV95 compatible.

**Comment by oterral** [comment]
:weary:

**Comment by oterral** [comment]
@mariokeusen @AFoletti can you see with them if we can add the projection in the their file?

**Comment by AFoletti** [comment]
Will do

**Comment by AFoletti** [comment]
can you please specify at which level of the json must the crs be specified?

**Comment by oterral** [comment]
```
{
  "name":"ch.bfe.bikesharing",
  "type":"FeatureCollection",
  "crs": {
       "type":"name",
       "properties":{
             "name":"EPSG:21781"
        }
   },
  "features":[
```

**Comment by mariokeusen** [comment]
Will try to get this change done by bafu/liip. 
@loicgasser : are you sure it is "EPSG:21781" (code for LV03)? According to [1] the code for LV95 is "EPSG:2056"

[1] https://epsg.io/2056

**Comment by oterral** [comment]
@mariokeusen ye lv95 is epsg:2056 but whatever they choose the system they want. The repojection will be done automatically if needed.

**Comment by mariokeusen** [comment]
Ah, ok so it's the data source's crs to be defined in the geojson, right?

**Comment by loicgasser** [comment]
Yes

**Comment by mariokeusen** [comment]
ok, requested that @bafu

**Comment by AFoletti** [comment]
BFE and BAKOM geoJSON looks already OK to me

**Comment by mariokeusen** [comment]
waiting for an answer from liip, if they can do this change till end Oct.
@oterral @loicgasser : when liip makes that change and json files come _with_ that crs information: will this change have an impact on the 10 min data updates in chsdi?

**Comment by loicgasser** [comment]
no impact. this will be used only when we migrate to LV95

**Comment by mariokeusen** [comment]
Confirmed by bafu and liip: they'll add the crs definition to the json files before Nov 1st. I'll get a message as soon as it's done.

**Comment by oterral** [comment]
I merge this in the lv95 which will be deploy le 1st november.

**Pull request merged**
