### PR TITLE
[WIP] Using topic groups and horizontal scrolling bar

### PR DESCRIPTION
**Pull request by loicgasser**
Fix for https://github.com/geoadmin/mf-geoadmin3/issues/3157

Not being able to use flex because of IE9 is not fun. @oterral knows what I am talking about.

Here is a [Test Link](https://mf-geoadmin3.int.bgdi.ch/gal_topic_groups/index.html?api_url=%2F%2Fmf-chsdi3.dev.bgdi.ch%2Fgal_topic_groups&lang=en)

This PR introduces the concepts of topics group, e.g. groups appear on the same line.
It is generic enough that we can create as many topic group as we want without changing the code.

This PR works with
https://github.com/geoadmin/mf-chsdi3/pull/2311

Before merging:

1. Add all missing single topics
2. Add all images and translations
3. Update `bod_master` with migration script
4.  Remove https://github.com/geoadmin/mf-chsdi3/commit/9db0dd58da8bca36ddfbb0ba436a9f540c25af35
5. Merge https://github.com/geoadmin/mf-chsdi3/pull/2311
6. Merge this PR

### CODE REVIEW

**Comment by davidoesch** [comment]
in #3157  we prpose three lines (can you add the singel topics as well?
add some responsiveness, eg on large screens it fits the width of the screens

**Comment by loicgasser** [comment]
See my comment in the issue

**Comment by loicgasser** [comment]
we can do tree, but it's not because you call them single topic that they are indeed a topic

**Comment by loicgasser** [comment]
There single topic for admin_boundaries:

[Test Link](https://mf-geoadmin3.int.bgdi.ch/gal_topic_groups/index.html?api_url=%2F%2Fmf-chsdi3.dev.bgdi.ch%2Fgal_topic_groups&topic=admin_boundaries)

If you have a preference for the order of the single topics it is time.

**Comment by davidoesch** [comment]
This is what we want !
-> lets discuss tomorrow 1:1 of the implications /costs are to operate this

we have list of all thos topics here
https://docs.google.com/spreadsheets/d/11zjWdLgaCZWiFhB8kP2AWhOb9vKBqLuXeXDPTSd4rDk/edit

**Comment by loicgasser** [comment]
only 28 more to go :laughing:

**Comment by loicgasser** [comment]
jenkins test

**Comment by loicgasser** [comment]
We could/should use 4 lines.

**Comment by loicgasser** [comment]
saucelabs tests are failing because it's taking the wrong backend.

**Comment by davidoesch** [comment]
the 3 lines are based on the fact we three types of topics...
and for the 28 remaining: this is one for the interns

**Comment by loicgasser** [comment]
Final decision: use modal and no single topics.

**Pull request closed without merging**
