### PR TITLE
Use custom proj4js file.

### PR DESCRIPTION
**Pull request by gjn**
This reduces the size of the proj4js file from 72KB to 30KB and thus saves 42KB from the build.js file.

Created with "grunt build:somerc,utm,longlat" (from https://github.com/proj4js/proj4js)

### CODE REVIEW

**Comment by cedricmoullet** [comment]
nice !

**Comment by gjn** [comment]
No we need to tackle custom ol3 build (ol3 is 450KB, almost half the size of build.js)

**Comment by ponceta** [comment]
Nice!

**Comment by oterral** [comment]
Very nice!!!


Any possibility to have a  make target to build it automatically?

**Comment by gjn** [comment]
Only when you save another 40KB by having an ol3 custom build. Deal?

;=)

**Comment by oterral** [comment]
challenge accepted!!!

**Comment by gjn** [comment]
jenkins test

**Comment by gjn** [comment]
jenkins test

**Comment by gjn** [comment]
jenkins test

**Comment by gjn** [comment]
jenkins test

**Comment by gjn** [comment]
jenkins test

**Comment by gjn** [comment]
jenkins test

**Comment by oterral** [comment]
thx for this

**Pull request merged**
