### PR TITLE
Add a padding to the camera position based on the camera height

### LINKED ISSUE #2827: Take the altitude into account when limiting the camera position
To be able to view the whole country at maximum altitude

### PR DESCRIPTION
**Pull request by fredj**
Fixes #2827
link: https://mf-geoadmin3.dev.bgdi.ch/camera_limit_padding/?dev3d=true

### CODE REVIEW

**Comment by gberaudo** [comment]
LGTM

**Comment by fredj** [comment]
Please tell me if the padding value is enough

**Comment by gjn** [comment]
Very nice improvement. Please merge when you're happy with it.

**Comment by fredj** [comment]
Thanks for the review

**Pull request merged**
