### PR TITLE
Update ImportController.js

### PR DESCRIPTION
**Pull request by dkottmann**
@davidoesch

<jenkins>A test link will be added here if the deploy on int succeeded.</jenkins>

### CODE REVIEW

**Comment by davidoesch** [comment]
LGTM 
@procastrinatio ... Jenkins is not happy

**Comment by pakb** [comment]
I'll merge this, I can sadly not give any testlink as our CI isn't able to get the source code from a forked repo for the time being (I'll try to improve that)

**Comment by davidoesch** [comment]
This worked before?

**Comment by pakb** [comment]
it's now on int : https://mf-geoadmin3.int.bgdi.ch

It might have worked before, it's a use case I've not been faced with since I'm here. I have done a couple changes to how Jenkins handle project mf-geoadmin3 these past few weeks so it might have broken this specific use case.

**Comment by davidoesch** [comment]
Lgtm (ask Marc ...he merged those sorts of PR in the past)

**Pull request merged**
