### PR TITLE
[WIP] Download kml from public

### PR DESCRIPTION
**Pull request by gjn**
Possible solution for https://github.com/geoadmin/mf-geoadmin3/issues/3441

Not tested, no testlink. Just showing approach as discussed in the issue.

@oterral @loicgasser

### CODE REVIEW

**Comment by oterral** [comment]
Nice solution. only thing is we looase the name of the KML file `map.geo.admin.ch_KML_20160822091838.kml` is that a problem ?

**Comment by loicgasser** [comment]
@davidoesch ?

**Comment by davidoesch** [comment]
yep, this is an issue if it affects all browser. if onyl safari and IE are affected.:ok

**Comment by loicgasser** [comment]
I mean new file name would be something like `JICZOrHIQ7yIcnGMooVMrQ.kml`
with this solution.

**Comment by davidoesch** [comment]
for all Browsers or only IE and safari?

**Comment by loicgasser** [comment]
For all

**Comment by davidoesch** [comment]
From a user perspective, this is a clear no go - and hard to explain. the source of download is not in the name, hard to remember filename. and bad from marketing. perspective...

-> invest here to get a human readable filenname

**Comment by loicgasser** [comment]
We'll go through CHSDI as before for now.
I don't know how feasible this is, direct download from S3 dosen't let us rename the file.
We'll keep it open and see if you can find a solution for a direct download and pretty file name.

**Comment by gjn** [comment]
Hi

for the local filename, use the 'download="filename.kml' property on the 
<a> tag element. It's html5. Most
browsers support it - only IE9 and safari don't. But that's maybe 
acceptable.

G.

**Comment by davidoesch** [comment]
If it is not supported for IE9 and safari... No issue. +1 for gin proposal

**Comment by oterral** [comment]
It's only  supported by the last  IE EDGE. [see](http://caniuse.com/#search=download)

**Comment by oterral** [comment]
and safari is commonly use.

**Comment by gjn** [comment]
I've updated the PR and deployed it [for testing](mf-geoadmin3.int.bgdi.ch/gjn_kmldown/727bb5d/1473078350/index.html)

**Comment by gjn** [comment]
For some reason, it doesn't work as expected, even in chrome and firefox.

**Comment by davidoesch** [comment]
ok.. and it fails as well in IE9

**Comment by gjn** [comment]
Let's put that to rest.

**Pull request closed without merging**
