### PR TITLE
Use node module for angular and angular-translate

### PR DESCRIPTION
**Pull request by oterral**
This PR facilitates the update of angular and angular-translate library. Just change the version number in `package.json`file and re-run `make dev` or `make all`

What do you think @gjn @procrastinatio @loicgasser ?

Update:
  The angular files are now ignored by git do you prefer we keep it in github?

### CODE REVIEW

**Comment by oterral** [comment]
jenkins test

**Comment by oterral** [comment]
jenkins test

**Comment by loicgasser** [comment]
+1

**Comment by gjn** [comment]
Downside: if npm is down, we can't deploy anymore. Hmm. Not sure about this.

**Comment by oterral** [comment]
Yes probably, that's why may be we should keep the angular files in `lib/` in github.

**Comment by loicgasser** [comment]
We kind of already can t deploy if npm is down. (From a fresh clone) We have a dependency to npm in chsdi as well. I like it for update simplicity. This is a huge advantage because we might do it more often.

**Comment by oterral** [comment]
I don't know why the travis failed can't eproduce, @gjn an idea? or we merge :)?

**Comment by gjn** [comment]
I think it needs a rebase.

I'll also removed travis building (it fails from time to time for no reason). The goal is to have jenkins/browserstack stable and reliable. I think I've improved browserstack by assuring that we don't restart apache during browserstack tests on ci environment.

**Comment by oterral** [comment]
I've rebased

**Comment by gjn** [comment]
jenkins test

**Comment by gjn** [comment]
jenkins test

**Comment by gjn** [comment]
bugger. all this stuff didn't seem to help. browserstack still unreliable. hmm.

jenkins test

**Comment by oterral** [comment]
jenkins test

**Pull request merged**
