### PR TITLE
Some fixes for some old issues

### LINKED ISSUE #2820: Measure : 3 circles don't display
call up this URL https://s.geo.admin.ch/67fa47f06d

3 circles are displayed:
http://www.awesomescreenshot.com/image/720574/d4292e5e4c179fe3989c41b0f1027be7 

zoom in: :boom: only one is visible
http://www.awesomescreenshot.com/image/720580/b6a22f736abcd47b9d33f29b85d35cab

expected result

If I draw three circles they are always visible

### LINKED ISSUE #3198: Profile:  Height scale: scale not adapted
Scale must be readable for differences of

2m
2-10m
10-50m
10-100m
100-250m
250-500m
500-750m
750-1000m

unbenannt

### LINKED ISSUE #3295: Time select box doesn't contain 'all' value for WMS
Happens only on mobile version with WMS time enabled layers.

The list of timestamps are present but the value 'all'.

### PR DESCRIPTION
**Pull request by oterral**
Fix #3198 [Test](https://mf-geoadmin3.dev.bgdi.ch/teo_fixes/?lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&X=170700.00&Y=609200.00&dev3d=true&zoom=3&debug&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege,KML%7C%7Chttps:%2F%2Fpublic.dev.bgdi.ch%2FqU0rRQ9mQvGQxtOtKF_o4A&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,)
Fix #2820 [Test](https://mf-geoadmin3.dev.bgdi.ch/teo_fixes/?topic=ech&lang=en&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege,KML%7C%7Chttps:%2F%2Fpublic.geo.admin.ch%2FBD1w7Fq9TWGEqU5mDO99Eg&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,&X=195734.00&Y=599190.00&zoom=9)
Fix #3295 [Test](https://mf-geoadmin3.dev.bgdi.ch/teo_fixes/mobile.html?topic=ech&lang=fr&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.geologie-gisgeol-flaechen-gt21000km2&layers_timestamp=&layers_opacity=0.75&mobile=true)
Fix pegman

### CODE REVIEW

**Comment by oterral** [comment]
Please review

**Comment by gjn** [comment]
LGTM. Tested a little.

The circles can still disappear when zooming too much. It's better than before but not optimal. I'll let @davidoesch decide if it's enough.

**Comment by davidoesch** [comment]
#2820 nok
#3198 ok
#3295 ok

**Comment by oterral** [comment]
For #2820 I've fixed the print, not the display.

**Pull request merged**
