### PR TITLE
add WMS geodienste.ch

### PR DESCRIPTION
**Pull request by dkottmann**
@davidoesch 

add planungszonen_v1_0_0 (deu, fra, ita) and planerischer_gewaesserschutz (ita)

<jenkins>A test link will be added here if the deploy on int succeeded.</jenkins>

### CODE REVIEW

**Comment by davidoesch** [comment]
Lgtm

**Comment by davidoesch** [comment]
@pakb  can u merge

**Comment by boecklic** [comment]
This PR actually broke our build. If a check fails it actually means something is not good and should be looked at. Please be careful when reviewing code!

**Comment by dkottmann** [comment]
@davidoesch @boecklic 

Sorry, i think lines 196-198 lack a "," at the end. Should i create a new commit?

**Comment by dkottmann** [comment]
@davidoesch 

The commit is not yet deployed. Did something go wrong? Should I create a new commit and pull request?

**Comment by davidoesch** [comment]
@pakb —- any update? Why this is not merged?

**Comment by procrastinatio** [comment]
It's not good practice to merge PR with failing tests

**Comment by davidoesch** [comment]
@dkottmann it has been deployed

**Pull request merged**
