### PR TITLE
BGDIINF_SB-2328, BGDIINF_SB-2493: Uses all backend from Frankfurt

### PR DESCRIPTION
**Pull request by ltshb**

### CODE REVIEW

**Comment by ltshb** [comment]
@pakb could you deploy this on a branch; `e.g. mf-geoadmin3.dev.bgdi.ch/frankfurt`.

**Comment by pakb** [comment]
[Test link](https://mf-geoadmin3.dev.bgdi.ch/feat-BGDIINF_SB-2328-frankfurt-migration/index.html)

**Comment by ltshb** [comment]
@pakb now that the migration is done could you check that this PR has been deployed on INT and DEV and then merge it ? Thanks.

**Comment by ltshb** [comment]
@pakb it seems that this has not been deployed on DEV ! mf-geoadmin3.dev.bgdi.ch is still using the old tod.dev.bgdi.ch ! Is there any cache to clear ?

**Comment by ltshb** [comment]
@pakb same for INT it seems this PR hasn't been deployed.

**Pull request merged**
