### PR TITLE
Change mouse icon on drag and drop

### LINKED ISSUE #3213: Change mouse icon on drag and drop
As mentioned in #3209. Change mouse icon on drag and drop as in moving mails in Gmail with drag and drop

### PR DESCRIPTION
**Pull request by Jenselme**
- Apply the cursor grab theme when dragging a layer.

Close #3213

### CODE REVIEW

**Comment by gjn** [comment]
add to whitelist

**Comment by gjn** [comment]
Doesn't work on chrome and IE. Does work on Firefox.

**Comment by loicgasser** [comment]
grab,grabbing not supported on IE and sometimes needs to be prefixed with -moz/-webkit. 
Would be nice to have the transition grab->grabbing

**Comment by Jenselme** [comment]
`-web-grab` fixes the problem on webkit but not IE. I tried with:
`cursor: url(http://www.worldtimzone.com/mozilla/testcase/css3cursors_files/grab.gif), default !important;` but that still doesn't work on IE.

**Comment by Jenselme** [comment]
Just updated the PR. Works on FF, chrome and IE. On IE, you have to move the cursor for the style to be applied.

**Comment by gjn** [comment]
[Testlink](https://mf-geoadmin3.dev.bgdi.ch/3213-mouse-cursor-dnd)

@Jenselme On IE, it's not a grabbing hand, but a pan icon (https://thenounproject.com/term/pan/275/) . Any way to get the hand as well?

**Comment by Jenselme** [comment]
@gjn Strange, it works fine on the dev version. Could it be that `cursor: url(/img/grab.cur), move;` is removed in the build process for prod?

**Comment by gjn** [comment]
Path is absolute. We need it relative. See https://github.com/geoadmin/mf-geoadmin3/blob/master/src/components/topic/style/topic.less#L8

**Comment by Jenselme** [comment]
@gjn Thanks for pointing that out. PR updated.

**Comment by gjn** [comment]
A flaw in the build system prevents the testing of this in a deployed branch. I'll merge.

**Comment by gjn** [comment]
Confirmed: works fine in IE now. Thanks alot @Jenselme for your contribution.

**Pull request merged**
