### PR TITLE
Fix #2298: Change print menu and submit button names

### LINKED ISSUE #2298: UI refactoring: Print menu
Improve menu and button names to 'Imprimer' and 'Créer PDF pour impression'.

### PR DESCRIPTION
**Pull request by kandre**
[Test link](http://mf-geoadmin3.dev.bgdi.ch/kan_UI_print_menu)

### CODE REVIEW

**Comment by kandre** [comment]
jenkins

**Comment by kandre** [comment]
Jenkins

**Comment by gjn** [comment]
you need to write 'jenkins test' :)

**Comment by kandre** [comment]
was looking for that thanks :)

**Comment by oterral** [comment]
jenkins test

**Comment by kandre** [comment]
jenkins test

**Comment by kandre** [comment]
Pull-rebased-pushed again to be sure

**Comment by kandre** [comment]
jenkins test

**Comment by gjn** [comment]
A push will automatically trigger a new build.

Anyway, I think the tests needs to be adapted because the text changed.

`WebDriver.findElement(By.xpath("//button[contains(text(), 'Drucken')]"))` fails. Please adapt the tests accordingly.

Note: you can run the tests locally by doing `make teste2e` on your account before pushing.

**Comment by kandre** [comment]
jenkins test

**Comment by kandre** [comment]
jenkins test

**Comment by gjn** [comment]
First step. Thanks alot.

**Pull request merged**
