### PR TITLE
[3D] Tooltip

### PR DESCRIPTION
**Pull request by oterral**
[Test](https://mf-geoadmin3.dev.bgdi.ch/teo_tooltip/?lang=de&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&dev3d=true&catalogNodes=457,477&layers=ch.bafu.biogeographische_regionen,KML%7C%7Chttps:%2F%2Fpublic.dev.bgdi.ch%2FCTi7TRMuSzOaoMDKrOX34Q&layers_opacity=0.75,1&lon=8.02901&lat=45.77825&elevation=140393&heading=3.854&pitch=-49.398)

### CODE REVIEW

**Comment by davidoesch** [comment]
not yet completely working ....

**Comment by oterral** [comment]
What is not working ?

**Comment by cedricmoullet** [comment]
KML tooltip is not active (most probably because 3d polygone is not over the terrain but on level zero)

**Comment by cedricmoullet** [comment]
@davidoesch what is not working ? I juste tested with agnes, swissimage index, lubis and it works quite fine

**Comment by davidoesch** [comment]
The highlight... But this is part will be solved according this mornings discussion

**Comment by davidoesch** [comment]
A bottle of wine for the person who is able to activate the tooltip under 3 clicks for LUBIS, this one here

https://mf-geoadmin3.dev.bgdi.ch/ltmoc/?dev3d=true&topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-grau&layers=WMS||Fahrverbotszone||https:%2F%2Fwww.gis.stadt-zuerich.ch%2Fmaps%2Fservices%2Fwms%2FWMS-ZH-STZH-OGD%2FMapServer%2FWMSServer%3F||Fahrverbotszone,ch.swisstopo.lubis-luftbilder_schwarzweiss&lon=8.52832&lat=47.36259&elevation=517&heading=74.861&pitch=-35.138&catalogNodes=457,458,477,485&layers_timestamp=,99991231

**Comment by cedricmoullet** [comment]
I did it 3 !!!!! I promise !!!


2015-09-16 20:11 GMT+02:00 davidoesch <notifications@github.com>:

> A bottle of wine for the person who is able to activate the tooltip under
> 3 clicks for LUBIS, this one here
>
>
> https://mf-geoadmin3.dev.bgdi.ch/ltmoc/?dev3d=true&topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-grau&layers=WMS||Fahrverbotszone||https:%2F%2Fwww.gis.stadt-zuerich.ch%2Fmaps%2Fservices%2Fwms%2FWMS-ZH-STZH-OGD%2FMapServer%2FWMSServer%3F||Fahrverbotszone,ch.swisstopo.lubis-luftbilder_schwarzweiss&lon=8.52832&lat=47.36259&elevation=517&heading=74.861&pitch=-35.138&catalogNodes=457,458,477,485&layers_timestamp=,99991231
> <https://mf-geoadmin3.dev.bgdi.ch/ltmoc/?dev3d=true&topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-grau&layers=WMS%7C%7CFahrverbotszone%7C%7Chttps:%2F%2Fwww.gis.stadt-zuerich.ch%2Fmaps%2Fservices%2Fwms%2FWMS-ZH-STZH-OGD%2FMapServer%2FWMSServer%3F%7C%7CFahrverbotszone,ch.swisstopo.lubis-luftbilder_schwarzweiss&lon=8.52832&lat=47.36259&elevation=517&heading=74.861&pitch=-35.138&catalogNodes=457,458,477,485&layers_timestamp=,99991231>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/pull/2638#issuecomment-140825238>
> .
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://t.sidekickopen21.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XYgf6M1WN1qfVVMRYFRqW8qlQyH56dByMf1q8vLz02?t=http%3A%2F%2Ftwitter.com%2Fcedricmoullet&si=6057645868318720&pi=e4333dd6-8c78-4412-d12c-1b4df1c99fe1>

**Comment by cedricmoullet** [comment]
But there is for sure place for improvement ;-)

2015-09-16 20:16 GMT+02:00 Cédric MOULLET <cedric.moullet@gmail.com>:

> I did it 3 !!!!! I promise !!!
>
>
> 2015-09-16 20:11 GMT+02:00 davidoesch <notifications@github.com>:
>
>> A bottle of wine for the person who is able to activate the tooltip under
>> 3 clicks for LUBIS, this one here
>>
>>
>> https://mf-geoadmin3.dev.bgdi.ch/ltmoc/?dev3d=true&topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-grau&layers=WMS||Fahrverbotszone||https:%2F%2Fwww.gis.stadt-zuerich.ch%2Fmaps%2Fservices%2Fwms%2FWMS-ZH-STZH-OGD%2FMapServer%2FWMSServer%3F||Fahrverbotszone,ch.swisstopo.lubis-luftbilder_schwarzweiss&lon=8.52832&lat=47.36259&elevation=517&heading=74.861&pitch=-35.138&catalogNodes=457,458,477,485&layers_timestamp=,99991231
>> <https://mf-geoadmin3.dev.bgdi.ch/ltmoc/?dev3d=true&topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-grau&layers=WMS%7C%7CFahrverbotszone%7C%7Chttps:%2F%2Fwww.gis.stadt-zuerich.ch%2Fmaps%2Fservices%2Fwms%2FWMS-ZH-STZH-OGD%2FMapServer%2FWMSServer%3F%7C%7CFahrverbotszone,ch.swisstopo.lubis-luftbilder_schwarzweiss&lon=8.52832&lat=47.36259&elevation=517&heading=74.861&pitch=-35.138&catalogNodes=457,458,477,485&layers_timestamp=,99991231>
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <http://t.sidekickopen21.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XYgf6M1WN1qfVVMRYFRqW8qlQyH56dByMf1q8vLz02?t=https%3A%2F%2Fgithub.com%2Fgeoadmin%2Fmf-geoadmin3%2Fpull%2F2638%23issuecomment-140825238&si=6057645868318720&pi=03d11030-232d-44c5-f5a5-50951d35d110>
>> .
>>
>
>
>
> --
> Twitter: http://twitter.com/cedricmoullet
> Linked In: http://www.linkedin.com/in/cedricmoullet
>
>
> <http://t.sidekickopen21.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XYgf6M1WN1qfVVMRYFRqW8qlQyH56dByMf1q8vLz02?t=http%3A%2F%2Ftwitter.com%2Fcedricmoullet&si=6057645868318720&pi=e4333dd6-8c78-4412-d12c-1b4df1c99fe1>
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://t.sidekickopen21.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XYgf6M1WN1qfVVMRYFRqW8qlQyH56dByMf1q8vLz02?t=http%3A%2F%2Ftwitter.com%2Fcedricmoullet&si=6057645868318720&pi=03d11030-232d-44c5-f5a5-50951d35d110>

**Comment by cedricmoullet** [comment]
@oterral I have also difficulty to select an item. How is the tolerance managed ?

**Comment by oterral** [comment]
There is the same problem in 2d.
There is a tolerance parameter(5 pixels) in the request. I guess we could modify it depending on the zoom level .

Anybody has a secret formula for that ?

**Comment by cedricmoullet** [comment]
Shouldn't it be dependent of the distance between the camera and the
clicked point ?

2015-09-17 9:31 GMT+02:00 oterral <notifications@github.com>:

> There is the same problem in 2d.
> There is a tolerance parameter(5 pixels) in the request. I guess we could
> modify it depending on the zoom level .
>
> Anybody has a secret formula for that ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/pull/2638#issuecomment-140991984>
> .
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://t.sidekickopen21.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XYgf6M1WN1qfVVMRYFRqW8qlQyH56dByMf1q8vLz02?t=http%3A%2F%2Ftwitter.com%2Fcedricmoullet&si=6057645868318720&pi=711942e6-09c6-494c-a457-9e9cf9580d2f>

**Comment by oterral** [comment]
In 3d, maye be yes

**Comment by gjn** [comment]
Formula has to be reversed engineered, I guess.

`tolerance in pixels = f(distance to point)`

**Comment by davidoesch** [comment]
+1 for Gilbert proposal - will solve a lot of issue in 2d as well especially on mobile / touch devices. We need to really test this thourghly

**Comment by procrastinatio** [comment]
You have to be at close range to click on features. Cliking on feature at the horizon is not useful.

**Comment by davidoesch** [comment]
Well the user will click in whatever position he is... Close or far, tilt it nadir

**Comment by oterral** [comment]
@cedricmoullet and @davidoesch I've added the highlight of features when mouse is over the tooltip.

[Test](https://mf-geoadmin3.dev.bgdi.ch/teo_tooltip/?lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&dev3d=true&X=209750.00&Y=628500.00&zoom=2&layers=ch.bafu.biogeographische_regionen,ch.swisstopo.geologie-geodaesie-bouguer_anomalien,KML%7C%7Chttps:%2F%2Fpublic.dev.bgdi.ch%2Fnq75nInrTcizMcXKCeQnGQ,ch.bafu.hydroweb-messstationen_vorhersage&catalogNodes=457,477&layers_opacity=0.75,1,1,1)

**Comment by cedricmoullet** [comment]
Great. Shouldn't we add the "Zoom To icon" in the feature header ?

2015-09-17 15:12 GMT+02:00 oterral <notifications@github.com>:

> @cedricmoullet <https://github.com/cedricmoullet> and @davidoesch
> <https://github.com/davidoesch> I've added the highlight of features when
> mouse is over the tooltip.
>
> Test
> <https://mf-geoadmin3.dev.bgdi.ch/teo_tooltip/?lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&dev3d=true&X=209750.00&Y=628500.00&zoom=2&layers=ch.bafu.biogeographische_regionen,ch.swisstopo.geologie-geodaesie-bouguer_anomalien,KML%7C%7Chttps:%2F%2Fpublic.dev.bgdi.ch%2Fnq75nInrTcizMcXKCeQnGQ,ch.bafu.hydroweb-messstationen_vorhersage&catalogNodes=457,477&layers_opacity=0.75,1,1,1>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/pull/2638#issuecomment-141078894>
> .
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>

**Comment by davidoesch** [comment]
- it even works better now in 2d: https://mf-g
eoadmin3.dev.bgdi.ch/teo_tooltip/?lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&dev3d=true&layers=ch.bafu.hydroweb-messstationen_gefahren&catalogNodes=457,477&X=283964.76&Y=589598.81&zoom=2

-3d: better now for
https://mf-geoadmin3.dev.bgdi.ch/teo_tooltip/?lang=fr&topic=luftbilder&bgLayer=ch.swisstopo.pixelkarte-grau&dev3d=true&layers=ch.swisstopo.lubis-luftbilder_schwarzweiss,ch.swisstopo.lubis-luftbilder_farbe&layers_timestamp=99991231,99991231&catalogNodes=1179,1180,1186&lon=8.52884&lat=47.35977&elevation=682&heading=0.016&pitch=-39.587

@cedric:" Shouldn't we add the "Zoom To icon" in the feature header" what
do you mean by this?

**Comment by cedricmoullet** [comment]
I meant to put 
image in the feature header of the tooltip

**Comment by oterral** [comment]
It's normal ch.bafu.hydroweb-messstationen_gefahren is a geojson layer, no identify request are triggered.

**Comment by oterral** [comment]
@cedricmoullet yes we could, i guess.

**Comment by davidoesch** [comment]
this is the "link to object" link in the bottom IMHO

the zoom: after print, minimize and close: to many icons, the tootlip
becoems to heavy ..... iconography-of-confusion

**Comment by davidoesch** [comment]
fo geojson: ch.bafu.hydroweb-messstationen_gefahren it works

**Comment by oterral** [comment]
we could add the zoom image near the link to object

**Comment by davidoesch** [comment]
Add: not an icon but a text : zoom to object / link to objekt

**Comment by oterral** [comment]
Yes why not  but the icon zoom is everywhere in the application. I found the icon more consistent with rest of your app. But as you wish, if you prefer th link.

**Comment by davidoesch** [comment]
Let's sleep over this one --- other opinions? @Gilbert?

**Comment by gjn** [comment]
Link to object is not the same as zoom to object. The first opens a new window, the second doesn't.

Not sure I would add a zoom to. And if we add it, we should you same icon as in other places.

**Comment by davidoesch** [comment]
the zoom (magnifying glass) is a rather an icon for search....than zoom .

but I agree: a zoom to function makes sense, but rather a double klick on the geometry symbol itself than a link/icon in the pop up text.....

**Comment by oterral** [comment]
Can we merge this one since the "zoom to" functionnaility  and the tolerance stuff are not regression but enhancements ?

**Comment by gjn** [comment]
jenkins test

**Pull request merged**
