### PR TITLE
Use a vector layer for crosshair

### PR DESCRIPTION
**Pull request by oterral**
[bowl](https://mf-geoadmin3.dev.bgdi.ch/teo_cross/index.html?crosshair=bowl)
[circle](https://mf-geoadmin3.dev.bgdi.ch/teo_cross/index.html?crosshair=circle)
[cross](https://mf-geoadmin3.dev.bgdi.ch/teo_cross/index.html?crosshair=cross)
[point](https://mf-geoadmin3.dev.bgdi.ch/teo_cross/index.html?crosshair=point)
[marker](https://mf-geoadmin3.dev.bgdi.ch/teo_cross/index.html?crosshair=marker)
[Bad value default to marker](https://mf-geoadmin3.dev.bgdi.ch/teo_cross/index.html?crosshair=badvalue)

### CODE REVIEW

**Comment by gjn** [comment]
jenkins test

**Comment by gjn** [comment]
Does printin them work? Couldn't test because print on dev is now down.

**Comment by oterral** [comment]
I've redeployed a war on test it should work now.

**Comment by gjn** [comment]
no yet...

**Comment by gjn** [comment]
@oterral In the app, everything is well.

When printing, the marker will be behind any layer that is added to the map. If the layer is opaque, the marker can't be seen in the print.

**Comment by oterral** [comment]
@gjn it's not related to this PR the search marker is also printed behind an opaque layer added further

**Comment by oterral** [comment]
I create an issue

**Comment by gjn** [comment]
ok. marker printing does not seem to work anyway on prod right now (see the issue you created).

So I'll merge this.

**Comment by gjn** [comment]
The printing is a regression. On prod, the crosshair never disappears behind a layer. So I'll move #2973 to prio 1.

**Pull request merged**
