### PR TITLE
Use MapProxy autoscaling addresses

### PR DESCRIPTION
**Pull request by loicgasser**
This is a [TestLink](https://mf-geoadmin3.dev.bgdi.ch/gal_autoscaling/?dev3d=true) for @danduk82 . When all problems are solved, we can merge this one.

### CODE REVIEW

**Comment by loicgasser** [comment]
All good now.

**Comment by loicgasser** [comment]
jenkins test

**Comment by danduk82** [comment]
From my side everything is OK. The requests come on the right backends, and the tiles are cached in S3. It is incredibly faster with chrome...

**Comment by procrastinatio** [comment]
Looks good

**Pull request merged**
