### PR TITLE
Add https to help links

### PR DESCRIPTION
**Pull request by ponceta**
In the purpose of going full HTTPS, this PR redirect all help queries to https://help.geo.admin.ch/

This goes in the sense of #2238

### CODE REVIEW

**Comment by gjn** [comment]
Please merge when the source is correct as well.

**Comment by ponceta** [comment]
I'll need to have access to the source to modify it.

**Comment by oterral** [comment]
maybe a stupid question but where we use these ids `are_help_link_href` ?

**Comment by ponceta** [comment]
tooltip?

**Comment by gjn** [comment]
https://github.com/geoadmin/mf-geoadmin3/blob/master/src/index.mako.html#L176

**Comment by gjn** [comment]
The source is a google spreadsheet. It's no use if it isn't changed there.

**Comment by oterral** [comment]
ah yes , but a 2nd question question comes to my mind, It is always the same links, we could  just remove this and put an agnostic url in index.mako but probably there was a reason for that.

**Comment by ponceta** [comment]
Non there's a script.js for the side menu, the fusion table is hosting only the content.

**Comment by gjn** [comment]
yes, but this content (what I meant by source) needs to be updated as well, otherwise we'll overwrite again on next translate.

**Comment by ponceta** [comment]
The doc is up to date, I've generated the json files with it.

**Comment by gjn** [comment]
ok. Thanks alot.

**Comment by oterral** [comment]
@gjn do you see my last comment? could just get rid of these translations?

**Comment by gjn** [comment]
Yes, you are right. They can be removed from the translations as they are always the same for each topic.

@ponceta Could you do that?

**Comment by ponceta** [comment]
Yes of course, we just need to be sure that all these links are not used anymore anywhere else @davidoesch @mariokeusen @cedricmoullet 

Meaning the one of 
 - are_help_link_href
 - bafu_...
 - blw
 - ech
 - funksender
 - geol
 - inspire
 - ivs
 - kgs
 - nga
 - sachplan
 - swisstopo
 - luftbilder
 - aviation
 - mgdi
 - gewiss
 - wildruhezonen
 - vu

**Comment by gjn** [comment]
The *_help_link_href are always the same for all topics. So we can remove them and put the link directly in the index.mako.html (see reference above) are topic independant.

AFAIK, the translation spreadsheet is only used by this project.

**Pull request merged**
