### PR TITLE
Add browser IE for test (light)

### PR DESCRIPTION
**Pull request by alcapat**
and prepare test for opera and Safari

### CODE REVIEW

**Comment by alcapat** [comment]
jenkins test

**Comment by gjn** [comment]
Finally IE tests with saucelabs!

Did you verify on the sauclabes page that they are really run?

**Comment by alcapat** [comment]
@gjn : for the PR we test only with top_browser (FF 44) 
Here a print screen of test from command line.

`Starting SauceLabs script!
Start test at 24/03/16 10:48
+--> Start test with Windows 7 internet explorer (9.0)
Start https://mf-geoadmin3.ci.bgdi.ch:
Start Test Ok!
It took 12.77 to execute start...
--- end test for this browser
+--> Start test with Windows 7 internet explorer (10.0)
Start https://mf-geoadmin3.ci.bgdi.ch:
Start Test Ok!
It took 8.93 to execute start...
--- end test for this browser
+--> Start test with Windows 7 internet explorer (11.0)
Start https://mf-geoadmin3.ci.bgdi.ch:
Start Test Ok!
It took 9.18 to execute start...
--- end test for this browser
End full tests
End test at 24/03/16 10:49
0:00:58.836691 secondes
`

**Comment by gjn** [comment]
Great. Could you also add Edged on Win 10?

**Comment by alcapat** [comment]
https://wiki.saucelabs.com/display/DOCS/Platform+Configurator#/
For edge we can have that [1], i wil try to add it and test.

[1]
caps = {'browserName': "MicrosoftEdge"}
caps['platform'] = "Windows 10"
caps['version'] = "13.10586"

**Comment by gjn** [comment]
And at the same time, you could remove the browserstack tests completely. If we have it in saucelabs, no need to have it in browserstack.

Nice easter present :=)

**Pull request merged**
