### PR TITLE
[Build error] Revert closure compiler version

### PR DESCRIPTION
**Pull request by loicgasser**
[Test link](https://mf-geoadmin3.int.bgdi.ch/[BRANCH_NAME]/index.html)
This link will work only if the build succeed

Trying to build the project result in the following error:

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/google/javascript/jscomp/CommandLineRunner : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:312)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
Makefile:754: recipe for target '.build-artefacts/app.js' failed
make[1]: *** [.build-artefacts/app.js] Error 1
make[1]: Leaving directory '/home/ltgal/mf-geoadmin3'
Makefile:183: recipe for target 'user' failed
make: *** [user] Error 2
```

java version:

```
$ java -version
java version "1.7.0_151"
OpenJDK Runtime Environment (IcedTea 2.6.11) (7u151-2.6.11-2~deb8u1)
OpenJDK 64-Bit Server VM (build 24.151-b01, mixed mode)
```

meaning  we have a higher JDK during compile time and lower JDK during run-time and  I don't think we compile closure compiler ourselves.

<jenkins>[Test link](https://mf-geoadmin3.int.bgdi.ch/gal_closure_compiler/index.html)</jenkins>

### CODE REVIEW

**Comment by loicgasser** [comment]
Because during branch deployment in our CI we create a folder outside the current directory to clone and deploy the branch, this might result in conflicts when push several commits in a row and create conflicts.
I added a commit to solve this issue.

**Comment by loicgasser** [comment]
some weird, permission denied on pip in the virtualenv of the branch.

/bin/bash: .build-artefacts/python-venv/bin/pip: /home/jenkins-slave/workspace/3_PR-4174-QLDNEZQTG4AF5DV5YSDD/clone-builds/gal: bad interpreter: Permission denied

Maybe something that has to do with Jenkins conf.

**Comment by oterral** [comment]
You need java 8 to build mf-geoadmin3.

**Comment by oterral** [comment]
keep the last version of the clossure compiler and take the java8  i have in my home then put the bin folder in the path:
```
export JAVA_HOME=~/jre1.8.0_151
export PATH=$JAVA_HOME/bin:$PATH

```

**Comment by gjn** [comment]
...not a fan of relying on local setups for the build. It should work on standard machines.  can't we update mf1?

On Monday, February 26, 2018, oterral wrote:
> keep the last version of the clossure compiler and take the java8  i have in my home then put the bin folder in the path:
> ```
> export JAVA_HOME=~/jre1.8.0_151
> export PATH=$JAVA_HOME/bin:$PATH
> 
> ```
> 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/geoadmin/mf-geoadmin3/pull/4174#issuecomment-36841527

-- 
Sent from my Jolla

**Comment by oterral** [comment]
I wanted but it was straight forward the last time I asked.

**Comment by gjn** [comment]
Hmm, certainly not optimal. We should insist. Env should be clear and managed by puppet ( or docker)

On Monday, February 26, 2018, oterral wrote:
> I wanted but it was straight forward the last time I asked. 
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/geoadmin/mf-geoadmin3/pull/4174#issuecomment-36842414

-- 
Sent from my Jolla

**Comment by oterral** [comment]
Yes I think there is some project which are dependent from java7 on dev like the print

**Comment by gjn** [comment]
I understand. But there are ways to have multiple java ens on same machine. It's quite standard then to specify in your build the one you want.

On Monday, February 26, 2018, oterral wrote:
> Yes I think there is some project which are dependent from java7 on dev like the print
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/geoadmin/mf-geoadmin3/pull/4174#issuecomment-36844041

-- 
Sent from my Jolla

**Comment by oterral** [comment]
Of cours I'm totally in favor it. I open a ticket for @danduk82

**Comment by danduk82** [comment]
@oterral , you need oracle java or does openjdk fulfill the job? (it's really painful to use oracle java)

**Comment by danduk82** [comment]
using stretch instead of jessie would have openjdk8 by default...

**Comment by danduk82** [comment]
(sorry, I pushed the wrong button)

**Comment by oterral** [comment]
Currently I use the oracle one but openjsdk should do the job

**Comment by loicgasser** [comment]
I removed the last commit, let's change back when we update default JAVA.

**Comment by oterral** [comment]
No, others devs have their setup already corrected for java 8 :)  and we can't utpdate ol if revert the version of closure.

**Comment by danduk82** [comment]
see the [jira ticket](https://jira.swisstopo.ch/browse/BGDIINF_SB-601)

**Comment by oterral** [comment]
Only the closure compiler needs to be downgraded

**Pull request merged**
