### PR TITLE
v004 of lbm is in production, we will give it to you

### PR DESCRIPTION
**Pull request by ltkum**
<jenkins>A test link will be added here if the deploy on int succeeded.</jenkins>

Version 4 is out and my previous pull request was merged a little bit too fast. v003 is no longer on prod, by the way.

<jenkins>[Test link](https://mf-geoadmin3.int.bgdi.ch/ltkum_lbm_v004/index.html)</jenkins>

### CODE REVIEW

**Comment by ltkum** [comment]
@davidoesch @danduk82 

Just to keep you two updated, and perhaps let your try the test link

**Comment by davidoesch** [comment]
yep... https://mf-geoadmin3.int.bgdi.ch/mvt/index.html? is broken letme knwo when we can continue with the test  cc @oterral @loicgasser

**Comment by ltkum** [comment]
@davidoesch 
I redeployed a tileserver prod version with both v003 and v004, that way, you aren't hindered while waiting for this PR to be reviewed.

**Comment by davidoesch** [comment]
thanks
@oterral @loicgasser  you can switch the app to 004

**Pull request merged**
