### PR TITLE
Fix standalone WMS and KML examples

### PR DESCRIPTION
**Pull request by gberaudo**
I am trying to run the [importkml](https://mf-geoadmin3.dev.bgdi.ch/gberaudo/src/components/importkml/example/) and [importwmts](https://mf-geoadmin3.dev.bgdi.ch/gberaudo/src/components/importwms/example/) examples but it doesn't work.

Links:
- https://mf-geoadmin3.dev.bgdi.ch/gberaudo_fix_examples/src/components/importwms/example/index.html?lang=en
- https://mf-geoadmin3.dev.bgdi.ch/gberaudo_fix_examples/src/components/importkml/example/index.html?lang=en

### CODE REVIEW

**Comment by gberaudo** [comment]
Currently, angular complains about unkwon provider gaLangProvider:
```
Error: [$injector:unpr] Unknown provider: gaLangProvider <- gaLang <- gaLayers <- gaMapDirective <- gaLayers
http://errors.angularjs.org/1.4.2/$injector/unpr?p0=gaLangProvider%20%3C-%20gaLang%20%3C-%20gaLayers%20%3C-%20gaMapDirective%20%3C-%20gaLayers
    at angular.js:68
    at angular.js:4264
    at Object.getService [as get] (angular.js:4411)
    at angular.js:4269
    at getService (angular.js:4411)
    at Object.invoke (angular.js:4443)
    at angular.js:4270
    at getService (angular.js:4411)
    at Object.invoke (angular.js:4443)
    at angular.js:6943
```

**Comment by loicgasser** [comment]
Probably some missing require in the map service.  Examples have not been maintained for a while.

**Comment by gberaudo** [comment]
Thanks @loicgasser, I could make these two examples load without error.

**Comment by gjn** [comment]
@gberaudo Could you please rebase and squash this?

I can do it if you can't find time.

**Comment by gberaudo** [comment]
@gjn, indeed I am a bit short of time this week; would be great if you could handle it.

**Comment by gjn** [comment]
@oterral Merge when re-basable. Otherwise, we close.

**Comment by gberaudo** [comment]
@gjn, @oterral I will rebase it now.

**Comment by gberaudo** [comment]
I updated my node version as explained by @oterral and rebased. It compiled cleanly but I had issues at runtime. I then compiled master (from this morning) and noticed the same problems:
- access to `services` and `layersConfig` in debug mode;
- an undefined access in production mode.

Could someone be kind to check if he can reproduce the problem (or is it only on my side!)?

$ node -v
v4.4.7

https://mf-geoadmin3.dev.bgdi.ch/gberaudo/src/?lang=en&X=169418.43&Y=682185.73&zoom=1
GET https://mf-geoadmin3.dev.bgdi.ch/gberaudo/src/services 404
GET https://mf-geoadmin3.dev.bgdi.ch/gberaudo/src/layersConfig?lang=en 404


https://mf-geoadmin3.dev.bgdi.ch/gberaudo/?lang=en&X=169418.43&Y=682185.73&zoom=1
build.js:203 TypeError: Cannot read property 'length' of undefined
    at h (build.js:1192)
    at build.js:1192
    at build.js:215
    at r.$eval (build.js:229)
    at r.$digest (build.js:226)
    at r.$apply (build.js:230)
    at g (build.js:183)
    at T (build.js:188)
    at XMLHttpRequest.w.onload (build.js:189)

**Comment by oterral** [comment]
I look this tomorrow.

**Comment by oterral** [comment]
@gberaudo 2 solutions : 
1) Checkout the last version of mf-geoadmin3
    Create a `rc_user_gberaudo` file then change the `API_URL ` to `//mf-chsdi3.dev.bgdi.ch/` inside. 
    Re-run `make clean user`

 2) Otherwise checkout the mf-chsdi3 project 
     Run `make user`
     Restart apache

**Comment by gberaudo** [comment]
Thanks @oterral. This PR is now rebased and squashed.

**Comment by oterral** [comment]
Thanks @gberaudo for this !!!!

**Pull request merged**
