### PR TITLE
Load FastClick everytime

### PR DESCRIPTION
**Pull request by oterral**
Fix 80% of #3408

80% of problems can be fixed by leting FastClick decide if it must activated or not.

20% of other problems: 
   - draw interaction needs to be improve. PR is coming.
   -  other map interactions needs to be tested (contextpopup conflict with others event)
   - `:hover` css can't be removed because most of browser doesn't support [css4 hover media](http://caniuse.com/#search=media%20features). This could be done using 2 different css files for mobile and desktop but I think it doesn't worth to spend time on it.  

[Test](https://mf-geoadmin3.int.bgdi.ch/teo_pointertype/index.html)

### CODE REVIEW

**Comment by gjn** [comment]
Is there a reported issue for this?

**Comment by loicgasser** [comment]
I guess this fixes some of the issues described in: https://github.com/geoadmin/mf-geoadmin3/issues/3408

**Comment by oterral** [comment]
Yes sorry forget to add the link to the issue

**Comment by gjn** [comment]
This needs good testing on all desktop browsers.

**Comment by oterral** [comment]
On our PC browsers (IE, FF, CH) and on the mac pro, FastClick is never activated.

Summarize  FastClick is activated if :  

    - the device support touch events and if: 
             - it's android + chrome on certain meta tag conditions
             - it's blackbery 10
             - it's firefox < 27 or  on certain meta tag conditions
             - it's iOS

**Pull request merged**
